-- ============================================================================
-- EmpossDurr content expansion: adds 484 new words/clue-sets on top of the
-- original 20-word seed batch in empossdurr_words_seed.sql (504 total,
-- verified against a fresh local load -- no duplicate words, no clue that
-- shares a root/lemma with its own word, checked programmatically as well
-- as by eye). Family playtesting confirmed the mode plays great and burns
-- through a small deck fast -- this bulks up the pool so replays don't
-- start repeating words within the same game night. Two INSERT statements
-- in this one file: the first (296 words) covers the family-edited batch
-- plus a first new-word wave; the second (188 words) is a further new-word
-- wave to close the gap to 504 total.
--
-- This file REPLACES the earlier, smaller empossdurr_words_expansion.sql --
-- that one was never run against any database, so there's nothing live to
-- reconcile. Safe to run once, start to finish, against a fresh database
-- that only has the 20-word seed loaded.
--
-- Purely additive: does NOT touch, modify, or delete any existing row. The
-- table already exists (created by empossdurr_words_seed.sql) and uses a
-- plain SERIAL id, so there's no MAX(id)-style numbering dance needed, just
-- a plain INSERT.
--
-- Content rules (refined from a direct family bug report on the clues, and
-- do not violate when adding more):
--   1. ADJACENT, NOT DIRECT -- this is the big one. A clue must not lead
--      almost straight back to the word. Illustrative example: if the word
--      were JESUS, "risen" or "crucifixion" would be a dead giveaway --
--      those terms basically ARE Jesus, not just associated with him. A
--      good clue sits one conceptual step away and could describe multiple
--      different things, not just this one.
--   2. No clue may share a root/lemma with the word itself.
--   3. A clue should be plausible for at least one OTHER word too -- if you
--      can't think of a second candidate, it's too tight (this is really
--      the same idea as rule 1, restated as a test you can run per-clue).
--   4. No rhymes or sound-alikes with zero semantic connection.
--   5. Loose and evocative beats tight and "correct."
--   6. Words don't have to be a single token -- a common two-word (or
--      three-word) compound noun is fine as long as the pair reads as one
--      indivisible concept.
--   7. Proper nouns, brands, and pop-culture references are fair game (the
--      original 10%-cap guidance is superseded by this batch's looser,
--      family-tested direction) -- just keep applying rule 1 to them same
--      as anything else.
--
-- No overlap with the seed file's 20 words (PIZZA, UMBRELLA, GUITAR,
-- VOLCANO, SANDWICH, LIGHTHOUSE, TREASURE CHEST, FIREFLY, ROLLER COASTER,
-- CHIMNEY, SNOWMAN, CAMPFIRE, ESCALATOR, BEEHIVE, SUBMARINE, XYLOPHONE,
-- ANCHOR, FIREFIGHTER, SCARECROW, IGLOO). PIZZA was dropped from the
-- family-edited batch below for that reason (it's already in the seed).
-- ============================================================================

INSERT INTO empossdurr_words (word, clue_1, clue_2, clue_3, clue_4) VALUES
    -- ---- Family-edited batch (kept as written, two clues tightened to fit
    -- the adjacent-not-direct rule -- see notes on TONGUE and WATER TOWER) ----
    ('BACKPACK', 'heavy', 'frame', 'dora', 'stuffed'),
    ('TRAMPOLINE', 'bounce', 'springs', 'backyard', 'somersault'),
    ('LEMONADE STAND', 'pitcher', 'summer', 'rip-off', 'ice'),
    ('SKATEBOARD', 'tony', 'ramp', 'vans', 'grind'),
    ('THUNDERSTORM', 'front porch', 'clouds', 'rumble', 'flash'),
    ('PIRATE SHIP', 'plank', 'mast', 'cannon', 'flag'),
    ('VENDING MACHINE', 'coins', 'soda', 'jam', 'alley'),
    ('HAMMOCK', 'sway', 'banana', 'backyard', 'nap'),
    ('BUTTERFLY', 'colorful', 'wings', 'garden', 'net'),
    ('TELESCOPE', 'stars', 'lens', 'glass', 'zoom'),
    ('DRAGONFLY', 'pond', 'wings', 'buzz', 'iridescent'),
    ('SANDCASTLE', 'beach', 'bucket', 'moat', 'tide'),
    ('FERRIS WHEEL', 'carnival', 'spokes', 'view', 'circle'),
    ('POPCORN', 'kernel', 'butter', 'movie', 'salty'),
    ('SLEEPING BAG', 'campout', 'zipper', 'cocoon', 'tent'),
    ('WATERFALL', 'cliff', 'mist', 'roar', 'plunge'),
    ('PARACHUTE', 'skydive', 'canopy', 'harness', 'freefall'),
    ('HOURGLASS', 'sand', 'timer', 'flip', 'minutes'),
    ('SCUBA DIVER', 'tank', 'flippers', 'coral', 'bubbles'),
    ('PIGGY BANK', 'coins', 'slot', 'savings', 'ceramic'),
    ('WHEELBARROW', 'dirt', 'garden', 'tip', 'handle'),
    ('KANGAROO', 'pouch', 'hop', 'marsupial', 'outback'),
    ('TRAFFIC LIGHT', 'intersection', 'red', 'signal', 'pole'),
    ('MAGNET', 'fridge', 'attract', 'metal', 'pole'),
    ('QUICKSAND', 'sink', 'desert', 'trap', 'mud'),
    ('SNORKEL', 'mask', 'breathe', 'reef', 'tube'),
    ('CHANDELIER', 'crystal', 'ceiling', 'sparkle', 'ballroom'),
    ('PRETZEL', 'twist', 'salt', 'dough', 'knot'),
    ('SPIDER WEB', 'silk', 'trap', 'dew', 'strands'),
    ('WINDMILL', 'blades', 'breeze', 'farm', 'grind'),
    ('TYPEWRITER', 'keys', 'ribbon', 'click', 'paper'),
    ('RAINBOW', 'prism', 'arc', 'storm', 'colors'),
    ('GRANDFATHER CLOCK', 'pendulum', 'chime', 'hallway', 'tick'),
    ('FLAMINGO', 'pink', 'pond', 'balance', 'feather'),
    ('BUBBLE WRAP', 'pop', 'cushion', 'packages', 'plastic'),
    ('TUMBLEWEED', 'desert', 'roll', 'dry', 'wind'),
    ('STETHOSCOPE', 'doctor', 'heartbeat', 'tubes', 'checkup'),
    ('PINATA', 'candy', 'blindfold', 'stick', 'burst'),
    ('GARGOYLE', 'stone', 'perch', 'cathedral', 'statue'),
    ('OCTOPUS', 'water', 'ink', 'reef', 'eight'),
    ('ACCORDION', 'squeeze', 'folds', 'polka', 'bellows'),
    ('MOUSETRAP', 'cheese', 'snap', 'bait', 'spring'),
    ('SNOW GLOBE', 'shake', 'flakes', 'dome', 'souvenir'),
    ('SLINGSHOT', 'pebble', 'stretch', 'aim', 'fork'),
    ('BOOMERANG', 'throw', 'curve', 'return', 'wood'),
    ('CACTUS', 'spikes', 'desert', 'bloom', 'prickly'),
    ('YO-YO', 'string', 'trick', 'spin', 'sleeper'),
    ('WHISTLE', 'referee', 'blow', 'tweet', 'coach'),
    ('BEANBAG CHAIR', 'slouch', 'pellets', 'cozy', 'floor'),
    ('COMPASS', 'needle', 'north', 'map', 'direction'),
    ('HORSESHOE', 'luck', 'forge', 'hoof', 'toss'),
    ('JACKHAMMER', 'pavement', 'vibrate', 'drill', 'construction'),
    ('LAWN GNOME', 'garden', 'beard', 'pointy hat', 'statue'),
    ('PILLOW FORT', 'blankets', 'chairs', 'floor', 'flashlight'),
    ('RUBBER DUCK', 'water', 'squeak', 'yellow', 'floatie'),
    ('SEESAW', 'playground', 'balance', 'plank', 'tip'),
    ('TAMBOURINE', 'jingle', 'shake', 'band', 'ribbons'),
    ('UNICYCLE', 'balance', 'circus', 'pedal', 'tire'),
    ('WATERING CAN', 'spout', 'garden', 'sprinkle', 'plants'),
    ('ZIPLINE', 'cable', 'harness', 'forest', 'glide'),
    ('BOWLING BALL', 'gutter', 'pins', 'heavy', 'lane'),
    ('DOORBELL', 'chime', 'porch', 'ring', 'visitor'),
    ('EGG TIMER', 'kitchen', 'sand', 'minutes', 'ding'),
    ('FLASHLIGHT', 'batteries', 'beam', 'dark', 'camping'),
    ('GUMBALL MACHINE', 'coin', 'glass', 'chew', 'twist'),
    ('HULA HOOP', 'spin', 'waist', 'plastic', 'circle'),
    ('ICE CREAM TRUCK', 'jingle', 'cone', 'summer', 'freezer'),
    ('JIGSAW PUZZLE', 'pieces', 'edges', 'table', 'missing'),
    ('KITE', 'string', 'wind', 'tail', 'fly'),
    ('LAVA LAMP', 'hot', 'blob', 'retro', 'bedroom'),
    ('MERRY-GO-ROUND', 'carousel', 'music', 'spin', 'horses'),
    ('NUTCRACKER', 'chomp', 'teeth', 'ballet', 'wooden'),
    ('OVEN MITT', 'kitchen', 'hot', 'grip', 'fabric'),
    ('PARROT', 'squawk', 'feather', 'pirate', 'mimic'),
    ('ROCKING CHAIR', 'porch', 'creak', 'grandma', 'sway'),
    ('TIGHTROPE', 'circus', 'balance', 'wire', 'fall'),
    ('VACUUM CLEANER', 'suck', 'hose', 'carpet', 'dust'),
    ('WAGON', 'wheels', 'pull', 'red', 'handle'),
    ('WEATHER VANE', 'rooftop', 'arrow', 'wind', 'rooster'),
    ('BALTIMORE', 'orange', 'purple', 'dirty', 'beltway'),
    ('SPRING GROVE', 'home', 'pa', 'mill', 'circle'),
    ('MUSHROOM', 'cap', 'mario', 'trip', 'lo mein'),
    ('MINECRAFT', 'block', 'savanna', 'steve', 'notch'),
    ('WINE', 'veritas', 'grape', 'cork', 'glass'),
    ('TRUMP', 'orange', 'blob', 'chicken', 'hair'),
    ('COFFEE', 'grind', 'bean', 'tea', 'drip'),
    ('BOSTON', 'bean', 'will', 'tea', 'patriots'),
    ('BAT', 'bugs', 'bruce', 'night', 'cave'),
    ('TONGUE', 'stick', 'roll', 'raspberry', 'wag'),
    ('MUD', 'dirt', 'brown', 'boots', 'mop'),
    ('DORA', 'backpack', 'map', 'boots', 'swipe'),
    ('ATM', 'card', 'swipe', 'cash', 'pin'),
    ('DROP', 'pin', 'edm', 'kick', 'mic'),
    ('DRUM', 'kick', 'line', 'boy', 'beat'),
    ('TEA', 'leaves', 'china', 'earl', 'pinkie'),
    ('AUTUMN', 'trees', 'football', 'brown', 'crisp'),
    ('CEREAL', 'special', 'cheery', 'milk', 'spoon'),
    ('FORK', 'spoon', 'pointy', 'you', 'silver'),
    ('PUZZLE', 'autism', 'table', 'box', 'flip'),
    ('RAIN', 'mist', 'cloud', 'purple', 'sky'),
    ('PRINCE', 'son', 'guitar', 'harry', 'william'),
    ('WATER TOWER', 'gravity', 'tall', 'blue', 'landmark'),
    ('CHRISTMAS', 'tree', 'spirit', 'lights', 'white'),
    ('HEART', 'red', 'shape', 'pump', 'valentine'),
    ('BIG BROTHER', 'jury', 'house', 'zing', 'have'),
    ('CORN MAZE', 'field', 'lost', 'muddy', 'fall'),
    ('BAND-AID', 'cut', 'knee', 'pad', 'blood'),
    ('GOOGLE', 'mail', 'map', 'verb', 'web'),
    ('STARBUCKS', 'pink', 'brew', 'green', 'latte'),
    ('MAILBOX', 'flag', 'post', 'black', 'envelope'),
    ('GRANDMOTHER', 'knitting', 'gray', 'wrinkled', 'cane'),
    ('BREAD', 'slice', 'whole', 'bag', 'rise'),
    ('MADONNA', 'music', 'material', 'immaculate', 'prayer'),
    ('BALD', 'hat', 'shiny', 'eagle', 'smooth'),
    ('WINNER', 'loser', 'chicken', 'dinner', 'runner up'),

    -- ---- New additions (~180 words) -- everyday objects, animals, food,
    -- places, tech, pop-culture archetypes, sports, school, holidays,
    -- weather, household, vehicles, entertainment, clothing, professions,
    -- and games/toys. All checked against the adjacent-not-direct rule. ----
    ('GIRAFFE', 'tall', 'spots', 'savanna', 'treetop'),
    ('PENGUIN', 'waddle', 'tuxedo', 'ice floe', 'flightless'),
    ('HEDGEHOG', 'curl', 'garden', 'spiky', 'snuffle'),
    ('PLATYPUS', 'pond', 'webbed', 'egg', 'odd'),
    ('RACCOON', 'mask', 'trash can', 'nocturnal', 'bandit'),
    ('SLOTH', 'slow', 'tree', 'hang', 'lazy'),
    ('PEACOCK', 'feathers', 'strut', 'fan', 'vain'),
    ('CHAMELEON', 'blend in', 'camouflage', 'branch', 'disguise'),
    ('WALRUS', 'tusks', 'blubber', 'arctic', 'whiskers'),
    ('ARMADILLO', 'armor', 'roll up', 'shell', 'burrow'),
    ('TOUCAN', 'beak', 'colorful', 'rainforest', 'fruit'),
    ('OTTER', 'playful', 'river', 'slide', 'fur'),
    ('HIPPO', 'river', 'wallow', 'heavy', 'yawn'),
    ('KOALA', 'eucalyptus', 'cuddly', 'tree', 'nap'),
    ('MEERKAT', 'lookout', 'burrow', 'desert', 'stand tall'),
    ('TACO', 'shell', 'fold', 'spicy', 'tuesday'),
    ('WAFFLE', 'grid', 'syrup', 'iron', 'breakfast'),
    ('DONUT', 'glaze', 'sprinkles', 'dozen', 'ring'),
    ('BURRITO', 'wrap', 'foil', 'filling', 'blanket'),
    ('MILKSHAKE', 'straw', 'blend', 'thick', 'diner'),
    ('NACHOS', 'cheese', 'chips', 'plate', 'shared'),
    ('SUSHI', 'roll', 'raw', 'rice', 'chopsticks'),
    ('BAGEL', 'dense', 'chewy', 'cream cheese', 'breakfast'),
    ('PANCAKE', 'stack', 'flip', 'syrup', 'griddle'),
    ('SMOOTHIE', 'blend', 'fruit', 'straw', 'cold'),
    ('HOT DOG', 'bun', 'ballpark', 'mustard', 'grill'),
    ('CUPCAKE', 'frosting', 'wrapper', 'sprinkles', 'tiny'),
    ('MEATBALL', 'sauce', 'round', 'sub', 'italian'),
    ('GUMBO', 'stew', 'spoon', 'cajun', 'pot'),
    ('FONDUE', 'dip', 'melt', 'skewer', 'pot'),
    ('DISNEYLAND', 'castle', 'mouse', 'rides', 'tickets'),
    ('HOLLYWOOD', 'stars', 'sign', 'red carpet', 'fame'),
    ('EIFFEL TOWER', 'iron', 'paris', 'view', 'postcard'),
    ('GRAND CANYON', 'cliff', 'hike', 'layers', 'echo'),
    ('TIMES SQUARE', 'billboard', 'ball drop', 'crowd', 'neon'),
    ('NIAGARA FALLS', 'barrel', 'mist', 'honeymoon', 'roar'),
    ('MOUNT RUSHMORE', 'carved', 'faces', 'granite', 'presidents'),
    ('YELLOWSTONE', 'geyser', 'bison', 'hot spring', 'park'),
    ('GOLDEN GATE BRIDGE', 'fog', 'cables', 'orange', 'bay'),
    ('STONEHENGE', 'circle', 'ancient', 'mystery', 'stones'),
    ('NETFLIX', 'binge', 'streaming', 'remote', 'couch'),
    ('AMAZON', 'package', 'delivery', 'prime', 'warehouse'),
    ('IPHONE', 'screen', 'apps', 'charger', 'camera'),
    ('TIKTOK', 'scroll', 'viral', 'dance', 'clock'),
    ('ZOOM', 'meeting', 'mute', 'webcam', 'screen'),
    ('BLUETOOTH', 'pair', 'wireless', 'headphones', 'signal'),
    ('WIFI', 'password', 'router', 'signal', 'connect'),
    ('ROBOT', 'metal', 'gears', 'wires', 'beep'),
    ('DRONE', 'hover', 'propeller', 'aerial', 'buzz'),
    ('PRINTER', 'paper', 'ink', 'jam', 'scan'),
    ('LAPTOP', 'keyboard', 'screen', 'battery', 'fold'),
    ('PODCAST', 'microphone', 'episode', 'headphones', 'host'),
    ('SUPERHERO', 'rescue', 'powers', 'sidekick', 'disguise'),
    ('ZOMBIE', 'shuffle', 'groan', 'brains', 'undead'),
    ('VAMPIRE', 'fangs', 'night', 'garlic', 'coffin'),
    ('WIZARD', 'wand', 'spell', 'robe', 'potion'),
    ('NINJA', 'stealth', 'shadow', 'silent', 'throw'),
    ('ALIEN', 'spaceship', 'antenna', 'abduction', 'green'),
    ('MERMAID', 'fin', 'scales', 'ocean', 'siren'),
    ('DRAGON', 'scales', 'breathe fire', 'hoard', 'wings'),
    ('UNICORN', 'horn', 'rainbow', 'magic', 'mane'),
    ('COSPLAY', 'costume', 'convention', 'wig', 'character'),
    ('KARAOKE', 'microphone', 'lyrics', 'stage', 'off-key'),
    ('TROPHY', 'shiny', 'shelf', 'engraved', 'win'),
    ('REFEREE', 'stripes', 'flag', 'call', 'sideline'),
    ('SCOREBOARD', 'numbers', 'lights', 'tally', 'stadium'),
    ('TOUCHDOWN', 'endzone', 'spike', 'celebrate', 'six'),
    ('HOME RUN', 'bases', 'fence', 'cheer', 'swing'),
    ('GOALPOST', 'net', 'kick', 'crossbar', 'field'),
    ('DUGOUT', 'bench', 'cleats', 'gum', 'bats'),
    ('LOCKER ROOM', 'towel', 'pep talk', 'cleats', 'showers'),
    ('MARATHON', 'finish line', 'sweat', 'medal', 'pace'),
    ('SKI SLOPE', 'powder', 'lift', 'moguls', 'goggles'),
    ('SURFBOARD', 'wax', 'wave', 'fin', 'paddle'),
    ('TREADMILL', 'belt', 'incline', 'jog', 'gym'),
    ('CHALKBOARD', 'dust', 'eraser', 'scribble', 'classroom'),
    ('REPORT CARD', 'grades', 'envelope', 'signature', 'semester'),
    ('HALL PASS', 'permission', 'clipboard', 'corridor', 'teacher'),
    ('LOCKER', 'combination', 'hallway', 'slam', 'stickers'),
    ('RECESS', 'playground', 'swings', 'tag', 'freedom'),
    ('DETENTION', 'silence', 'clock', 'desk', 'punishment'),
    ('SCIENCE FAIR', 'poster board', 'experiment', 'judges', 'gymnasium'),
    ('FIELD TRIP', 'bus', 'permission slip', 'chaperone', 'museum'),
    ('POP QUIZ', 'surprise', 'pencil', 'dread', 'grade'),
    ('GRADUATION CAP', 'tassel', 'toss', 'gown', 'stage'),
    ('FIREWORKS', 'sparkle', 'boom', 'sky', 'finale'),
    ('JACK-O-LANTERN', 'carve', 'candle', 'grin', 'porch'),
    ('EASTER EGG', 'hunt', 'basket', 'dye', 'hidden'),
    ('VALENTINE', 'card', 'cupid', 'chocolate', 'red'),
    ('THANKSGIVING', 'turkey', 'feast', 'gratitude', 'table'),
    ('NEW YEAR', 'countdown', 'resolution', 'midnight', 'champagne'),
    ('BIRTHDAY CAKE', 'candles', 'frosting', 'wish', 'slice'),
    ('CONFETTI', 'toss', 'colorful', 'celebration', 'mess'),
    ('PARADE', 'float', 'marching band', 'banner', 'crowd'),
    ('AVALANCHE', 'snow', 'slide', 'mountain', 'sudden'),
    ('HURRICANE', 'eye', 'wind', 'evacuate', 'category'),
    ('TORNADO', 'funnel', 'siren', 'twist', 'debris'),
    ('GLACIER', 'ice', 'slow', 'blue', 'crevasse'),
    ('OASIS', 'palm trees', 'mirage', 'desert', 'spring'),
    ('GEYSER', 'erupt', 'steam', 'boiling', 'spout'),
    ('TIDE POOL', 'rocks', 'starfish', 'shallow', 'anemone'),
    ('METEOR SHOWER', 'streak', 'wish', 'night sky', 'blaze'),
    ('NORTHERN LIGHTS', 'aurora', 'green glow', 'arctic', 'dance'),
    ('SANDSTORM', 'gritty', 'visibility', 'desert', 'gust'),
    ('TOASTER', 'pop up', 'crumbs', 'slot', 'browning'),
    ('BLENDER', 'puree', 'pitcher', 'whirl', 'blade'),
    ('RECLINER', 'footrest', 'nap', 'remote', 'cushions'),
    ('DOORMAT', 'welcome', 'wipe feet', 'entrance', 'bristly'),
    ('CLOTHESLINE', 'pins', 'breeze', 'laundry', 'backyard'),
    ('ATTIC', 'dusty', 'boxes', 'cobwebs', 'rafters'),
    ('BASEMENT', 'dark', 'stairs', 'storage', 'damp'),
    ('GARAGE SALE', 'bargain', 'tags', 'driveway', 'haggle'),
    ('CEILING FAN', 'spin', 'blades', 'breeze', 'pull chain'),
    ('LIGHT SWITCH', 'flip', 'wall', 'dark', 'click'),
    ('SMOKE DETECTOR', 'beep', 'battery', 'alarm', 'ceiling'),
    ('THERMOSTAT', 'dial', 'temperature', 'wall', 'adjust'),
    ('JUNK DRAWER', 'clutter', 'batteries', 'mess', 'tangled'),
    ('MEDICINE CABINET', 'mirror', 'bandages', 'pills', 'shelf'),
    ('SCHOOL BUS', 'yellow', 'seats', 'driver', 'route'),
    ('GOLF CART', 'quiet', 'course', 'fairway', 'electric'),
    ('MOTORCYCLE', 'engine', 'helmet', 'roar', 'handlebars'),
    ('HOT AIR BALLOON', 'basket', 'float', 'burner', 'sky'),
    ('CANOE', 'paddle', 'river', 'tip over', 'calm water'),
    ('SKI LIFT', 'chair', 'cable', 'mountain', 'dangle'),
    ('MONSTER TRUCK', 'crush', 'tires', 'mud', 'arena'),
    ('TOW TRUCK', 'hook', 'breakdown', 'flatbed', 'rescue'),
    ('MOPED', 'scooter', 'small engine', 'helmet', 'zip'),
    ('DISCO BALL', 'sparkle', 'spin', 'mirror', 'dance floor'),
    ('BOOMBOX', 'shoulder', 'cassette', 'blast', 'batteries'),
    ('VINYL RECORD', 'needle', 'groove', 'spin', 'crackle'),
    ('MOSH PIT', 'shove', 'concert', 'chaos', 'crowd surf'),
    ('ENCORE', 'applause', 'one more', 'curtain', 'cheer'),
    ('SPOTLIGHT', 'beam', 'stage', 'bright', 'focus'),
    ('BACKSTAGE', 'crew', 'dressing room', 'cue', 'hidden'),
    ('JUKEBOX', 'coin', 'select', 'diner', 'flashing'),
    ('SAFETY PIN', 'clasp', 'diaper', 'sharp', 'fasten'),
    ('DUCT TAPE', 'sticky', 'silver', 'roll', 'fix-all'),
    ('RUBBER BAND', 'stretch', 'snap', 'ponytail', 'bundle'),
    ('PAPER AIRPLANE', 'fold', 'glide', 'classroom', 'crease'),
    ('SNOW CONE', 'shaved ice', 'syrup', 'paper cup', 'summer'),
    ('BUBBLE GUM', 'chew', 'blow', 'pink', 'pop'),
    ('FIDGET SPINNER', 'twirl', 'fingers', 'classroom', 'distraction'),
    ('WATER BALLOON', 'splash', 'toss', 'summer', 'soaked'),
    ('POGO STICK', 'bounce', 'spring', 'hop', 'sidewalk'),
    ('KAZOO', 'hum', 'buzz', 'plastic', 'silly'),
    ('KALEIDOSCOPE', 'twist', 'colors', 'mirror', 'pattern'),
    ('LOCKET', 'chain', 'photo', 'open', 'heart'),
    ('MAGNIFYING GLASS', 'detective', 'lens', 'enlarge', 'ants'),
    ('MONOCLE', 'eye', 'fancy', 'single lens', 'aristocrat'),
    ('PARASOL', 'shade', 'lace', 'twirl', 'garden'),
    ('TOP HAT', 'magician', 'tall', 'formal', 'rabbit'),
    ('BOW TIE', 'formal', 'neck', 'dapper', 'waiter'),
    ('FANNY PACK', 'waist', 'zip', 'retro', 'tourist'),
    ('RAINCOAT', 'hood', 'puddle', 'yellow', 'drizzle'),
    ('FLIP FLOPS', 'sandy', 'slap', 'summer', 'beach'),
    ('MITTENS', 'cold', 'string', 'snowball', 'cozy'),
    ('EARRINGS', 'dangle', 'pierce', 'sparkle', 'pair'),
    ('SUNGLASSES', 'shade', 'cool', 'lens', 'glare'),
    ('BANDANA', 'knot', 'cowboy', 'wrap', 'headscarf'),
    ('CAPE', 'flowing', 'shoulder', 'dramatic', 'wind'),
    ('LIFEGUARD', 'tower', 'tan', 'rescue', 'float'),
    ('ASTRONAUT', 'suit', 'gravity', 'moonwalk', 'helmet'),
    ('CHEF', 'apron', 'whisk', 'kitchen', 'taste'),
    ('DENTIST', 'drill', 'floss', 'chair', 'checkup'),
    ('POSTAL WORKER', 'route', 'stamp', 'uniform', 'deliver'),
    ('LIBRARIAN', 'shush', 'shelves', 'due date', 'glasses'),
    ('ELECTRICIAN', 'wires', 'sparks', 'outlet', 'ladder'),
    ('PLUMBER', 'wrench', 'pipes', 'leak', 'overalls'),
    ('VETERINARIAN', 'paws', 'checkup', 'clinic', 'gentle'),
    ('ARCHITECT', 'blueprint', 'model', 'design', 'skyline'),
    ('CHESSBOARD', 'squares', 'strategy', 'king', 'checkmate'),
    ('DOMINOES', 'tile', 'chain reaction', 'dots', 'topple'),
    ('RUBIKS CUBE', 'twist', 'colors', 'solve', 'frustrating'),
    ('MARBLES', 'glass', 'roll', 'pouch', 'shooter'),
    ('JUMP ROPE', 'skip', 'playground', 'double dutch', 'swing'),
    ('BOARD GAME', 'dice', 'rules', 'family night', 'pieces'),
    ('ACTION FIGURE', 'pose', 'plastic', 'collect', 'hero'),
    ('STUFFED ANIMAL', 'cuddly', 'button eyes', 'bedtime', 'soft'),
    ('WATER GUN', 'squirt', 'summer', 'refill', 'ambush'),
    ('PLAYING CARDS', 'shuffle', 'deck', 'deal', 'poker'),
    ('KEYCHAIN', 'dangle', 'jingle', 'pocket', 'souvenir');

-- ---- Wave 2: ~201 more new words to close the gap to 500 total. Same
-- rules, fresh categories (body/personal, emotions, space, ocean, insects,
-- birds, prehistoric, farm, circus, instruments, weather, school, office,
-- medical, arts/crafts, retro tech, everyday city objects, sports gear,
-- gardening, winter). ----
INSERT INTO empossdurr_words (word, clue_1, clue_2, clue_3, clue_4) VALUES
    ('ELBOW', 'bend', 'funny bone', 'joint', 'nudge'),
    ('KNEE', 'cap', 'bend', 'scrape', 'wobbly'),
    ('EYEBROW', 'raise', 'arch', 'pencil', 'expression'),
    ('FRECKLE', 'sun', 'dot', 'cheek', 'scatter'),
    ('DIMPLE', 'smile', 'cheek', 'cute', 'chin'),
    ('COWLICK', 'hair', 'stubborn', 'part', 'comb'),
    ('BELLY BUTTON', 'lint', 'innie', 'outie', 'tummy'),
    ('KNUCKLE', 'crack', 'fist', 'ring', 'sandwich'),
    ('EARLOBE', 'pierce', 'dangle', 'tug', 'soft'),
    ('NOSTRIL', 'flare', 'sniff', 'breathe', 'tickle'),
    ('YAWN', 'tired', 'contagious', 'stretch', 'mouth'),
    ('HICCUP', 'startle', 'breath', 'spasm', 'annoying'),
    ('JEALOUSY', 'green', 'envy', 'rival', 'sting'),
    ('NOSTALGIA', 'memory', 'old song', 'bittersweet', 'throwback'),
    ('STAGE FRIGHT', 'nerves', 'spotlight', 'freeze', 'audience'),
    ('DEJA VU', 'familiar', 'glitch', 'repeat', 'strange'),
    ('WRITERS BLOCK', 'blank page', 'stuck', 'stare', 'frustration'),
    ('BUTTERFLIES', 'nervous', 'stomach', 'flutter', 'first date'),
    ('GOOSEBUMPS', 'chill', 'skin', 'spooky', 'arm hair'),
    ('BRAIN FREEZE', 'cold', 'headache', 'ice cream', 'sudden'),
    ('SIDE-EYE', 'glance', 'suspicious', 'judge', 'glare'),
    ('FACEPALM', 'embarrassed', 'forehead', 'groan', 'oops'),
    ('SATURN', 'rings', 'planet', 'gas', 'orbit'),
    ('BLACK HOLE', 'gravity', 'suck in', 'dark', 'warp'),
    ('COMET', 'tail', 'ice', 'streak', 'orbit'),
    ('CONSTELLATION', 'stars', 'connect dots', 'pattern', 'myth'),
    ('ECLIPSE', 'shadow', 'glasses', 'block', 'rare'),
    ('GALAXY', 'spiral', 'stars', 'vast', 'milky'),
    ('ASTEROID', 'rock', 'belt', 'crash', 'space'),
    ('ROCKET', 'launch', 'fuel', 'blast off', 'countdown'),
    ('SPACE STATION', 'orbit', 'floating', 'module', 'astronaut'),
    ('MOON LANDING', 'flag', 'footprint', 'giant leap', '1969'),
    ('JELLYFISH', 'sting', 'float', 'translucent', 'tentacles'),
    ('STARFISH', 'arms', 'regrow', 'tide pool', 'sandy'),
    ('SEAHORSE', 'tiny', 'curled tail', 'coral', 'dad carries eggs'),
    ('SHARK FIN', 'dorsal', 'cut water', 'movie music', 'gray'),
    ('CORAL REEF', 'colorful', 'fragile', 'fish', 'bleaching'),
    ('TIDAL WAVE', 'massive', 'shore', 'warning', 'surge'),
    ('SHIPWRECK', 'sunken', 'treasure', 'rust', 'divers'),
    ('PEARL', 'oyster', 'necklace', 'shine', 'grit'),
    ('SEAWEED', 'slimy', 'green', 'wash up', 'tangled'),
    ('SAND DOLLAR', 'flat', 'beach', 'fragile', 'disc'),
    ('HARPOON', 'whaling', 'spear', 'rope', 'old ship'),
    ('LADYBUG', 'spots', 'luck', 'red', 'garden'),
    ('GRASSHOPPER', 'jump', 'green', 'chirp', 'field'),
    ('CATERPILLAR', 'crawl', 'leaves', 'fuzzy', 'transform'),
    ('CRICKET', 'chirp', 'night', 'jump', 'lucky'),
    ('MANTIS', 'pray', 'green', 'ambush', 'still'),
    ('ANT HILL', 'colony', 'dirt mound', 'picnic', 'tiny'),
    ('MOSQUITO', 'bite', 'buzz', 'itchy', 'repellent'),
    ('TERMITE', 'wood', 'colony', 'damage', 'hidden'),
    ('DUNG BEETLE', 'roll', 'gross', 'strong', 'recycle'),
    ('OWL', 'nocturnal', 'hoot', 'wise', 'swivel'),
    ('EAGLE', 'soar', 'talons', 'patriotic', 'nest'),
    ('WOODPECKER', 'tap', 'drum', 'tree', 'red crest'),
    ('HUMMINGBIRD', 'hover', 'tiny', 'nectar', 'fast wings'),
    ('PELICAN', 'pouch', 'dive', 'beach', 'large bill'),
    ('ROBIN', 'red breast', 'spring', 'worm', 'nest'),
    ('SEAGULL', 'steal fries', 'squawk', 'beach', 'white'),
    ('CROW', 'caw', 'black', 'clever', 'murder'),
    ('CARDINAL', 'red', 'winter', 'feeder', 'whistle'),
    ('OSTRICH', 'bury head', 'tall', 'fast runner', 'egg'),
    ('FOSSIL', 'dig', 'ancient', 'rock', 'imprint'),
    ('AMBER', 'trapped', 'golden', 'resin', 'ancient bug'),
    ('CAVEMAN', 'club', 'fire', 'drawings', 'grunt'),
    ('MAMMOTH', 'tusks', 'frozen', 'hairy', 'extinct'),
    ('DINOSAUR EGG', 'nest', 'hatch', 'giant', 'fossil'),
    ('T-REX', 'tiny arms', 'roar', 'jurassic', 'predator'),
    ('SABER-TOOTH', 'fangs', 'ice age', 'cat', 'prehistoric'),
    ('BARN', 'hay', 'red', 'animals', 'silo'),
    ('SILO', 'grain', 'tall', 'farm', 'tower'),
    ('TRACTOR', 'plow', 'mud', 'farmer', 'wheels'),
    ('HAYRIDE', 'wagon', 'tractor', 'autumn', 'bumpy'),
    ('CHICKEN COOP', 'eggs', 'cluck', 'fence', 'feathers'),
    ('PITCHFORK', 'hay', 'farmer', 'prongs', 'barn'),
    ('MILKING STOOL', 'three-legged', 'barn', 'low', 'cow'),
    ('CORNFIELD', 'rows', 'tall', 'rustle', 'harvest'),
    ('ROOSTER', 'crow', 'sunrise', 'comb', 'farm'),
    ('DUCK POND', 'quack', 'ripple', 'feed', 'park'),
    ('RINGMASTER', 'top hat', 'whip', 'announce', 'spotlight'),
    ('TRAPEZE', 'swing', 'catch', 'high wire', 'net'),
    ('JUGGLER', 'balls', 'toss', 'clown', 'coordination'),
    ('CLOWN', 'red nose', 'big shoes', 'honk', 'makeup'),
    ('CARNIVAL GAME', 'rigged', 'prize', 'ring toss', 'stuffed animal'),
    ('COTTON CANDY', 'fluffy', 'spin', 'pink', 'melt'),
    ('FUNHOUSE MIRROR', 'distort', 'warped', 'laugh', 'reflection'),
    ('STRONGMAN', 'mallet', 'bell', 'muscle', 'tent'),
    ('DRUMSTICK', 'tap', 'rhythm', 'wood', 'beat'),
    ('TRUMPET', 'brass', 'valves', 'blare', 'marching band'),
    ('VIOLIN', 'bow', 'strings', 'orchestra', 'screech'),
    ('HARMONICA', 'blues', 'breathe', 'pocket', 'train sound'),
    ('BAGPIPES', 'scottish', 'wail', 'kilt', 'squeeze'),
    ('TRIANGLE', 'ting', 'metal', 'orchestra', 'simple'),
    ('CYMBALS', 'crash', 'clang', 'drummer', 'shiny'),
    ('HARP', 'strings', 'angel', 'pluck', 'elegant'),
    ('DIDGERIDOO', 'hum', 'long', 'aboriginal', 'breath'),
    ('MARACAS', 'shake', 'rattle', 'latin', 'pair'),
    ('FOG', 'mist', 'low visibility', 'ghostly', 'morning'),
    ('FROST', 'cold', 'window', 'crunch', 'silver'),
    ('HAIL', 'ice', 'dent', 'sudden', 'pellets'),
    ('DEW', 'morning', 'grass', 'droplets', 'glisten'),
    ('HEAT WAVE', 'sweat', 'record', 'shimmer', 'fan'),
    ('BLIZZARD', 'whiteout', 'snowplow', 'howling', 'freezing'),
    ('DROUGHT', 'dry', 'cracked ground', 'water shortage', 'dust'),
    ('MONSOON', 'heavy rain', 'season', 'flood', 'humid'),
    ('CAFETERIA', 'tray', 'lunch line', 'noisy', 'mystery meat'),
    ('YEARBOOK', 'signatures', 'photos', 'memories', 'cover'),
    ('SPELLING BEE', 'microphone', 'nerves', 'buzzer', 'champion'),
    ('SUBSTITUTE TEACHER', 'unfamiliar', 'chaos', 'seating chart', 'note'),
    ('HOMEROOM', 'attendance', 'announcements', 'first bell', 'seat'),
    ('PRINCIPALS OFFICE', 'trouble', 'chair', 'intercom', 'nervous'),
    ('SCHOOL PLAY', 'costume', 'lines', 'curtain', 'nerves'),
    ('BUS STOP', 'wait', 'backpack', 'early morning', 'corner'),
    ('CUBICLE', 'gray', 'walls', 'coffee mug', 'monotony'),
    ('STAPLER', 'click', 'red', 'jam', 'desk'),
    ('PAPER CLIP', 'bend', 'silver', 'holds', 'wire'),
    ('WHITEBOARD', 'marker', 'erase', 'meeting', 'squeak'),
    ('CONFERENCE CALL', 'mute', 'awkward', 'silence', 'dial in'),
    ('WATER COOLER', 'gossip', 'gurgle', 'jug', 'break room'),
    ('NAME TAG', 'convention', 'sticker', 'badge', 'lanyard'),
    ('BREAK ROOM', 'microwave', 'fridge', 'snacks', 'small talk'),
    ('THERMOMETER', 'temperature', 'mercury', 'fever', 'under tongue'),
    ('CRUTCHES', 'hobble', 'cast', 'armpit', 'injury'),
    ('WHEELCHAIR', 'wheels', 'ramp', 'push', 'accessible'),
    ('X-RAY', 'bones', 'radiation', 'vest', 'scan'),
    ('WAITING ROOM', 'magazines', 'nervous', 'clipboard', 'called'),
    ('CAST', 'itchy', 'signatures', 'broken', 'plaster'),
    ('EYE CHART', 'letters', 'blurry', 'doctor', 'memorize'),
    ('PAINTBRUSH', 'bristles', 'canvas', 'dip', 'strokes'),
    ('EASEL', 'canvas', 'stand', 'studio', 'tilt'),
    ('GLUE STICK', 'glitter', 'purple', 'twist up', 'craft'),
    ('SCISSORS', 'cut', 'blades', 'paper', 'sharp'),
    ('CRAYON', 'wax', 'box of 64', 'color outside lines', 'melt'),
    ('CLAY', 'mold', 'squish', 'kiln', 'pottery wheel'),
    ('GLITTER', 'sparkle', 'mess', 'everywhere', 'craft'),
    ('SKETCHBOOK', 'pencil', 'blank pages', 'doodle', 'artist'),
    ('ORIGAMI', 'fold', 'paper', 'crane', 'precise'),
    ('MOSAIC', 'tiles', 'pattern', 'fragments', 'glass'),
    ('ROTARY PHONE', 'dial', 'cord', 'click', 'heavy'),
    ('CASSETTE TAPE', 'rewind', 'walkman', 'ribbon', 'click'),
    ('FLOPPY DISK', 'save icon', 'outdated', 'click', 'storage'),
    ('POLAROID', 'shake', 'instant', 'square', 'develop'),
    ('ARCADE MACHINE', 'quarter', 'joystick', 'high score', 'blinking'),
    ('PAGER', 'beep', 'clip', '90s', 'buzz'),
    ('VHS TAPE', 'rewind', 'rental', 'static', 'tracking'),
    ('DIAL-UP MODEM', 'screech', 'connect', 'slow', '90s'),
    ('WALLET', 'cash', 'cards', 'fold', 'pocket'),
    ('PURSE', 'strap', 'clutter', 'zipper', 'shoulder'),
    ('SUITCASE', 'pack', 'wheels', 'airport', 'handle'),
    ('PASSPORT', 'stamp', 'photo', 'travel', 'booklet'),
    ('BOARDING PASS', 'gate', 'seat number', 'scan', 'airport'),
    ('ELEVATOR', 'buttons', 'floors', 'music', 'ding'),
    ('REVOLVING DOOR', 'spin', 'lobby', 'glass', 'continuous'),
    ('FIRE ESCAPE', 'metal', 'ladder', 'alley', 'emergency'),
    ('STREETLAMP', 'glow', 'night', 'moths', 'pole'),
    ('PARKING METER', 'coins', 'ticket', 'expired', 'curb'),
    ('CROSSWALK', 'stripes', 'signal', 'pedestrian', 'button'),
    ('MANHOLE COVER', 'round', 'steam', 'street', 'heavy'),
    ('FIRE HYDRANT', 'red', 'dog', 'spray', 'curb'),
    ('NEWSPAPER STAND', 'headline', 'coins', 'corner', 'folded'),
    ('PARK BENCH', 'sit', 'pigeons', 'plaque', 'shade'),
    ('GAZEBO', 'park', 'wedding', 'roof', 'octagon'),
    ('SUNDIAL', 'shadow', 'ancient', 'garden', 'time'),
    ('HELMET', 'padding', 'chin strap', 'protect', 'sport'),
    ('SHIN GUARD', 'soccer', 'padding', 'protect', 'kick'),
    ('MOUTHGUARD', 'teeth', 'football', 'protect', 'custom'),
    ('JERSEY', 'number', 'team', 'sweat', 'locker room'),
    ('CLEATS', 'spikes', 'grass', 'soccer', 'traction'),
    ('SCOREKEEPER', 'pencil', 'tally', 'sideline', 'careful'),
    ('BASKETBALL HOOP', 'net', 'rim', 'swish', 'backboard'),
    ('FINISH LINE', 'tape', 'cheer', 'race', 'checkered flag'),
    ('STARTING BLOCKS', 'sprinter', 'crouch', 'race', 'tension'),
    ('VICTORY LAP', 'cheer', 'flag', 'slow down', 'celebrate'),
    ('GREENHOUSE', 'glass', 'plants', 'humid', 'grow'),
    ('FLOWER POT', 'dirt', 'drainage', 'terracotta', 'windowsill'),
    ('RAKE', 'leaves', 'prongs', 'autumn', 'tines'),
    ('SHOVEL', 'dig', 'dirt', 'blade', 'garden'),
    ('SEED PACKET', 'plant', 'envelope', 'instructions', 'sprout'),
    ('COMPOST BIN', 'rot', 'scraps', 'worms', 'recycle'),
    ('BIRDBATH', 'water', 'garden', 'splash', 'statue'),
    ('SLED', 'hill', 'snow', 'slide', 'wooden'),
    ('ICE SKATE', 'blade', 'rink', 'glide', 'cold'),
    ('SNOWBALL', 'pack', 'throw', 'cold', 'fight'),
    ('SNOWPLOW', 'clear', 'street', 'orange', 'heavy'),
    ('ICICLE', 'drip', 'sharp', 'hang', 'melt'),
    ('SNOW SHOVEL', 'driveway', 'heavy', 'clear', 'back-breaking'),
    ('HOT COCOA', 'mug', 'marshmallow', 'warm', 'winter'),
    ('WOOL SCARF', 'wrap', 'itchy', 'neck', 'knit');
