-- ============================================================================
-- Pop Culture content expansion: ~1000 new questions spanning the last 100
-- years, across 5 factions (MOVIES / MUSIC / TV / LITERATURE / ART).
--
-- Purely additive: does NOT touch, modify, or delete any existing row, and
-- does NOT drop or truncate anything (unlike seed.js). Safe to run against a
-- live database with existing content, including production.
--
-- question_number is computed dynamically (current MAX + row position), so
-- this is safe to paste into Neon's SQL editor regardless of exactly what's
-- already in the table.
--
-- Design (per the planning discussion): the well isn't evenly deep across
-- 100 years -- pop culture as mass, broadly-shared media only gets dense
-- from the 1960s/70s onward. So content density ramps up hard toward the
-- present; 1920s-1950s is a deliberately curated "legends" tier of only the
-- most enduring, still-recognized touchstones (Chaplin, Casablanca, early
-- Disney, big-band swing), not matched in volume to later decades. Points
-- (100/200/300) reflect a mix of "how iconic within its era" and "how far
-- back / how obscure" -- both count toward difficulty.
--
-- subcategory is used meaningfully here (unlike Primary School, which ended
-- up almost entirely THING): PERSON for actors/directors/musicians/authors/
-- artists, THING for titles/characters/songs/albums/artworks. Distractors are
-- sourced per (category, subcategory, faction), so PERSON and THING within
-- the same faction are separate pools -- e.g. an actor question never pulls
-- a movie title as a wrong answer, keeping every multiple-choice row
-- internally coherent.
-- ============================================================================

INSERT INTO questions (question_number, game_mode, category, subcategory, faction, question_text, visual_asset, correct_answer, points)
SELECT (SELECT COALESCE(MAX(question_number), 0) FROM questions) + ROW_NUMBER() OVER (), 'TRIVIA', 'POP_CULTURE', v.subcategory, v.faction, v.question_text, NULL, v.correct_answer, v.points
FROM (VALUES

-- ============================================================================
-- FACTION: MOVIES / PERSON -- actors and directors
-- ============================================================================

-- Golden Age & classic Hollywood (curated legends tier)
('PERSON', 'MOVIES', 'Which actor played the Tramp character in classic silent films?', 'Charlie Chaplin', 200),
('PERSON', 'MOVIES', 'Which actress starred as Dorothy in "The Wizard of Oz"?', 'Judy Garland', 100),
('PERSON', 'MOVIES', 'Which actor is famous for playing Rick Blaine in "Casablanca"?', 'Humphrey Bogart', 200),
('PERSON', 'MOVIES', 'Which actress starred opposite Humphrey Bogart in "Casablanca"?', 'Ingrid Bergman', 200),
('PERSON', 'MOVIES', 'Which director is famous for the 1933 film "King Kong"?', 'Merian C. Cooper', 300),
('PERSON', 'MOVIES', 'Which actress became a global icon in "Some Like It Hot" and "Gentlemen Prefer Blondes"?', 'Marilyn Monroe', 100),
('PERSON', 'MOVIES', 'Which actor was famous for swashbuckling roles like Robin Hood in the 1930s?', 'Errol Flynn', 300),
('PERSON', 'MOVIES', 'Which director made "Rear Window," "Psycho," and "Vertigo"?', 'Alfred Hitchcock', 200),
('PERSON', 'MOVIES', 'Which actor played the lead cowboy hero in many classic Westerns of the 1940s-60s?', 'John Wayne', 200),
('PERSON', 'MOVIES', 'Which actress starred in "Roman Holiday" and "Breakfast at Tiffany''s"?', 'Audrey Hepburn', 100),

-- 1960s-1970s
('PERSON', 'MOVIES', 'Which actor played James Bond first, starting in 1962?', 'Sean Connery', 200),
('PERSON', 'MOVIES', 'Which director made "2001: A Space Odyssey" and "The Shining"?', 'Stanley Kubrick', 200),
('PERSON', 'MOVIES', 'Which actor starred as Michael Corleone in "The Godfather"?', 'Al Pacino', 100),
('PERSON', 'MOVIES', 'Which actor played Don Vito Corleone in "The Godfather"?', 'Marlon Brando', 200),
('PERSON', 'MOVIES', 'Which director made "Jaws," "E.T.," and "Jurassic Park"?', 'Steven Spielberg', 100),
('PERSON', 'MOVIES', 'Which director created the original "Star Wars" trilogy?', 'George Lucas', 100),
('PERSON', 'MOVIES', 'Which actor played Rocky Balboa?', 'Sylvester Stallone', 100),
('PERSON', 'MOVIES', 'Which actor voiced Darth Vader in the original "Star Wars" trilogy?', 'James Earl Jones', 200),
('PERSON', 'MOVIES', 'Which actress starred in "Annie Hall" and won an Oscar for it?', 'Diane Keaton', 300),
('PERSON', 'MOVIES', 'Which director made "Taxi Driver" and "Raging Bull"?', 'Martin Scorsese', 200),

-- 1980s
('PERSON', 'MOVIES', 'Which actor played Indiana Jones?', 'Harrison Ford', 100),
('PERSON', 'MOVIES', 'Which actor starred as the Terminator?', 'Arnold Schwarzenegger', 100),
('PERSON', 'MOVIES', 'Which actor played Marty McFly in "Back to the Future"?', 'Michael J. Fox', 100),
('PERSON', 'MOVIES', 'Which actress starred as Sarah Connor in "The Terminator"?', 'Linda Hamilton', 200),
('PERSON', 'MOVIES', 'Which director made "E.T." and "Poltergeist" in the same era?', 'Steven Spielberg', 200),
('PERSON', 'MOVIES', 'Which actor played Ferris Bueller?', 'Matthew Broderick', 200),
('PERSON', 'MOVIES', 'Which director is known for "The Breakfast Club" and "Ferris Bueller''s Day Off"?', 'John Hughes', 300),
('PERSON', 'MOVIES', 'Which actor starred as John McClane in "Die Hard"?', 'Bruce Willis', 100),
('PERSON', 'MOVIES', 'Which actress played Princess Leia in the original "Star Wars" trilogy?', 'Carrie Fisher', 100),
('PERSON', 'MOVIES', 'Which actor played the lead role in "Top Gun" (1986)?', 'Tom Cruise', 100),

-- 1990s
('PERSON', 'MOVIES', 'Which actor played Jack Dawson in "Titanic"?', 'Leonardo DiCaprio', 100),
('PERSON', 'MOVIES', 'Which actress played Rose in "Titanic"?', 'Kate Winslet', 100),
('PERSON', 'MOVIES', 'Which director made "Titanic" and "Avatar"?', 'James Cameron', 100),
('PERSON', 'MOVIES', 'Which actor starred as Forrest Gump?', 'Tom Hanks', 100),
('PERSON', 'MOVIES', 'Which actor played Neo in "The Matrix"?', 'Keanu Reeves', 100),
('PERSON', 'MOVIES', 'Which director made "Pulp Fiction" and "Kill Bill"?', 'Quentin Tarantino', 200),
('PERSON', 'MOVIES', 'Which actress starred in "Pretty Woman" alongside Richard Gere?', 'Julia Roberts', 100),
('PERSON', 'MOVIES', 'Which actor played Hannibal Lecter in "The Silence of the Lambs"?', 'Anthony Hopkins', 200),
('PERSON', 'MOVIES', 'Which actress won an Oscar for "Silence of the Lambs" as Clarice Starling?', 'Jodie Foster', 200),
('PERSON', 'MOVIES', 'Which actor voiced Woody in the "Toy Story" films?', 'Tom Hanks', 200),
('PERSON', 'MOVIES', 'Which actor voiced Buzz Lightyear in the "Toy Story" films?', 'Tim Allen', 200),
('PERSON', 'MOVIES', 'Which director made "Jurassic Park" and "Schindler''s List" in the same year, 1993?', 'Steven Spielberg', 300),

-- 2000s
('PERSON', 'MOVIES', 'Which actor played Harry Potter in the film series?', 'Daniel Radcliffe', 100),
('PERSON', 'MOVIES', 'Which actress played Hermione Granger in the "Harry Potter" films?', 'Emma Watson', 100),
('PERSON', 'MOVIES', 'Which actor played Frodo Baggins in "The Lord of the Rings" trilogy?', 'Elijah Wood', 200),
('PERSON', 'MOVIES', 'Which director made "The Lord of the Rings" trilogy?', 'Peter Jackson', 200),
('PERSON', 'MOVIES', 'Which actor played Jack Sparrow in the "Pirates of the Caribbean" films?', 'Johnny Depp', 100),
('PERSON', 'MOVIES', 'Which director made "The Dark Knight" trilogy?', 'Christopher Nolan', 200),
('PERSON', 'MOVIES', 'Which actor played the Joker in "The Dark Knight" (2008)?', 'Heath Ledger', 200),
('PERSON', 'MOVIES', 'Which actress starred as Elle Woods in "Legally Blonde"?', 'Reese Witherspoon', 200),
('PERSON', 'MOVIES', 'Which actor played Tony Stark / Iron Man in the Marvel Cinematic Universe?', 'Robert Downey Jr.', 100),
('PERSON', 'MOVIES', 'Which director made "Finding Nemo" and "WALL-E"?', 'Andrew Stanton', 300),

-- 2010s-2020s
('PERSON', 'MOVIES', 'Which actor played Captain America in the Marvel Cinematic Universe?', 'Chris Evans', 100),
('PERSON', 'MOVIES', 'Which actor played Thor in the Marvel Cinematic Universe?', 'Chris Hemsworth', 100),
('PERSON', 'MOVIES', 'Which actress played Katniss Everdeen in "The Hunger Games"?', 'Jennifer Lawrence', 100),
('PERSON', 'MOVIES', 'Which director made "La La Land" and "Whiplash"?', 'Damien Chazelle', 300),
('PERSON', 'MOVIES', 'Which actress played Elsa in Disney''s "Frozen" (voice role)?', 'Idina Menzel', 200),
('PERSON', 'MOVIES', 'Which director made "Parasite," the first non-English film to win Best Picture?', 'Bong Joon-ho', 300),
('PERSON', 'MOVIES', 'Which actor played Spider-Man starting in 2017''s "Spider-Man: Homecoming"?', 'Tom Holland', 100),
('PERSON', 'MOVIES', 'Which director made "Oppenheimer" and "Inception"?', 'Christopher Nolan', 100),
('PERSON', 'MOVIES', 'Which actress played the title role in "Barbie" (2023)?', 'Margot Robbie', 100),
('PERSON', 'MOVIES', 'Which director made "Barbie" (2023)?', 'Greta Gerwig', 200),

-- ============================================================================
-- FACTION: MOVIES / THING -- titles, characters, franchises, quotes
-- ============================================================================

('THING', 'MOVIES', 'What is the name of the sled in "Citizen Kane" that becomes the film''s central mystery?', 'Rosebud', 300),
('THING', 'MOVIES', 'What 1939 film features the song "Over the Rainbow"?', 'The Wizard of Oz', 100),
('THING', 'MOVIES', 'What is the name of Dorothy''s dog in "The Wizard of Oz"?', 'Toto', 100),
('THING', 'MOVIES', 'What 1942 film is set in a nightclub in wartime Morocco?', 'Casablanca', 200),
('THING', 'MOVIES', 'What 1933 film features a giant ape climbing the Empire State Building?', 'King Kong', 100),
('THING', 'MOVIES', 'What was the first full-length animated Disney feature film, released in 1937?', 'Snow White and the Seven Dwarfs', 200),
('THING', 'MOVIES', 'What 1959 Alfred Hitchcock film features a famous crop-duster chase scene?', 'North by Northwest', 300),
('THING', 'MOVIES', 'What 1960 Hitchcock film features a famous shower scene?', 'Psycho', 200),
('THING', 'MOVIES', 'What 1968 film features the artificial intelligence HAL 9000?', '2001: A Space Odyssey', 200),
('THING', 'MOVIES', 'What crime family is at the center of "The Godfather"?', 'The Corleone family', 200),
('THING', 'MOVIES', 'What 1975 film about a great white shark launched the summer blockbuster era?', 'Jaws', 100),
('THING', 'MOVIES', 'What is the name of the droid who beeps and whistles in "Star Wars"?', 'R2-D2', 100),
('THING', 'MOVIES', 'What is the name of the golden protocol droid in "Star Wars"?', 'C-3PO', 100),
('THING', 'MOVIES', 'What is the name of Luke Skywalker''s home planet in "Star Wars"?', 'Tatooine', 200),
('THING', 'MOVIES', 'What is the name of the ship captained by Han Solo?', 'Millennium Falcon', 100),
('THING', 'MOVIES', 'What organization does Indiana Jones search for the Ark of the Covenant against?', 'The Nazis', 200),
('THING', 'MOVIES', 'What 1982 film features a friendly alien who wants to "phone home"?', 'E.T. the Extra-Terrestrial', 100),
('THING', 'MOVIES', 'What is the name of the time-traveling car in "Back to the Future"?', 'DeLorean', 100),
('THING', 'MOVIES', 'What speed must the DeLorean reach to time travel in "Back to the Future"?', '88 miles per hour', 200),
('THING', 'MOVIES', 'What 1984 film features a boy who befriends a mischievous creature named Gizmo?', 'Gremlins', 200),
('THING', 'MOVIES', 'What sport does the "Karate Kid" actually train in, contrary to the title?', 'Karate', 100),
('THING', 'MOVIES', 'What ocean liner sinks in the 1997 film "Titanic"?', 'RMS Titanic', 100),
('THING', 'MOVIES', 'What 1993 film features dinosaurs cloned from ancient DNA on an island theme park?', 'Jurassic Park', 100),
('THING', 'MOVIES', 'What simulated world do Neo and the other characters discover in "The Matrix"?', 'The Matrix', 200),
('THING', 'MOVIES', 'What color pill does Neo take to see the truth in "The Matrix"?', 'Red pill', 200),
('THING', 'MOVIES', 'What is the name of the shrimp company Forrest Gump''s friend Bubba dreams of in "Forrest Gump"?', 'Bubba Gump', 200),
('THING', 'MOVIES', 'What 1994 film follows two hitmen, a boxer, and a gangster''s wife in Los Angeles?', 'Pulp Fiction', 200),
('THING', 'MOVIES', 'What toy cowboy is the main character of "Toy Story"?', 'Woody', 100),
('THING', 'MOVIES', 'What is the name of the ogre in the "Shrek" film series?', 'Shrek', 100),
('THING', 'MOVIES', 'What magical school does Harry Potter attend?', 'Hogwarts', 100),
('THING', 'MOVIES', 'What is the name of Harry Potter''s owl?', 'Hedwig', 200),
('THING', 'MOVIES', 'What is the name of the evil wizard Harry Potter must defeat?', 'Voldemort', 100),
('THING', 'MOVIES', 'What magic ring is the central object in "The Lord of the Rings"?', 'The One Ring', 100),
('THING', 'MOVIES', 'What is the name of the hobbit who carries the Ring in "The Lord of the Rings"?', 'Frodo', 100),
('THING', 'MOVIES', 'What fictional Caribbean pirate captain is played by Johnny Depp?', 'Jack Sparrow', 100),
('THING', 'MOVIES', 'What secretive fight organization is at the center of "Fight Club"?', 'Fight Club', 200),
('THING', 'MOVIES', 'What clownfish is searching for his lost son in "Finding Nemo"?', 'Marlin', 200),
('THING', 'MOVIES', 'What is the name of Nemo''s forgetful blue tang friend in "Finding Nemo"?', 'Dory', 100),
('THING', 'MOVIES', 'What superhero team assembles in the 2012 Marvel film of the same name?', 'The Avengers', 100),
('THING', 'MOVIES', 'What Marvel villain seeks to collect six magical Infinity Stones?', 'Thanos', 200),
('THING', 'MOVIES', 'What is the fictional African nation ruled by the superhero Black Panther?', 'Wakanda', 200),
('THING', 'MOVIES', 'What 2013 Disney film features the song "Let It Go"?', 'Frozen', 100),
('THING', 'MOVIES', 'What is the name of the snowman in Disney''s "Frozen"?', 'Olaf', 100),
('THING', 'MOVIES', 'What dystopian games give "The Hunger Games" its title?', 'The Hunger Games', 200),
('THING', 'MOVIES', 'What 2009 film set on the alien world of Pandora became the highest-grossing film ever at the time?', 'Avatar', 200),
('THING', 'MOVIES', 'What doll comes to life and questions her identity in the 2023 film "Barbie"?', 'Barbie', 100),
('THING', 'MOVIES', 'What 2023 film about the creator of the atomic bomb won Best Picture?', 'Oppenheimer', 200),
('THING', 'MOVIES', 'What South Korean film won Best Picture at the 2020 Academy Awards?', 'Parasite', 300),
('THING', 'MOVIES', 'What annual awards ceremony gives out Oscar statuettes?', 'The Academy Awards', 100),
('THING', 'MOVIES', 'What is the highest annual film award given by the Academy of Motion Picture Arts and Sciences called?', 'Best Picture', 100),

-- More MOVIES / PERSON
('PERSON', 'MOVIES', 'Which actor played Michael Myers'' nemesis, Dr. Loomis, in the original "Halloween"?', 'Donald Pleasence', 300),
('PERSON', 'MOVIES', 'Which director made the original 1978 "Halloween"?', 'John Carpenter', 300),
('PERSON', 'MOVIES', 'Which actress starred as Ellen Ripley in the "Alien" film series?', 'Sigourney Weaver', 200),
('PERSON', 'MOVIES', 'Which director made "Alien" and "Blade Runner"?', 'Ridley Scott', 200),
('PERSON', 'MOVIES', 'Which actor played the shark hunter Quint in "Jaws"?', 'Robert Shaw', 300),
('PERSON', 'MOVIES', 'Which actress played Princess Buttercup in "The Princess Bride"?', 'Robin Wright', 300),
('PERSON', 'MOVIES', 'Which actor played the Man in Black / Westley in "The Princess Bride"?', 'Cary Elwes', 300),
('PERSON', 'MOVIES', 'Which actor played Batman in Tim Burton''s 1989 "Batman"?', 'Michael Keaton', 200),
('PERSON', 'MOVIES', 'Which actor played the Joker in Tim Burton''s 1989 "Batman"?', 'Jack Nicholson', 200),
('PERSON', 'MOVIES', 'Which actress played Catwoman in "Batman Returns"?', 'Michelle Pfeiffer', 300),
('PERSON', 'MOVIES', 'Which actor played Batman in "The Dark Knight" trilogy?', 'Christian Bale', 200),
('PERSON', 'MOVIES', 'Which actress played Ellen Ripley''s successor as an action heroine in "Kill Bill"?', 'Uma Thurman', 200),
('PERSON', 'MOVIES', 'Which actor played Vincent Vega in "Pulp Fiction"?', 'John Travolta', 200),
('PERSON', 'MOVIES', 'Which actor starred as Danny Zuko in "Grease"?', 'John Travolta', 200),
('PERSON', 'MOVIES', 'Which actress starred as Sandy in "Grease"?', 'Olivia Newton-John', 200),
('PERSON', 'MOVIES', 'Which actor played Maximus in "Gladiator"?', 'Russell Crowe', 200),
('PERSON', 'MOVIES', 'Which director made "Gladiator" and "Blade Runner"?', 'Ridley Scott', 300),
('PERSON', 'MOVIES', 'Which actress played Elizabeth Swann in "Pirates of the Caribbean"?', 'Keira Knightley', 200),
('PERSON', 'MOVIES', 'Which actor played Captain Barbossa in "Pirates of the Caribbean"?', 'Geoffrey Rush', 300),
('PERSON', 'MOVIES', 'Which actor played Wolverine in the "X-Men" film series?', 'Hugh Jackman', 100),
('PERSON', 'MOVIES', 'Which actress played Storm in the "X-Men" film series?', 'Halle Berry', 300),
('PERSON', 'MOVIES', 'Which actor played Professor Charles Xavier in the original "X-Men" trilogy?', 'Patrick Stewart', 300),
('PERSON', 'MOVIES', 'Which actor played the Hulk / Bruce Banner in the Marvel Cinematic Universe from 2012 onward?', 'Mark Ruffalo', 200),
('PERSON', 'MOVIES', 'Which actress played Black Widow in the Marvel Cinematic Universe?', 'Scarlett Johansson', 100),
('PERSON', 'MOVIES', 'Which actor played Star-Lord in "Guardians of the Galaxy"?', 'Chris Pratt', 200),
('PERSON', 'MOVIES', 'Which director made "Guardians of the Galaxy"?', 'James Gunn', 300),
('PERSON', 'MOVIES', 'Which actress played Wonder Woman in the DC Extended Universe?', 'Gal Gadot', 100),
('PERSON', 'MOVIES', 'Which actor played Superman in "Man of Steel" and "Justice League"?', 'Henry Cavill', 200),
('PERSON', 'MOVIES', 'Which actor played Deadpool?', 'Ryan Reynolds', 100),
('PERSON', 'MOVIES', 'Which actor played Ron Weasley in the "Harry Potter" films?', 'Rupert Grint', 100),
('PERSON', 'MOVIES', 'Which actor played Dumbledore in the first two "Harry Potter" films?', 'Richard Harris', 300),
('PERSON', 'MOVIES', 'Which actor played Severus Snape in the "Harry Potter" films?', 'Alan Rickman', 200),
('PERSON', 'MOVIES', 'Which actor played Gandalf in "The Lord of the Rings"?', 'Ian McKellen', 200),
('PERSON', 'MOVIES', 'Which actor played Aragorn in "The Lord of the Rings"?', 'Viggo Mortensen', 300),
('PERSON', 'MOVIES', 'Which actor played Gollum in "The Lord of the Rings" through motion capture?', 'Andy Serkis', 300),
('PERSON', 'MOVIES', 'Which actress played Bridget Jones in "Bridget Jones''s Diary"?', 'Renee Zellweger', 300),
('PERSON', 'MOVIES', 'Which actor played Mr. Darcy in "Bridget Jones''s Diary" and "Pride & Prejudice"?', 'Colin Firth', 300),
('PERSON', 'MOVIES', 'Which actress played Andy Sachs in "The Devil Wears Prada"?', 'Anne Hathaway', 200),
('PERSON', 'MOVIES', 'Which actress played the demanding editor Miranda Priestly in "The Devil Wears Prada"?', 'Meryl Streep', 200),
('PERSON', 'MOVIES', 'Which actor played the title role in "Napoleon Dynamite"?', 'Jon Heder', 300),
('PERSON', 'MOVIES', 'Which comedic actor starred in "Anchorman" as Ron Burgundy?', 'Will Ferrell', 200),
('PERSON', 'MOVIES', 'Which actor played Shrek (voice role)?', 'Mike Myers', 200),
('PERSON', 'MOVIES', 'Which actor voiced Donkey in "Shrek"?', 'Eddie Murphy', 200),
('PERSON', 'MOVIES', 'Which comedian starred in "The Nutty Professor" and "Coming to America"?', 'Eddie Murphy', 200),
('PERSON', 'MOVIES', 'Which actor played Austin Powers?', 'Mike Myers', 200),
('PERSON', 'MOVIES', 'Which actress played Bella Swan in the "Twilight" film series?', 'Kristen Stewart', 200),
('PERSON', 'MOVIES', 'Which actor played Edward Cullen in the "Twilight" film series?', 'Robert Pattinson', 200),
('PERSON', 'MOVIES', 'Which actor played Peeta Mellark in "The Hunger Games" films?', 'Josh Hutcherson', 300),
('PERSON', 'MOVIES', 'Which actor played the villainous President Snow in "The Hunger Games" films?', 'Donald Sutherland', 300),
('PERSON', 'MOVIES', 'Which director made "Get Out" and "Us"?', 'Jordan Peele', 200),
('PERSON', 'MOVIES', 'Which director made "Inside Out" and "Up"?', 'Pete Docter', 300),
('PERSON', 'MOVIES', 'Which actor voiced the grumpy old man Carl in "Up"?', 'Ed Asner', 300),
('PERSON', 'MOVIES', 'Which actress played Mia Thermopolis in "The Princess Diaries"?', 'Anne Hathaway', 200),
('PERSON', 'MOVIES', 'Which actress played Cher in the 1995 film "Clueless"?', 'Alicia Silverstone', 300),
('PERSON', 'MOVIES', 'Which director made "Clueless"?', 'Amy Heckerling', 300),
('PERSON', 'MOVIES', 'Which actress played Elle Driver in "Kill Bill"?', 'Daryl Hannah', 300),
('PERSON', 'MOVIES', 'Which actor played the title role in "Edward Scissorhands"?', 'Johnny Depp', 200),
('PERSON', 'MOVIES', 'Which director made "Edward Scissorhands" and "Beetlejuice"?', 'Tim Burton', 200),
('PERSON', 'MOVIES', 'Which actor played Beetlejuice?', 'Michael Keaton', 300),

-- More MOVIES / THING
('THING', 'MOVIES', 'What franchise features a masked killer named Michael Myers stalking Haddonfield, Illinois?', 'Halloween', 200),
('THING', 'MOVIES', 'What spaceship crew discovers a deadly alien creature in the 1979 film "Alien"?', 'The Nostromo crew', 300),
('THING', 'MOVIES', 'What company do Ripley and her crew work for in the "Alien" franchise?', 'Weyland-Yutani', 300),
('THING', 'MOVIES', 'What oversized creatures does Westley claim "don''t exist" right before one attacks in the Fire Swamp, in "The Princess Bride"?', 'Rodents of Unusual Size', 300),
('THING', 'MOVIES', 'What is the name of the villain in "The Princess Bride" who wants to marry Buttercup?', 'Prince Humperdinck', 300),
('THING', 'MOVIES', 'What fictional city is protected by Batman?', 'Gotham City', 100),
('THING', 'MOVIES', 'What is the name of Batman''s loyal butler?', 'Alfred', 100),
('THING', 'MOVIES', 'What is the name of the vehicle Batman drives?', 'The Batmobile', 100),
('THING', 'MOVIES', 'What criminal organization does Neo fight against in "The Matrix"?', 'The Agents', 300),
('THING', 'MOVIES', 'What 1994 film follows a boxer-turned-hitman on "one last job" alongside a gangster''s wife on a night out?', 'Pulp Fiction', 300),
('THING', 'MOVIES', 'What 1978 musical film starred John Travolta and Olivia Newton-John as high schoolers?', 'Grease', 100),
('THING', 'MOVIES', 'What 2000 film follows a Roman general seeking revenge as a gladiator?', 'Gladiator', 200),
('THING', 'MOVIES', 'What team of mutants does Professor X lead in the "X-Men" films?', 'The X-Men', 100),
('THING', 'MOVIES', 'What metal covers Wolverine''s claws and skeleton in "X-Men"?', 'Adamantium', 300),
('THING', 'MOVIES', 'What group of misfit heroes, led by Star-Lord, protect the galaxy in the Marvel films?', 'Guardians of the Galaxy', 100),
('THING', 'MOVIES', 'What Amazonian island is Wonder Woman''s home in the DC films?', 'Themyscira', 300),
('THING', 'MOVIES', 'What term describes Deadpool''s rapid self-healing ability, granted by the Weapon X program?', 'Regeneration', 300),
('THING', 'MOVIES', 'What class does Professor Snape teach at Hogwarts in the "Harry Potter" films?', 'Potions', 200),
('THING', 'MOVIES', 'What creature guards the vaults at Gringotts Wizarding Bank in "Harry Potter"?', 'Dragons', 300),
('THING', 'MOVIES', 'What is the name of the volcano Frodo must reach to destroy the One Ring?', 'Mount Doom', 200),
('THING', 'MOVIES', 'What is the name of Gollum''s split personality, obsessed with "my precious"?', 'Smeagol', 300),
('THING', 'MOVIES', 'What fashion magazine does the film "The Devil Wears Prada" center around?', 'Runway', 300),
('THING', 'MOVIES', 'What 2004 film follows a group of California wine enthusiasts on a road trip?', 'Sideways', 300),
('THING', 'MOVIES', 'What 2004 mockumentary-style comedy follows an awkward high schooler and his llama farm?', 'Napoleon Dynamite', 200),
('THING', 'MOVIES', 'What fictional cable news anchor does Will Ferrell play in "Anchorman"?', 'Ron Burgundy', 200),
('THING', 'MOVIES', 'What ogre lives in a swamp and rescues Princess Fiona in "Shrek"?', 'Shrek', 100),
('THING', 'MOVIES', 'What 1995 film, based on a novel, follows a wealthy L.A. teenager named Cher navigating high school?', 'Clueless', 200),
('THING', 'MOVIES', 'What horror-comedy 1988 Tim Burton film features a mischievous ghost trying to scare away a living family?', 'Beetlejuice', 200),
('THING', 'MOVIES', 'What is the name Beetlejuice must be said three times to summon him?', 'Beetlejuice', 200),
('THING', 'MOVIES', 'What 2017 horror film by Jordan Peele follows a Black man visiting his white girlfriend''s family?', 'Get Out', 200),
('THING', 'MOVIES', 'What Pixar film follows the emotions inside a young girl''s mind, including Joy and Sadness?', 'Inside Out', 100),
('THING', 'MOVIES', 'What Pixar film follows an elderly widower who ties balloons to his house?', 'Up', 100),
('THING', 'MOVIES', 'What robot falls in love with another robot named EVE in a Pixar film?', 'WALL-E', 200),
('THING', 'MOVIES', 'What 2004 Pixar film follows a family of undercover superheroes?', 'The Incredibles', 100),
('THING', 'MOVIES', 'What underwater kingdom is home to the crab Sebastian in Disney''s "The Little Mermaid"?', 'Atlantica', 300),
('THING', 'MOVIES', 'What is the name of the mermaid protagonist of Disney''s "The Little Mermaid"?', 'Ariel', 100),
('THING', 'MOVIES', 'What Disney film features a lion cub named Simba who must reclaim his throne?', 'The Lion King', 100),
('THING', 'MOVIES', 'What phrase, meaning "no worries," is sung by Timon and Pumbaa in "The Lion King"?', 'Hakuna Matata', 100),
('THING', 'MOVIES', 'What Disney film follows a young Chinese woman who disguises herself as a soldier?', 'Mulan', 100),
('THING', 'MOVIES', 'What Disney film features a genie granting three wishes to a street urchin?', 'Aladdin', 100),
('THING', 'MOVIES', 'What is the name of the magic carpet in Disney''s "Aladdin"?', 'Magic Carpet', 200),
('THING', 'MOVIES', 'What animated film follows a rat who dreams of becoming a chef in Paris?', 'Ratatouille', 200),
('THING', 'MOVIES', 'What monster company powers its world with children''s screams in "Monsters, Inc."?', 'Monsters, Inc.', 200),

-- ============================================================================
-- FACTION: MUSIC / PERSON -- musicians, singers, and bands
-- ============================================================================

-- Golden Age & classic era (curated legends tier)
('PERSON', 'MUSIC', 'Which bandleader was known as the "King of Swing" in the big band era?', 'Benny Goodman', 300),
('PERSON', 'MUSIC', 'Which jazz trumpeter and singer was known for "What a Wonderful World"?', 'Louis Armstrong', 200),
('PERSON', 'MUSIC', 'Which singer was known as "Ol'' Blue Eyes" and sang "My Way"?', 'Frank Sinatra', 200),
('PERSON', 'MUSIC', 'Which singer became known as the "King of Rock and Roll" in the 1950s?', 'Elvis Presley', 100),
('PERSON', 'MUSIC', 'Which singer known for "Great Balls of Fire" was a pioneering rock and roll pianist?', 'Jerry Lee Lewis', 300),

-- 1960s-1970s
('PERSON', 'MUSIC', 'Which British band, formed in Liverpool, recorded "Abbey Road" and "Let It Be"?', 'The Beatles', 100),
('PERSON', 'MUSIC', 'Which British rock band is fronted by Mick Jagger?', 'The Rolling Stones', 200),
('PERSON', 'MUSIC', 'Which guitarist is famous for his performance of "The Star-Spangled Banner" at Woodstock?', 'Jimi Hendrix', 300),
('PERSON', 'MUSIC', 'Which singer-songwriter released "Like a Rolling Stone" and won the Nobel Prize in Literature?', 'Bob Dylan', 300),
('PERSON', 'MUSIC', 'Which reggae musician is famous for "No Woman, No Cry" and "One Love"?', 'Bob Marley', 200),
('PERSON', 'MUSIC', 'Which singer fronted the band Queen?', 'Freddie Mercury', 100),
('PERSON', 'MUSIC', 'Which disco and pop group sang "Dancing Queen" and "Mamma Mia"?', 'ABBA', 200),
('PERSON', 'MUSIC', 'Which soul singer was known as the "Queen of Soul" and sang "Respect"?', 'Aretha Franklin', 200),
('PERSON', 'MUSIC', 'Which Motown singer was known as the "King of Pop" before Michael Jackson claimed the title?', 'Stevie Wonder', 300),
('PERSON', 'MUSIC', 'Which singer-songwriter recorded "Piano Man" and "Uptown Girl"?', 'Billy Joel', 200),

-- 1980s
('PERSON', 'MUSIC', 'Which artist is known as the "King of Pop" and released the album "Thriller"?', 'Michael Jackson', 100),
('PERSON', 'MUSIC', 'Which singer is known as the "Queen of Pop" and released "Like a Virgin"?', 'Madonna', 100),
('PERSON', 'MUSIC', 'Which rock band, fronted by Bono, released "The Joshua Tree"?', 'U2', 200),
('PERSON', 'MUSIC', 'Which pop superstar, born Stefani Germanotta, released "Poker Face" and "Bad Romance"?', 'Lady Gaga', 100),
('PERSON', 'MUSIC', 'Which guitarist and singer fronted Guns N'' Roses on hits like "Sweet Child o'' Mine"?', 'Axl Rose', 300),
('PERSON', 'MUSIC', 'Which pop star released "Like a Prayer" and starred in "Evita"?', 'Madonna', 200),
('PERSON', 'MUSIC', 'Which singer known as "The Boss" recorded "Born in the U.S.A."?', 'Bruce Springsteen', 200),
('PERSON', 'MUSIC', 'Which singer fronted the British duo Eurythmics on hits like "Sweet Dreams (Are Made of This)"?', 'Annie Lennox', 300),
('PERSON', 'MUSIC', 'Which artist released the album "Purple Rain" and starred in the film of the same name?', 'Prince', 200),
('PERSON', 'MUSIC', 'Which grunge band, fronted by Kurt Cobain, released "Smells Like Teen Spirit"?', 'Nirvana', 200),

-- 1990s
('PERSON', 'MUSIC', 'Which R&B and pop singer released "I Will Always Love You" for "The Bodyguard"?', 'Whitney Houston', 100),
('PERSON', 'MUSIC', 'Which singer-songwriter fronted Nirvana before his death in 1994?', 'Kurt Cobain', 200),
('PERSON', 'MUSIC', 'Which girl group sang "Wannabe" and "Spice Up Your Life"?', 'Spice Girls', 200),
('PERSON', 'MUSIC', 'Which Canadian singer recorded "My Heart Will Go On" for "Titanic"?', 'Celine Dion', 100),
('PERSON', 'MUSIC', 'Which rapper released "All Eyez on Me" and was a leading figure in West Coast hip-hop?', 'Tupac Shakur', 200),
('PERSON', 'MUSIC', 'Which rapper released "Ready to Die" and was a leading figure in East Coast hip-hop?', 'The Notorious B.I.G.', 300),
('PERSON', 'MUSIC', 'Which boy band sang "I Want It That Way"?', 'Backstreet Boys', 200),
('PERSON', 'MUSIC', 'Which alternative rock band, fronted by Thom Yorke, released "OK Computer"?', 'Radiohead', 300),
('PERSON', 'MUSIC', 'Which singer released "...Baby One More Time" in 1998?', 'Britney Spears', 100),
('PERSON', 'MUSIC', 'Which Irish rock band released "One" and "Even Better Than the Real Thing"?', 'U2', 300),

-- 2000s
('PERSON', 'MUSIC', 'Which singer released the albums "Songs in A Minor" and "The Diary of Alicia Keys"?', 'Alicia Keys', 300),
('PERSON', 'MUSIC', 'Which rapper released "Lose Yourself" for the film "8 Mile"?', 'Eminem', 200),
('PERSON', 'MUSIC', 'Which singer released "Since U Been Gone" after winning "American Idol"?', 'Kelly Clarkson', 300),
('PERSON', 'MUSIC', 'Which singer fronted Destiny''s Child before her solo career?', 'Beyonce', 100),
('PERSON', 'MUSIC', 'Which country-turned-pop singer released "Fearless" and later "1989"?', 'Taylor Swift', 100),
('PERSON', 'MUSIC', 'Which singer released "Rehab" and the album "Back to Black"?', 'Amy Winehouse', 200),
('PERSON', 'MUSIC', 'Which artist released "Umbrella" featuring Jay-Z?', 'Rihanna', 200),
('PERSON', 'MUSIC', 'Which pop-punk singer released "Sk8er Boi" and "Complicated"?', 'Avril Lavigne', 200),
('PERSON', 'MUSIC', 'Which rapper released "In da Club" in 2003?', '50 Cent', 200),
('PERSON', 'MUSIC', 'Which band, fronted by Chris Martin, released "Yellow" and "Fix You"?', 'Coldplay', 200),

-- 2010s-2020s
('PERSON', 'MUSIC', 'Which singer released "Rolling in the Deep" and "Someone Like You"?', 'Adele', 100),
('PERSON', 'MUSIC', 'Which singer released "Shape of You" and "Perfect"?', 'Ed Sheeran', 100),
('PERSON', 'MUSIC', 'Which Canadian singer released "Sorry" and "What Do You Mean?"?', 'Justin Bieber', 100),
('PERSON', 'MUSIC', 'Which singer released "Bad Guy" as a teenager in 2019?', 'Billie Eilish', 100),
('PERSON', 'MUSIC', 'Which South Korean group released "Dynamite" and became global superstars?', 'BTS', 200),
('PERSON', 'MUSIC', 'Which singer released the albums "1989," "Folklore," and "Midnights"?', 'Taylor Swift', 100),
('PERSON', 'MUSIC', 'Which rapper released "Old Town Road," a record-breaking country-rap crossover?', 'Lil Nas X', 200),
('PERSON', 'MUSIC', 'Which artist and producer''s song "Uptown Funk" featured Bruno Mars on vocals?', 'Mark Ronson', 300),
('PERSON', 'MUSIC', 'Which singer released "Levitating" and "Don''t Start Now"?', 'Dua Lipa', 200),
('PERSON', 'MUSIC', 'Which singer released "As It Was" in 2022?', 'Harry Styles', 200),

-- ============================================================================
-- FACTION: MUSIC / THING -- songs, albums, genres, and instruments
-- ============================================================================

('THING', 'MUSIC', 'What genre of music, born in New Orleans, features improvisation and syncopation?', 'Jazz', 200),
('THING', 'MUSIC', 'What genre of dance music dominated by large ensembles was popular in the 1930s-40s, led by figures like Benny Goodman?', 'Big band / Swing', 300),
('THING', 'MUSIC', 'What 1965 Beatles album features "Yesterday"?', 'Help!', 300),
('THING', 'MUSIC', 'What 1969 Beatles album features the famous cover of the band crossing a street?', 'Abbey Road', 200),
('THING', 'MUSIC', 'What 1967 Beatles album is considered one of the first "concept albums," featuring a fictional band?', 'Sgt. Pepper''s Lonely Hearts Club Band', 300),
('THING', 'MUSIC', 'What 1971 outdoor music festival is often remembered as a defining moment of the 1960s counterculture?', 'Woodstock', 200),
('THING', 'MUSIC', 'What genre features electric guitars, strong rhythms, and grew out of rock and roll in the 1960s-70s?', 'Rock', 100),
('THING', 'MUSIC', 'What 1977 Bee Gees-driven soundtrack defined the disco era?', 'Saturday Night Fever', 300),
('THING', 'MUSIC', 'What dance music genre, featuring a steady four-on-the-floor beat, was hugely popular in the late 1970s?', 'Disco', 200),
('THING', 'MUSIC', 'What Michael Jackson album, released in 1982, became the best-selling album of all time?', 'Thriller', 100),
('THING', 'MUSIC', 'What music video channel, launched in 1981, transformed how pop music was marketed?', 'MTV', 200),
('THING', 'MUSIC', 'What genre of loud, distorted rock music, associated with Seattle in the early 1990s, is exemplified by Nirvana?', 'Grunge', 200),
('THING', 'MUSIC', 'What genre of music, originating in the Bronx in the 1970s, features rapping over beats?', 'Hip hop', 100),
('THING', 'MUSIC', 'What Jamaican music genre, associated with Bob Marley, features off-beat rhythms?', 'Reggae', 200),
('THING', 'MUSIC', 'What instrument does a guitarist play with a "pick" or their fingers to produce sound?', 'Guitar', 100),
('THING', 'MUSIC', 'What is the name of the annual awards show that gives out the "Grammy" trophies?', 'The Grammy Awards', 100),
('THING', 'MUSIC', 'What genre of upbeat electronic dance music became mainstream in the 2010s, often abbreviated EDM?', 'Electronic dance music', 200),
('THING', 'MUSIC', 'What 1991 Nirvana song opens with the line "Load up on guns, bring your friends"?', 'Smells Like Teen Spirit', 200),
('THING', 'MUSIC', 'What 2003 song by Beyonce featuring Jay-Z became one of her signature solo hits?', 'Crazy in Love', 300),
('THING', 'MUSIC', 'What streaming service, launched in 2008, transformed how people listen to music?', 'Spotify', 200),
('THING', 'MUSIC', 'What genre of Korean pop music, exemplified by BTS and BLACKPINK, became a global phenomenon?', 'K-pop', 100),
('THING', 'MUSIC', 'What 2017 Ed Sheeran song about romance became a massive worldwide hit?', 'Shape of You', 200),
('THING', 'MUSIC', 'What annual outdoor music festival, held in California, is known for its fashion as much as its lineup?', 'Coachella', 200),
('THING', 'MUSIC', 'What term describes a musician''s first officially released song of a new album, used to promote it?', 'Single', 200),
('THING', 'MUSIC', 'What term describes a collection of songs released together as one body of work?', 'Album', 100),

-- More MUSIC / PERSON
('PERSON', 'MUSIC', 'Which singer is known as "The King" of rockabilly and recorded "Jailhouse Rock"?', 'Elvis Presley', 200),
('PERSON', 'MUSIC', 'Paul Simon''s singing partner in Simon & Garfunkel was which musician?', 'Art Garfunkel', 300),
('PERSON', 'MUSIC', 'Which folk-rock duo recorded "The Sound of Silence"?', 'Simon & Garfunkel', 300),
('PERSON', 'MUSIC', 'Which singer-songwriter recorded "Fire and Rain" and "You''ve Got a Friend"?', 'James Taylor', 300),
('PERSON', 'MUSIC', 'Which singer-songwriter released the album "Blue," considered one of the greatest of all time?', 'Joni Mitchell', 300),
('PERSON', 'MUSIC', 'Which band, fronted by Robert Plant and Jimmy Page, released "Stairway to Heaven"?', 'Led Zeppelin', 200),
('PERSON', 'MUSIC', 'Which band released "Bohemian Rhapsody" in 1975?', 'Queen', 100),
('PERSON', 'MUSIC', 'Which singer, known as "The Piano Man," is also famous for "We Didn''t Start the Fire"?', 'Billy Joel', 200),
('PERSON', 'MUSIC', 'Which rock band released "Hotel California" in 1976?', 'Eagles', 200),
('PERSON', 'MUSIC', 'Which singer and songwriter is known for the album "Rumours" as part of Fleetwood Mac?', 'Stevie Nicks', 300),
('PERSON', 'MUSIC', 'Which artist is known as "The Boss" and recorded "Dancing in the Dark"?', 'Bruce Springsteen', 200),
('PERSON', 'MUSIC', 'Which rock band, fronted by Steven Tyler, released "Dream On" and "Walk This Way"?', 'Aerosmith', 200),
('PERSON', 'MUSIC', 'Which singer released "Girls Just Want to Have Fun" and "Time After Time"?', 'Cyndi Lauper', 300),
('PERSON', 'MUSIC', 'Which singer released "Livin'' on a Prayer" as the frontman of his namesake band?', 'Jon Bon Jovi', 200),
('PERSON', 'MUSIC', 'Which pop group, made up of five brothers, launched Michael Jackson''s career?', 'The Jackson 5', 200),
('PERSON', 'MUSIC', 'Which singer released "Karma Chameleon" as the frontman of Culture Club?', 'Boy George', 300),
('PERSON', 'MUSIC', 'Which synth-pop duo released "Take On Me" in 1985?', 'a-ha', 300),
('PERSON', 'MUSIC', 'Which rapper released "Fight the Power" and fronted Public Enemy?', 'Chuck D', 300),
('PERSON', 'MUSIC', 'Which rapper released "U Can''t Touch This" in 1990?', 'MC Hammer', 200),
('PERSON', 'MUSIC', 'Which rapper released "Baby Got Back" in 1992?', 'Sir Mix-a-Lot', 300),
('PERSON', 'MUSIC', 'Which R&B group sang "End of the Road" and "I''ll Make Love to You"?', 'Boyz II Men', 300),
('PERSON', 'MUSIC', 'Which singer released "Genie in a Bottle" in 1999?', 'Christina Aguilera', 200),
('PERSON', 'MUSIC', 'Which Latin pop star released "Livin'' la Vida Loca" in 1999?', 'Ricky Martin', 200),
('PERSON', 'MUSIC', 'Which singer, part of ''N Sync, went on to a major solo career including "Cry Me a River"?', 'Justin Timberlake', 200),
('PERSON', 'MUSIC', 'Which boy band sang "Bye Bye Bye" in 2000?', 'NSYNC', 200),
('PERSON', 'MUSIC', 'Which rock band, fronted by Chad Kroeger, released "How You Remind Me"?', 'Nickelback', 300),
('PERSON', 'MUSIC', 'Which singer released "Complicated" and "Sk8er Boi" as a teenager in 2002?', 'Avril Lavigne', 200),
('PERSON', 'MUSIC', 'Which rapper released "In Da Club" and "Candy Shop"?', '50 Cent', 200),
('PERSON', 'MUSIC', 'Which singer released "Hips Don''t Lie" featuring Wyclef Jean?', 'Shakira', 200),
('PERSON', 'MUSIC', 'Which band, fronted by Chris Martin, released "Clocks" and "Viva la Vida"?', 'Coldplay', 200),
('PERSON', 'MUSIC', 'Which singer released "Since U Been Gone" and "Stronger"?', 'Kelly Clarkson', 200),
('PERSON', 'MUSIC', 'Which pop-rock band released "Mr. Brightside"?', 'The Killers', 300),
('PERSON', 'MUSIC', 'Which singer released "Hey There Delilah" as the frontman of Plain White T''s?', 'Tom Higgenson', 300),
('PERSON', 'MUSIC', 'Which artist released "Party in the U.S.A."?', 'Miley Cyrus', 200),
('PERSON', 'MUSIC', 'Which rapper released "Gold Digger" featuring Jamie Foxx?', 'Kanye West', 200),
('PERSON', 'MUSIC', 'Which singer released "Halo" and "Single Ladies (Put a Ring on It)"?', 'Beyonce', 200),
('PERSON', 'MUSIC', 'Which singer released "Just Dance" as her breakout single in 2008?', 'Lady Gaga', 200),
('PERSON', 'MUSIC', 'Which country singer crossed over to pop with "Before He Cheats"?', 'Carrie Underwood', 200),
('PERSON', 'MUSIC', 'Which singer released "Firework" and "California Gurls"?', 'Katy Perry', 200),
('PERSON', 'MUSIC', 'Which singer released "Just the Way You Are" and "Grenade"?', 'Bruno Mars', 200),
('PERSON', 'MUSIC', 'Which rapper released "Started from the Bottom" and is from Toronto?', 'Drake', 100),
('PERSON', 'MUSIC', 'Which singer released "Someone You Loved" in 2018?', 'Lewis Capaldi', 300),
('PERSON', 'MUSIC', 'Which singer released "Blank Space" and "Shake It Off"?', 'Taylor Swift', 100),
('PERSON', 'MUSIC', 'Which singer released "thank u, next" in 2018?', 'Ariana Grande', 200),
('PERSON', 'MUSIC', 'Which rapper released "HUMBLE." and won a Pulitzer Prize for his album "DAMN."?', 'Kendrick Lamar', 300),
('PERSON', 'MUSIC', 'Which singer released "Watermelon Sugar" and "Adore You"?', 'Harry Styles', 200),
('PERSON', 'MUSIC', 'Which singer, formerly of One Direction, released "Sign of the Times"?', 'Harry Styles', 200),
('PERSON', 'MUSIC', 'Which British boy band released "What Makes You Beautiful"?', 'One Direction', 200),
('PERSON', 'MUSIC', 'Which singer released "drivers license" in 2021?', 'Olivia Rodrigo', 200),
('PERSON', 'MUSIC', 'Which rapper released "God''s Plan" and "One Dance"?', 'Drake', 200),

-- More MUSIC / THING
('THING', 'MUSIC', 'What Led Zeppelin song is widely considered one of the greatest rock songs ever written?', 'Stairway to Heaven', 200),
('THING', 'MUSIC', 'What Queen song, over six minutes long with no repeating chorus, became a surprise hit?', 'Bohemian Rhapsody', 200),
('THING', 'MUSIC', 'What Eagles song is famous for the line "you can check out any time you like, but you can never leave"?', 'Hotel California', 200),
('THING', 'MUSIC', 'What genre of loud, fast, aggressive rock music, associated with bands like Metallica, emerged in the 1980s?', 'Heavy metal', 200),
('THING', 'MUSIC', 'What genre of rap music associated with the West Coast in the early 1990s features stories of street life?', 'Gangsta rap', 300),
('THING', 'MUSIC', 'What genre features fiddles, banjos, and storytelling lyrics, popular in Nashville?', 'Country music', 100),
('THING', 'MUSIC', 'What 1977 disco soundtrack album, tied to a John Travolta film, dominated the charts?', 'Saturday Night Fever', 300),
('THING', 'MUSIC', 'What term describes a song that returns to popularity or is performed again by a new artist?', 'Cover', 200),
('THING', 'MUSIC', 'What term describes an artist''s very first album?', 'Debut album', 200),
('THING', 'MUSIC', 'What music chart, published by Billboard magazine, ranks the most popular singles in the US?', 'The Billboard Hot 100', 300),
('THING', 'MUSIC', 'What genre blends country and pop and became hugely popular through artists like Taylor Swift?', 'Country pop', 300),
('THING', 'MUSIC', 'What is the name of the streaming award show honoring music videos, launched by MTV in 1984?', 'MTV Video Music Awards', 300),
('THING', 'MUSIC', 'What term describes a musician who writes their own songs rather than performing others'' material?', 'Singer-songwriter', 200),
('THING', 'MUSIC', 'What instrument is central to the "big band" swing sound, typically leading the brass section?', 'Trumpet', 300),
('THING', 'MUSIC', 'What genre of Jamaican music influenced by reggae, faster in tempo, is associated with artists like Sean Paul?', 'Dancehall', 300),

-- ============================================================================
-- FACTION: TV / PERSON

-- ============================================================================
-- FACTION: TV / PERSON -- actors and the characters they're known for playing
-- ============================================================================

-- 1950s-1970s
('PERSON', 'TV', 'Which actress starred in the classic 1950s sitcom "I Love Lucy"?', 'Lucille Ball', 200),
('PERSON', 'TV', 'Which actor played Captain Kirk in the original "Star Trek" series?', 'William Shatner', 200),
('PERSON', 'TV', 'Which actor played Mr. Spock in the original "Star Trek" series?', 'Leonard Nimoy', 200),
('PERSON', 'TV', 'Which actor starred as Fonzie in "Happy Days"?', 'Henry Winkler', 300),

-- 1980s-1990s
('PERSON', 'TV', 'Which actor played the title role in "The Cosby Show"?', 'Bill Cosby', 300),
('PERSON', 'TV', 'Which actor played Alex P. Keaton in "Family Ties"?', 'Michael J. Fox', 300),
('PERSON', 'TV', 'Which actor starred as Jerry in the sitcom "Seinfeld"?', 'Jerry Seinfeld', 200),
('PERSON', 'TV', 'Which actress played Elaine Benes in "Seinfeld"?', 'Julia Louis-Dreyfus', 200),
('PERSON', 'TV', 'Which actor played Ross Geller in "Friends"?', 'David Schwimmer', 100),
('PERSON', 'TV', 'Which actress played Rachel Green in "Friends"?', 'Jennifer Aniston', 100),
('PERSON', 'TV', 'Which actor played Chandler Bing in "Friends"?', 'Matthew Perry', 200),
('PERSON', 'TV', 'Which actress played Monica Geller in "Friends"?', 'Courteney Cox', 200),
('PERSON', 'TV', 'Which actor voices Homer Simpson on "The Simpsons"?', 'Dan Castellaneta', 300),
('PERSON', 'TV', 'Which talk show host became known for giving away cars on her daytime talk show?', 'Oprah Winfrey', 200),
('PERSON', 'TV', 'Which actor starred as the title character in "The Fresh Prince of Bel-Air"?', 'Will Smith', 200),
('PERSON', 'TV', 'Which actor played Fox Mulder on "The X-Files"?', 'David Duchovny', 300),

-- 2000s
('PERSON', 'TV', 'Which actor played Michael Scott in the American version of "The Office"?', 'Steve Carell', 100),
('PERSON', 'TV', 'Which actor played Tony Soprano in "The Sopranos"?', 'James Gandolfini', 300),
('PERSON', 'TV', 'Which actor played Jack Bauer in "24"?', 'Kiefer Sutherland', 300),
('PERSON', 'TV', 'Which actress played Carrie Bradshaw in "Sex and the City"?', 'Sarah Jessica Parker', 200),
('PERSON', 'TV', 'Which actor played Jack Shephard in "Lost"?', 'Matthew Fox', 300),
('PERSON', 'TV', 'Which actor played Dr. Gregory House in "House"?', 'Hugh Laurie', 200),
('PERSON', 'TV', 'Which host became famous for hosting "American Idol" for its original run?', 'Ryan Seacrest', 300),
('PERSON', 'TV', 'Which actress played Sheldon Cooper''s neighbor Penny in "The Big Bang Theory"?', 'Kaley Cuoco', 200),
('PERSON', 'TV', 'Which actor played Sheldon Cooper in "The Big Bang Theory"?', 'Jim Parsons', 200),
('PERSON', 'TV', 'Which actor played Walter White in "Breaking Bad"?', 'Bryan Cranston', 100),

-- 2010s-2020s
('PERSON', 'TV', 'Which actor played Jon Snow in "Game of Thrones"?', 'Kit Harington', 200),
('PERSON', 'TV', 'Which actress played Daenerys Targaryen in "Game of Thrones"?', 'Emilia Clarke', 200),
('PERSON', 'TV', 'Which actor played Eleven''s father figure, Hopper, in "Stranger Things"?', 'David Harbour', 300),
('PERSON', 'TV', 'Which actress played Eleven in "Stranger Things"?', 'Millie Bobby Brown', 200),
('PERSON', 'TV', 'Which comedian hosts "The Tonight Show" after taking over from Jay Leno?', 'Jimmy Fallon', 300),
('PERSON', 'TV', 'Which actor played the title role in the soccer comedy "Ted Lasso"?', 'Jason Sudeikis', 200),
('PERSON', 'TV', 'Which actress starred as Wednesday Addams in the 2022 Netflix series "Wednesday"?', 'Jenna Ortega', 200),
('PERSON', 'TV', 'Which actor played Logan Roy in "Succession"?', 'Brian Cox', 300),

-- ============================================================================
-- FACTION: TV / THING -- shows, characters, catchphrases, and formats
-- ============================================================================

('THING', 'TV', 'What Springfield family is at the center of the long-running animated show "The Simpsons"?', 'The Simpsons', 100),
('THING', 'TV', 'What is Bart Simpson''s famous catchphrase, told to authority figures who annoy him?', 'Eat my shorts', 300),
('THING', 'TV', 'What 1990s sitcom followed six friends living in New York City?', 'Friends', 100),
('THING', 'TV', 'What coffee shop do the characters of "Friends" frequently hang out in?', 'Central Perk', 200),
('THING', 'TV', 'What sitcom is set in a New York apartment building and follows Jerry, George, Elaine, and Kramer?', 'Seinfeld', 200),
('THING', 'TV', 'What long-running late-night show, launched in 1975, is known for its "Weekend Update" segment?', 'Saturday Night Live', 200),
('THING', 'TV', 'What children''s educational show, launched in 1969, is set on a fictional street in New York City?', 'Sesame Street', 200),
('THING', 'TV', 'What game show host greeting phrase is famously associated with "The Price Is Right"?', 'Come on down', 300),
('THING', 'TV', 'What 1990s-2000s game show asked contestants "Is that your final answer?"', 'Who Wants to Be a Millionaire', 200),
('THING', 'TV', 'What crime drama follows a chemistry teacher who turns to making methamphetamine?', 'Breaking Bad', 100),
('THING', 'TV', 'What fantasy series, based on novels by George R.R. Martin, features the fictional continent of Westeros?', 'Game of Thrones', 100),
('THING', 'TV', 'What supernatural Netflix series is set in the fictional town of Hawkins, Indiana?', 'Stranger Things', 100),
('THING', 'TV', 'What alternate dimension do characters travel to in "Stranger Things"?', 'The Upside Down', 200),
('THING', 'TV', 'What mockumentary-style sitcom is set at the fictional Dunder Mifflin paper company?', 'The Office', 100),
('THING', 'TV', 'What medical drama is set at Seattle Grace Hospital?', 'Grey''s Anatomy', 200),
('THING', 'TV', 'What HBO series follows a New Jersey mob boss balancing family and crime?', 'The Sopranos', 300),
('THING', 'TV', 'What reality competition show has contestants competing to avoid elimination on a deserted location?', 'Survivor', 200),
('THING', 'TV', 'What singing competition show made Kelly Clarkson its first winner in 2002?', 'American Idol', 200),
('THING', 'TV', 'What animated show follows a family in Quahog, Rhode Island, created by Seth MacFarlane?', 'Family Guy', 200),
('THING', 'TV', 'What sketch comedy and variety show has been broadcast live from Studio 8H since 1975?', 'Saturday Night Live', 300),
('THING', 'TV', 'What British sci-fi series follows a time-traveling alien known as "the Doctor"?', 'Doctor Who', 200),
('THING', 'TV', 'What sitcom about four socially awkward scientists is set near Caltech?', 'The Big Bang Theory', 200),
('THING', 'TV', 'What streaming service launched "Stranger Things" and "Wednesday"?', 'Netflix', 100),
('THING', 'TV', 'What awards show honors excellence in American television programming?', 'The Emmy Awards', 200),

-- More TV / PERSON
('PERSON', 'TV', 'Which actress played Blanche Devereaux on "The Golden Girls"?', 'Rue McClanahan', 300),
('PERSON', 'TV', 'Which actor played Batman in the campy 1960s "Batman" TV series?', 'Adam West', 300),
('PERSON', 'TV', 'Which actor played Archie Bunker in "All in the Family"?', 'Carroll O''Connor', 300),
('PERSON', 'TV', 'Which actor played J.R. Ewing in "Dallas"?', 'Larry Hagman', 300),
('PERSON', 'TV', 'Which actress played Blair Warner in "The Facts of Life"?', 'Lisa Whelchel', 300),
('PERSON', 'TV', 'Which actor played MacGyver, known for improvised gadgets?', 'Richard Dean Anderson', 300),
('PERSON', 'TV', 'Which actor played Sam Malone in "Cheers"?', 'Ted Danson', 300),
('PERSON', 'TV', 'Which actress played Murphy Brown?', 'Candice Bergen', 300),
('PERSON', 'TV', 'Which actor played Screech in "Saved by the Bell"?', 'Dustin Diamond', 300),
('PERSON', 'TV', 'Which actress played Buffy in "Buffy the Vampire Slayer"?', 'Sarah Michelle Gellar', 200),
('PERSON', 'TV', 'Which actress played Joyce Byers, mother of Will and Jonathan, in "Stranger Things"?', 'Winona Ryder', 300),
('PERSON', 'TV', 'Which actor played Phoebe Buffay''s love interest Mike in the later seasons of "Friends"?', 'Paul Rudd', 300),
('PERSON', 'TV', 'Which actress played Lorelai Gilmore in "Gilmore Girls"?', 'Lauren Graham', 300),
('PERSON', 'TV', 'Which actor played Don Draper in "Mad Men"?', 'Jon Hamm', 300),
('PERSON', 'TV', 'Which actress played Peggy Olson in "Mad Men"?', 'Elisabeth Moss', 300),
('PERSON', 'TV', 'Which actor played Michael Scott''s successor, Andy Bernard, in "The Office"?', 'Ed Helms', 300),
('PERSON', 'TV', 'Which actress played Leslie Knope in "Parks and Recreation"?', 'Amy Poehler', 200),
('PERSON', 'TV', 'Which actor played Ron Swanson in "Parks and Recreation"?', 'Nick Offerman', 200),
('PERSON', 'TV', 'Which actress played Robin Scherbatsky in "How I Met Your Mother"?', 'Cobie Smulders', 300),
('PERSON', 'TV', 'Which actor played Barney Stinson in "How I Met Your Mother"?', 'Neil Patrick Harris', 200),
('PERSON', 'TV', 'Which actor played the con man nicknamed "Sawyer" in "Lost"?', 'Josh Holloway', 300),
('PERSON', 'TV', 'Which actress played Olivia Pope in "Scandal"?', 'Kerry Washington', 300),
('PERSON', 'TV', 'Which actor played Rick Grimes in "The Walking Dead"?', 'Andrew Lincoln', 200),
('PERSON', 'TV', 'Which actress played Claire Underwood in "House of Cards"?', 'Robin Wright', 300),
('PERSON', 'TV', 'Which actor played Frank Underwood in "House of Cards"?', 'Kevin Spacey', 300),
('PERSON', 'TV', 'Which actress played Elizabeth Jennings in "The Americans"?', 'Keri Russell', 300),
('PERSON', 'TV', 'Which actor played Tyrion Lannister in "Game of Thrones"?', 'Peter Dinklage', 200),
('PERSON', 'TV', 'Which actress played Cersei Lannister in "Game of Thrones"?', 'Lena Headey', 300),
('PERSON', 'TV', 'Which comedian hosted "The Daily Show" before Jon Stewart''s original run ended?', 'Jon Stewart', 300),
('PERSON', 'TV', 'Which actor voices Rick Sanchez in "Rick and Morty"?', 'Justin Roiland', 300),
('PERSON', 'TV', 'Which actress played Phoebe Buffay in "Friends"?', 'Lisa Kudrow', 200),
('PERSON', 'TV', 'Which actor played Joey Tribbiani in "Friends"?', 'Matt LeBlanc', 200),

-- More TV / THING
('THING', 'TV', 'What sitcom, set in Miami, follows four older women sharing a house?', 'The Golden Girls', 200),
('THING', 'TV', 'What 1960s campy superhero show starred Adam West as the Caped Crusader?', 'Batman', 300),
('THING', 'TV', 'What sitcom follows a working-class family, the Bunkers, in Queens, New York?', 'All in the Family', 300),
('THING', 'TV', 'What primetime soap opera follows the oil-rich Ewing family in Texas?', 'Dallas', 300),
('THING', 'TV', 'What sitcom is set in a Boston bar "where everybody knows your name"?', 'Cheers', 200),
('THING', 'TV', 'What teen sitcom is set at the fictional Bayside High School?', 'Saved by the Bell', 200),
('THING', 'TV', 'What supernatural drama follows a teenage girl chosen to fight vampires?', 'Buffy the Vampire Slayer', 200),
('THING', 'TV', 'What comedy-drama follows a mother and daughter in the small town of Stars Hollow?', 'Gilmore Girls', 200),
('THING', 'TV', 'What advertising-agency drama is set in 1960s Madison Avenue?', 'Mad Men', 200),
('THING', 'TV', 'What mockumentary sitcom follows government employees in the Parks Department of Pawnee, Indiana?', 'Parks and Recreation', 200),
('THING', 'TV', 'What sitcom follows a group of friends navigating relationships and jobs in New York, narrated in flashback?', 'How I Met Your Mother', 200),
('THING', 'TV', 'What post-apocalyptic drama follows survivors of a zombie outbreak?', 'The Walking Dead', 100),
('THING', 'TV', 'What political drama follows a ruthless congressman''s rise to the presidency?', 'House of Cards', 300),
('THING', 'TV', 'What spy drama follows two Soviet KGB agents posing as an American family?', 'The Americans', 300),
('THING', 'TV', 'What late-night satirical news show was hosted by Jon Stewart for over a decade?', 'The Daily Show', 200),
('THING', 'TV', 'What animated sci-fi comedy follows a genius scientist and his none-too-bright grandson?', 'Rick and Morty', 200),
('THING', 'TV', 'What fantasy series features the noble houses Stark, Lannister, and Targaryen?', 'Game of Thrones', 100),
('THING', 'TV', 'What is the name of the giant ice wall that protects Westeros from threats in the North?', 'The Wall', 300),
('THING', 'TV', 'What is the name of Jon Snow''s direwolf in "Game of Thrones"?', 'Ghost', 300),
('THING', 'TV', 'What word do the Starks use as their House motto, warning that danger is always near?', 'Winter is Coming', 200),
('THING', 'TV', 'What Netflix competition show features contestants baking and decorating, hosted with British charm?', 'The Great British Bake Off', 300),
('THING', 'TV', 'What long-running animated show follows a dysfunctional family in Quahog, Rhode Island, with a talking dog and baby?', 'Family Guy', 200),
('THING', 'TV', 'What is the name of the elementary school Bart and Lisa Simpson attend?', 'Springfield Elementary', 300),
('THING', 'TV', 'What reality show franchise, hosted by Simon Cowell, searches for the next singing star in the UK and beyond?', 'The X Factor', 300),
('THING', 'TV', 'What competitive cooking show, hosted by Gordon Ramsay, pits aspiring chefs against each other?', 'Hell''s Kitchen', 300),

-- ============================================================================
-- FACTION: LITERATURE / PERSON

-- ============================================================================
-- FACTION: LITERATURE / PERSON -- authors (leaning into books that also
-- became famous films, fair crossover territory for a pop-culture category)
-- ============================================================================

('PERSON', 'LITERATURE', 'Which author wrote "The Great Gatsby"?', 'F. Scott Fitzgerald', 200),
('PERSON', 'LITERATURE', 'Which author wrote "To Kill a Mockingbird"?', 'Harper Lee', 200),
('PERSON', 'LITERATURE', 'Which author wrote "1984" and "Animal Farm"?', 'George Orwell', 200),
('PERSON', 'LITERATURE', 'Which author wrote "The Lord of the Rings" and "The Hobbit"?', 'J.R.R. Tolkien', 100),
('PERSON', 'LITERATURE', 'Which author wrote "Jaws," later adapted into the Spielberg film?', 'Peter Benchley', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Godfather," later adapted into the Coppola film?', 'Mario Puzo', 300),
('PERSON', 'LITERATURE', 'Which author wrote the "Harry Potter" series?', 'J.K. Rowling', 100),
('PERSON', 'LITERATURE', 'Which author wrote "Jurassic Park," later adapted into the Spielberg film?', 'Michael Crichton', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Charlie and the Chocolate Factory" and "Matilda"?', 'Roald Dahl', 100),
('PERSON', 'LITERATURE', 'Which author wrote the "Chronicles of Narnia" series?', 'C.S. Lewis', 200),
('PERSON', 'LITERATURE', 'Which horror author wrote "It," "The Shining," and "Carrie"?', 'Stephen King', 100),
('PERSON', 'LITERATURE', 'Which author wrote "The Da Vinci Code"?', 'Dan Brown', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Twilight"?', 'Stephenie Meyer', 200),
('PERSON', 'LITERATURE', 'Which author wrote "The Hunger Games" trilogy?', 'Suzanne Collins', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Gone Girl," later adapted into a film starring Ben Affleck?', 'Gillian Flynn', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Fault in Our Stars"?', 'John Green', 200),
('PERSON', 'LITERATURE', 'Which mystery author created the detective Hercule Poirot?', 'Agatha Christie', 300),
('PERSON', 'LITERATURE', 'Which author created the detective Sherlock Holmes?', 'Arthur Conan Doyle', 200),
('PERSON', 'LITERATURE', 'Which playwright wrote "Romeo and Juliet" and "Hamlet"?', 'William Shakespeare', 100),
('PERSON', 'LITERATURE', 'Which author wrote "Where the Wild Things Are"?', 'Maurice Sendak', 200),

-- ============================================================================
-- FACTION: LITERATURE / THING -- titles, characters, and series
-- ============================================================================

('THING', 'LITERATURE', 'What novel by F. Scott Fitzgerald follows the mysterious millionaire Jay Gatsby?', 'The Great Gatsby', 200),
('THING', 'LITERATURE', 'What George Orwell novel introduces the phrase "Big Brother is watching you"?', '1984', 200),
('THING', 'LITERATURE', 'What fantasy novel begins with a hobbit named Bilbo Baggins finding a magic ring?', 'The Hobbit', 100),
('THING', 'LITERATURE', 'What is the name of the wizarding school Harry Potter attends?', 'Hogwarts', 100),
('THING', 'LITERATURE', 'What is the name of Harry Potter''s best friend, known for his red hair and large family?', 'Ron Weasley', 100),
('THING', 'LITERATURE', 'What sport, played on flying broomsticks, is popular at Hogwarts?', 'Quidditch', 200),
('THING', 'LITERATURE', 'What dystopian trilogy features a televised fight to the death called the titular "Games"?', 'The Hunger Games', 200),
('THING', 'LITERATURE', 'What is the name of the fictional nation where "The Hunger Games" is set?', 'Panem', 300),
('THING', 'LITERATURE', 'What vampire romance series is set in the fictional town of Forks, Washington?', 'Twilight', 200),
('THING', 'LITERATURE', 'What classic novel follows Scout Finch and her father Atticus in the Depression-era South?', 'To Kill a Mockingbird', 200),
('THING', 'LITERATURE', 'What object, blown to call meetings, becomes a symbol of order in "Lord of the Flies"?', 'The conch shell', 300),
('THING', 'LITERATURE', 'What children''s book by Maurice Sendak follows Max''s journey to a land of monsters?', 'Where the Wild Things Are', 200),
('THING', 'LITERATURE', 'What chocolate factory does Charlie win a golden ticket to visit?', 'Willy Wonka''s Chocolate Factory', 100),
('THING', 'LITERATURE', 'What is the name of the young detective created by Agatha Christie with a fondness for his "little grey cells"?', 'Hercule Poirot', 300),
('THING', 'LITERATURE', 'What is the name of Sherlock Holmes'' loyal companion and chronicler?', 'Dr. Watson', 200),
('THING', 'LITERATURE', 'What street does Sherlock Holmes famously live on in London?', 'Baker Street', 300),
('THING', 'LITERATURE', 'What Shakespeare play features the line "To be, or not to be"?', 'Hamlet', 200),
('THING', 'LITERATURE', 'What Shakespeare play follows two feuding families and their star-crossed children?', 'Romeo and Juliet', 100),
('THING', 'LITERATURE', 'What thriller novel and film follows a woman who fakes her own disappearance?', 'Gone Girl', 300),
('THING', 'LITERATURE', 'What symbol does Dan Brown''s "The Da Vinci Code" center much of its mystery around?', 'The Holy Grail', 300),

-- More LITERATURE / PERSON
('PERSON', 'LITERATURE', 'Which author wrote "Little Women"?', 'Louisa May Alcott', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Pride and Prejudice"?', 'Jane Austen', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Moby-Dick"?', 'Herman Melville', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Adventures of Huckleberry Finn"?', 'Mark Twain', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Alice''s Adventures in Wonderland"?', 'Lewis Carroll', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Charlotte''s Web" and "Stuart Little"?', 'E.B. White', 200),
('PERSON', 'LITERATURE', 'Which author wrote the dystopian novel "Brave New World"?', 'Aldous Huxley', 300),
('PERSON', 'LITERATURE', 'Which author wrote "One Flew Over the Cuckoo''s Nest"?', 'Ken Kesey', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Catcher in the Rye"?', 'J.D. Salinger', 200),
('PERSON', 'LITERATURE', 'Which author wrote "Of Mice and Men" and "The Grapes of Wrath"?', 'John Steinbeck', 200),
('PERSON', 'LITERATURE', 'Which author created the character James Bond?', 'Ian Fleming', 300),
('PERSON', 'LITERATURE', 'Which author wrote the "Percy Jackson" series?', 'Rick Riordan', 200),
('PERSON', 'LITERATURE', 'Which author wrote "The Chronicles of Narnia" and taught at Oxford alongside Tolkien?', 'C.S. Lewis', 300),
('PERSON', 'LITERATURE', 'Which author wrote "A Wrinkle in Time"?', 'Madeleine L''Engle', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Giver"?', 'Lois Lowry', 300),
('PERSON', 'LITERATURE', 'Which author wrote "Diary of a Wimpy Kid"?', 'Jeff Kinney', 200),
('PERSON', 'LITERATURE', 'Which author wrote "The Outsiders" as a teenager?', 'S.E. Hinton', 300),
('PERSON', 'LITERATURE', 'Which author wrote "Life of Pi"?', 'Yann Martel', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Kite Runner"?', 'Khaled Hosseini', 300),
('PERSON', 'LITERATURE', 'Which author wrote "The Alchemist"?', 'Paulo Coelho', 300),

-- More LITERATURE / THING
('THING', 'LITERATURE', 'What classic novel follows four sisters -- Meg, Jo, Beth, and Amy -- growing up during the Civil War?', 'Little Women', 200),
('THING', 'LITERATURE', 'What novel follows Elizabeth Bennet and the proud Mr. Darcy?', 'Pride and Prejudice', 200),
('THING', 'LITERATURE', 'What novel follows a young girl who falls down a rabbit hole into a fantastical world?', 'Alice''s Adventures in Wonderland', 200),
('THING', 'LITERATURE', 'What children''s novel follows a pig named Wilbur saved by a spider''s web messages?', 'Charlotte''s Web', 200),
('THING', 'LITERATURE', 'What is the name of the spider who saves Wilbur in "Charlotte''s Web"?', 'Charlotte', 200),
('THING', 'LITERATURE', 'What dystopian novel follows a boy named Jonas who lives in a "utopian" society without pain, memory, or color?', 'The Giver', 300),
('THING', 'LITERATURE', 'What novel follows teenage gang rivalries between the Greasers and the Socs?', 'The Outsiders', 300),
('THING', 'LITERATURE', 'What novel follows a boy stranded on a lifeboat with a Bengal tiger named Richard Parker?', 'Life of Pi', 300),
('THING', 'LITERATURE', 'What series follows a demigod son of Poseidon navigating Greek mythology in the modern world?', 'Percy Jackson', 200),
('THING', 'LITERATURE', 'What spy novel series, created by Ian Fleming, features agent 007?', 'James Bond', 200),
('THING', 'LITERATURE', 'What classic adventure novel follows pirates searching for buried treasure, narrated by young Jim Hawkins?', 'Treasure Island', 300),
('THING', 'LITERATURE', 'What novel follows an orphan boy who is adopted after asking for "more" gruel in a workhouse?', 'Oliver Twist', 300),
('THING', 'LITERATURE', 'What novel by Mark Twain follows a boy who tricks his friends into whitewashing a fence?', 'The Adventures of Tom Sawyer', 200),
('THING', 'LITERATURE', 'What comic strip and book series follows a mischievous boy and his stuffed tiger?', 'Calvin and Hobbes', 200),
('THING', 'LITERATURE', 'What graphic-heavy children''s book series follows Greg Heffley''s awkward middle school life?', 'Diary of a Wimpy Kid', 200),
('THING', 'LITERATURE', 'What fantasy series follows a young wizard fighting the Dark Lord Voldemort across seven books?', 'Harry Potter', 100),
('THING', 'LITERATURE', 'What term describes a story written specifically to teach a moral lesson, often using animal characters?', 'Fable', 200),
('THING', 'LITERATURE', 'What term describes a book that is the first in a planned series?', 'Debut', 300),
('THING', 'LITERATURE', 'What annual award, named after a Swedish inventor, has been given for Literature since 1901?', 'The Nobel Prize', 300),
('THING', 'LITERATURE', 'What annual American award honors the best in fiction, journalism, and the arts, including literature?', 'The Pulitzer Prize', 300),

-- ============================================================================
-- FACTION: ART / PERSON

-- ============================================================================
-- FACTION: ART / PERSON -- artists whose work is broadly recognized outside
-- an art-history classroom
-- ============================================================================

('PERSON', 'ART', 'Which Italian Renaissance artist painted the "Mona Lisa"?', 'Leonardo da Vinci', 100),
('PERSON', 'ART', 'Which Italian Renaissance artist painted the ceiling of the Sistine Chapel?', 'Michelangelo', 100),
('PERSON', 'ART', 'Which Dutch painter is famous for "The Starry Night" and cutting off part of his own ear?', 'Vincent van Gogh', 100),
('PERSON', 'ART', 'Which Spanish artist is known for the surrealist melting clocks in "The Persistence of Memory"?', 'Salvador Dali', 200),
('PERSON', 'ART', 'Which Spanish artist co-founded Cubism and painted "Guernica"?', 'Pablo Picasso', 100),
('PERSON', 'ART', 'Which Norwegian artist painted "The Scream"?', 'Edvard Munch', 200),
('PERSON', 'ART', 'Which American artist painted "American Gothic," showing a farmer and his daughter?', 'Grant Wood', 300),
('PERSON', 'ART', 'Which American artist is famous for Campbell''s Soup Can prints and pop art?', 'Andy Warhol', 200),
('PERSON', 'ART', 'Which American artist is known for splattering and dripping paint onto huge canvases?', 'Jackson Pollock', 200),
('PERSON', 'ART', 'Which Dutch painter is famous for "Girl with a Pearl Earring"?', 'Johannes Vermeer', 300),
('PERSON', 'ART', 'Which sculptor carved the statue of "David" in Florence?', 'Michelangelo', 200),
('PERSON', 'ART', 'Which French sculptor designed the Statue of Liberty?', 'Frederic Auguste Bartholdi', 300),
('PERSON', 'ART', 'Which street artist, known for anonymous stenciled work, is famous for "Girl with a Balloon"?', 'Banksy', 200),
('PERSON', 'ART', 'Which French Impressionist painter is known for his series of water lily paintings?', 'Claude Monet', 200),
('PERSON', 'ART', 'Which Mexican artist is famous for vivid self-portraits, including one with a monkey?', 'Frida Kahlo', 200),

-- ============================================================================
-- FACTION: ART / THING -- famous works, movements, and landmarks
-- ============================================================================

('THING', 'ART', 'What is the name of the famously enigmatic smiling woman painted by Leonardo da Vinci?', 'Mona Lisa', 100),
('THING', 'ART', 'What museum in Paris houses the "Mona Lisa"?', 'The Louvre', 200),
('THING', 'ART', 'What swirling, star-filled night sky painting was made by Vincent van Gogh?', 'The Starry Night', 100),
('THING', 'ART', 'What art movement, led by Monet and Renoir, focused on capturing light and fleeting moments?', 'Impressionism', 200),
('THING', 'ART', 'What art movement, pioneered by Picasso, depicts subjects from multiple angles at once?', 'Cubism', 200),
('THING', 'ART', 'What art movement, associated with Dali, explores dreamlike and irrational imagery?', 'Surrealism', 200),
('THING', 'ART', 'What art movement, associated with Warhol, drew imagery from advertising and mass media?', 'Pop art', 200),
('THING', 'ART', 'What famous painting shows a rural American farmer holding a pitchfork beside a woman?', 'American Gothic', 300),
('THING', 'ART', 'What is the title of Edvard Munch''s painting showing a figure with hands on its face against a swirling sky?', 'The Scream', 200),
('THING', 'ART', 'What large chapel in the Vatican has a famous ceiling painted by Michelangelo?', 'The Sistine Chapel', 200),
('THING', 'ART', 'What statue, holding a torch, stands in New York Harbor as a gift from France?', 'The Statue of Liberty', 100),
('THING', 'ART', 'What famous ancient Egyptian statue in Giza has the body of a lion and the head of a human?', 'The Great Sphinx', 200),
('THING', 'ART', 'What iron tower in Paris was built for the 1889 World''s Fair?', 'The Eiffel Tower', 100),
('THING', 'ART', 'What Pablo Picasso painting, named for a Spanish town, depicts the horrors of war?', 'Guernica', 300),
('THING', 'ART', 'What term describes a work of art carved or molded into a three-dimensional form?', 'Sculpture', 100),

-- More ART / PERSON
('PERSON', 'ART', 'Which German artist created influential woodcut prints during the Northern Renaissance?', 'Albrecht Durer', 300),
('PERSON', 'ART', 'Which Dutch painter is known for dramatic use of light and shadow, and self-portraits, including "The Night Watch"?', 'Rembrandt', 300),
('PERSON', 'ART', 'Which French sculptor created "The Thinker"?', 'Auguste Rodin', 300),
('PERSON', 'ART', 'Which artist, associated with Cubism alongside Picasso, co-founded the movement?', 'Georges Braque', 300),
('PERSON', 'ART', 'Which American realist painter is known for "Nighthawks," depicting a late-night diner?', 'Edward Hopper', 300),
('PERSON', 'ART', 'Which artist created large-scale abstract color field paintings, popular in mid-20th-century America?', 'Mark Rothko', 300),
('PERSON', 'ART', 'Which artist is known for giant sculptures of everyday soft objects, like a giant clothespin?', 'Claes Oldenburg', 300),
('PERSON', 'ART', 'Which artist painted colorful, primitivist self-portraits inspired by Mexican folk art?', 'Frida Kahlo', 200),
('PERSON', 'ART', 'Which artist, known for graffiti-inspired work, rose from the New York street art scene in the 1980s?', 'Jean-Michel Basquiat', 300),
('PERSON', 'ART', 'Which contemporary artist is known for wrapping famous landmarks in fabric, like the Reichstag?', 'Christo', 300),
('PERSON', 'ART', 'Which artist created the iconic 2008 "Hope" poster of Barack Obama?', 'Shepard Fairey', 300),
('PERSON', 'ART', 'Which sculptor created Mount Rushmore''s presidential faces?', 'Gutzon Borglum', 300),

-- More ART / THING
('THING', 'ART', 'What Dutch painting by Rembrandt, actually depicting a daytime scene, is famous for its dramatic lighting?', 'The Night Watch', 300),
('THING', 'ART', 'What bronze sculpture by Rodin depicts a man deep in contemplation, resting his chin on his hand?', 'The Thinker', 200),
('THING', 'ART', 'What Edward Hopper painting shows several lonely figures inside a brightly lit late-night diner?', 'Nighthawks', 300),
('THING', 'ART', 'What monument in South Dakota features the carved faces of four U.S. presidents?', 'Mount Rushmore', 100),
('THING', 'ART', 'Which U.S. President, also the first to hold the office, is carved into Mount Rushmore alongside Jefferson, Roosevelt, and Lincoln?', 'George Washington', 200),
('THING', 'ART', 'What ancient Roman amphitheater, famous for gladiator contests, still stands in Rome today?', 'The Colosseum', 100),
('THING', 'ART', 'What ancient wonder, a massive statue, once stood at the entrance to the harbor of Rhodes?', 'The Colossus of Rhodes', 300),
('THING', 'ART', 'What art style features bold colors, geometric shapes, and streamlined forms, popular in the 1920s-30s?', 'Art Deco', 300),
('THING', 'ART', 'What New York City skyscraper is a famous example of the Art Deco style, completed in 1931?', 'The Empire State Building', 200),
('THING', 'ART', 'What term describes an artist''s preliminary drawing or plan for a larger artwork?', 'Sketch', 200),
('THING', 'ART', 'What term describes the technique of applying layers of oil or acrylic paint to canvas?', 'Painting', 100),
('THING', 'ART', 'What term describes an artist''s depiction of themselves, made by their own hand?', 'Self-portrait', 100),
('THING', 'ART', 'What term describes an artwork depicting arranged objects, like fruit or flowers, rather than people or scenery?', 'Still life', 200),
('THING', 'ART', 'What term describes a painting of an outdoor scene, like fields, mountains, or the sea?', 'Landscape', 100),
('THING', 'ART', 'What genre of street art uses stencils and spray paint, often placed illegally in public spaces?', 'Graffiti', 100)

) AS v(subcategory, faction, question_text, correct_answer, points);
