-- ============================================================================
-- Primary School content expansion: ~500 new questions across 7 factions
-- (NUMBERS / WORDS_MEANING / WORDS_LABELS / SCIENCE_PHYSICAL / SCIENCE_LIFE /
-- SCIENCE_EARTH_SPACE / SCIENCE_GEOGRAPHY_TERMS).
--
-- Purely additive: does NOT touch, modify, or delete any existing row. Does
-- NOT drop or truncate anything (unlike seed.js, which rebuilds the whole
-- table -- this script is safe to run against a live database with existing
-- content, including production).
--
-- question_number is computed dynamically (current MAX + row position), so
-- this is safe to paste into Neon's SQL editor regardless of exactly what's
-- already in the table.
--
-- NUMBERS answers are stored as bare numerals on purpose (e.g. "6", not
-- "Six"; "180", not "180 degrees") so every multiple-choice row reads as a
-- clean list of numbers -- the question text itself carries any unit. That's
-- what makes a wildly-off distractor (e.g. "180" showing up as a wrong
-- answer to a hexagon question) read as an absurd number, not a formatting
-- glitch.
-- ============================================================================

INSERT INTO questions (question_number, game_mode, category, subcategory, faction, question_text, visual_asset, correct_answer, points)
SELECT (SELECT COALESCE(MAX(question_number), 0) FROM questions) + ROW_NUMBER() OVER (), 'TRIVIA', 'PRIMARY_SCHOOL', 'THING', v.faction, v.question_text, NULL, v.correct_answer, v.points
FROM (VALUES

-- ============================================================================
-- FACTION: NUMBERS -- the answer is always a number. Shapes, angles, counts
-- of things, measurement, time, money, sports, and civics/history numbers all
-- share one pool on purpose (see design discussion) -- an absurdly-scaled
-- wrong answer is the intended joke, not a bug.
-- ============================================================================

-- Polygon sides
('NUMBERS', 'How many sides does a triangle have?', '3', 100),
('NUMBERS', 'How many sides does a square have?', '4', 100),
('NUMBERS', 'How many sides does a pentagon have?', '5', 100),
('NUMBERS', 'How many sides does a hexagon have?', '6', 100),
('NUMBERS', 'How many sides does a heptagon have?', '7', 200),
('NUMBERS', 'How many sides does an octagon have?', '8', 100),
('NUMBERS', 'How many sides does a nonagon have?', '9', 200),
('NUMBERS', 'How many sides does a decagon have?', '10', 200),
('NUMBERS', 'How many sides does a dodecagon have?', '12', 300),
('NUMBERS', 'How many sides does a stop sign have?', '8', 100),
('NUMBERS', 'How many sides does a rhombus have?', '4', 100),
('NUMBERS', 'How many sides does a trapezoid have?', '4', 100),
('NUMBERS', 'How many sides does a parallelogram have?', '4', 100),

-- 3D shapes
('NUMBERS', 'How many faces does a cube have?', '6', 100),
('NUMBERS', 'How many edges does a cube have?', '12', 200),
('NUMBERS', 'How many vertices (corners) does a cube have?', '8', 200),
('NUMBERS', 'How many faces does a triangular pyramid have?', '4', 200),
('NUMBERS', 'How many faces does a square pyramid have?', '5', 200),
('NUMBERS', 'How many faces does a triangular prism have?', '5', 300),
('NUMBERS', 'How many faces does an octahedron have?', '8', 300),

-- Angles
('NUMBERS', 'How many degrees are in a right angle?', '90', 100),
('NUMBERS', 'How many degrees are in a straight angle?', '180', 100),
('NUMBERS', 'How many degrees do the interior angles of a triangle add up to?', '180', 200),
('NUMBERS', 'How many degrees do the interior angles of a quadrilateral add up to?', '360', 200),
('NUMBERS', 'How many degrees are in a full circle?', '360', 100),
('NUMBERS', 'How many degrees do the interior angles of a pentagon add up to?', '540', 300),

-- Body and animal counts
('NUMBERS', 'How many chambers does the human heart have?', '4', 100),
('NUMBERS', 'How many adult teeth does a typical human have, wisdom teeth included?', '32', 200),
('NUMBERS', 'How many bones are in the adult human body?', '206', 200),
('NUMBERS', 'How many bones are in the human hand?', '27', 300),
('NUMBERS', 'About how many bones is a human baby born with?', '270', 300),
('NUMBERS', 'About how many muscles are in the human body?', '600', 300),
('NUMBERS', 'How many legs does a typical insect have?', '6', 100),
('NUMBERS', 'How many legs does a spider have?', '8', 100),
('NUMBERS', 'How many legs does a lobster have, including its claws?', '10', 300),
('NUMBERS', 'How many hearts does an octopus have?', '3', 200),
('NUMBERS', 'How many arms does an octopus have?', '8', 100),
('NUMBERS', 'How many stomach compartments does a cow have?', '4', 200),
('NUMBERS', 'How many senses do humans traditionally have?', '5', 100),
('NUMBERS', 'How many pairs of ribs does the human body have?', '12', 300),
('NUMBERS', 'How many toes does a typical bird have on each foot?', '4', 300),
('NUMBERS', 'How many arms does a typical starfish have?', '5', 200),
('NUMBERS', 'How many primary (baby) teeth does a typical human child have?', '20', 200),
('NUMBERS', 'How many teeth does a typical adult dog have?', '42', 300),
('NUMBERS', 'How many wisdom teeth can a human have, at most?', '4', 200),

-- Earth, space, and everyday counts
('NUMBERS', 'How many planets are in our solar system?', '8', 100),
('NUMBERS', 'How many oceans are there on Earth?', '5', 100),
('NUMBERS', 'How many continents are there?', '7', 100),
('NUMBERS', 'How many of the Great Lakes are there?', '5', 200),
('NUMBERS', 'How many natural moons does Earth have?', '1', 100),
('NUMBERS', 'How many moons does Mars have?', '2', 300),
('NUMBERS', 'Earth is the how-many-eth planet from the Sun?', '3', 200),
('NUMBERS', 'Mars is the how-many-eth planet from the Sun?', '4', 200),
('NUMBERS', 'Jupiter is the how-many-eth planet from the Sun?', '5', 200),
('NUMBERS', 'How many officially recognized dwarf planets are there in our solar system?', '5', 300),
('NUMBERS', 'How many colors are in a rainbow?', '7', 100),
('NUMBERS', 'How many primary colors of light are there?', '3', 200),
('NUMBERS', 'How many strings does a standard guitar have?', '6', 100),
('NUMBERS', 'How many keys are on a standard piano?', '88', 300),
('NUMBERS', 'How many squares are on a chessboard?', '64', 200),
('NUMBERS', 'How many pieces does each player start with in chess?', '16', 200),
('NUMBERS', 'How many cards are in a standard deck, jokers excluded?', '52', 100),
('NUMBERS', 'How many suits are there in a standard deck of cards?', '4', 100),
('NUMBERS', 'How many cards are in each suit of a standard deck?', '13', 200),
('NUMBERS', 'How many face cards (Jack, Queen, King) are in each suit?', '3', 200),
('NUMBERS', 'How many tiles are in a standard double-six domino set?', '28', 300),
('NUMBERS', 'How many pieces does each player start with in checkers?', '12', 200),
('NUMBERS', 'How many squares are on a standard tic-tac-toe grid?', '9', 100),
('NUMBERS', 'How many faces does a standard die have?', '6', 100),
('NUMBERS', 'How many letters are in the English alphabet?', '26', 100),
('NUMBERS', 'How many vowels are in the English alphabet?', '5', 100),
('NUMBERS', 'How many wheels does a standard bicycle have?', '2', 100),
('NUMBERS', 'How many wheels does a tricycle have?', '3', 100),
('NUMBERS', 'How many zeros are in one million?', '6', 200),
('NUMBERS', 'How many zeros are in one billion?', '9', 300),

-- US civics and history
('NUMBERS', 'How many states are in the United States?', '50', 100),
('NUMBERS', 'How many original colonies were there in America?', '13', 200),
('NUMBERS', 'How many stars are on the current U.S. flag?', '50', 100),
('NUMBERS', 'How many stripes are on the U.S. flag?', '13', 100),
('NUMBERS', 'How many amendments are there to the U.S. Constitution?', '27', 300),
('NUMBERS', 'How many amendments make up the Bill of Rights?', '10', 200),
('NUMBERS', 'Which amendment to the U.S. Constitution protects freedom of speech?', '1', 200),
('NUMBERS', 'Which amendment to the U.S. Constitution abolished slavery?', '13', 300),
('NUMBERS', 'Which amendment to the U.S. Constitution gave women the right to vote?', '19', 300),
('NUMBERS', 'Which amendment to the U.S. Constitution lowered the voting age to 18?', '26', 300),
('NUMBERS', 'How many justices currently sit on the U.S. Supreme Court?', '9', 200),
('NUMBERS', 'George Washington was the how-many-eth President of the United States?', '1', 100),
('NUMBERS', 'Thomas Jefferson was the how-many-eth President of the United States?', '3', 200),
('NUMBERS', 'Abraham Lincoln was the how-many-eth President of the United States?', '16', 200),
('NUMBERS', 'Theodore Roosevelt was the how-many-eth President of the United States?', '26', 300),
('NUMBERS', 'Franklin D. Roosevelt was the how-many-eth President of the United States?', '32', 300),
('NUMBERS', 'John F. Kennedy was the how-many-eth President of the United States?', '35', 300),

-- Time
('NUMBERS', 'How many seconds are in a minute?', '60', 100),
('NUMBERS', 'How many minutes are in an hour?', '60', 100),
('NUMBERS', 'How many hours are in a day?', '24', 100),
('NUMBERS', 'How many days are in a week?', '7', 100),
('NUMBERS', 'How many weeks are in a year?', '52', 200),
('NUMBERS', 'How many months are in a year?', '12', 100),
('NUMBERS', 'How many days are in a standard, non-leap year?', '365', 200),
('NUMBERS', 'How many days are in a leap year?', '366', 200),
('NUMBERS', 'How many years are in a decade?', '10', 100),
('NUMBERS', 'How many years are in a century?', '100', 100),
('NUMBERS', 'How many years are in a millennium?', '1000', 200),

-- Money
('NUMBERS', 'How many pennies are in a dollar?', '100', 100),
('NUMBERS', 'How many nickels are in a dollar?', '20', 200),
('NUMBERS', 'How many dimes are in a dollar?', '10', 100),
('NUMBERS', 'How many quarters are in a dollar?', '4', 100),
('NUMBERS', 'How many cents is a quarter worth?', '25', 100),
('NUMBERS', 'How many cents is a dime worth?', '10', 100),

-- Measurement
('NUMBERS', 'How many inches are in a foot?', '12', 100),
('NUMBERS', 'How many feet are in a yard?', '3', 100),
('NUMBERS', 'How many feet are in a mile?', '5280', 300),
('NUMBERS', 'How many ounces are in a pound?', '16', 200),
('NUMBERS', 'How many pounds are in a (US) ton?', '2000', 300),
('NUMBERS', 'How many cups are in a gallon?', '16', 200),
('NUMBERS', 'How many quarts are in a gallon?', '4', 200),
('NUMBERS', 'How many pints are in a gallon?', '8', 200),
('NUMBERS', 'At what temperature, in Fahrenheit, does water freeze?', '32', 200),
('NUMBERS', 'At what temperature, in Fahrenheit, does water boil at sea level?', '212', 200),
('NUMBERS', 'At what temperature, in Celsius, does water freeze?', '0', 100),
('NUMBERS', 'At what temperature, in Celsius, does water boil at sea level?', '100', 200),

-- Sports
('NUMBERS', 'How many players from each team are on the field at once in soccer?', '11', 200),
('NUMBERS', 'How many players from each team are on the court at once in basketball?', '5', 100),
('NUMBERS', 'How many players from each team are on the field at once in baseball?', '9', 200),
('NUMBERS', 'How many innings are in a standard baseball game?', '9', 200),
('NUMBERS', 'How many players from each team are on the field at once in American football?', '11', 200),
('NUMBERS', 'How many players from each team are on the ice at once in hockey, goalie included?', '6', 300),
('NUMBERS', 'How many players from each team are on the court at once in volleyball?', '6', 200),
('NUMBERS', 'How many holes are on a standard golf course?', '18', 200),
('NUMBERS', 'How many pins are set up in ten-pin bowling?', '10', 100),

-- More shapes, counts, and everyday numbers
('NUMBERS', 'How many sides does an equilateral triangle have that are equal in length?', '3', 100),
('NUMBERS', 'How many right angles does a rectangle have?', '4', 100),
('NUMBERS', 'How many diagonals does a square have?', '2', 200),
('NUMBERS', 'How many vertices does a hexagon have?', '6', 200),
('NUMBERS', 'How many edges does a triangular prism have?', '9', 300),
('NUMBERS', 'How many players are on the ice for one team during 5-on-5 hockey play, goalie not included?', '5', 300),
('NUMBERS', 'How many events make up a decathlon?', '10', 300),
('NUMBERS', 'How many events make up a heptathlon?', '7', 300),
('NUMBERS', 'How many rings are on the Olympic flag?', '5', 200),
('NUMBERS', 'How many players are on a standard rugby union team on the field?', '15', 300),
('NUMBERS', 'How many periods are in a standard game of ice hockey?', '3', 200),
('NUMBERS', 'How many quarters are in a standard basketball game?', '4', 100),
('NUMBERS', 'How many downs does a team get in American football to advance the ball 10 yards?', '4', 300),
('NUMBERS', 'How many players are on each side in a standard game of doubles tennis?', '2', 100),
('NUMBERS', 'How many continents does the equator pass through?', '3', 300),
('NUMBERS', 'How many bones make up the human skull?', '22', 300),
('NUMBERS', 'How many lungs does a human have?', '2', 100),
('NUMBERS', 'How many kidneys does a human typically have?', '2', 100),
('NUMBERS', 'How many chromosomes are in a typical human cell?', '46', 300),
('NUMBERS', 'How many eyes does a bee have?', '5', 300),
('NUMBERS', 'How many wings does a typical butterfly have?', '4', 200),
('NUMBERS', 'How many humps does a Bactrian camel have?', '2', 200),
('NUMBERS', 'How many humps does a dromedary camel have?', '1', 200),
('NUMBERS', 'How many chambers does a typical fish heart have?', '2', 300),
('NUMBERS', 'How many legs does a crab have, including its claws?', '10', 300),
('NUMBERS', 'The word "centipede" literally means how many feet?', '100', 300),
('NUMBERS', 'How many segments does a typical ant''s body have?', '3', 300),
('NUMBERS', 'How many wonders were traditionally listed in the Seven Wonders of the Ancient World?', '7', 200),
('NUMBERS', 'How many dwarfs are in the classic story "Snow White and the Seven Dwarfs"?', '7', 100),
('NUMBERS', 'How many days does the story of Noah''s ark say it rained for?', '40', 300),
('NUMBERS', 'How many musicians are typically in a quartet?', '4', 100),
('NUMBERS', 'How many musicians are typically in a trio?', '3', 100),
('NUMBERS', 'How many musicians are typically in an octet?', '8', 300),
('NUMBERS', 'How many notes are in a standard musical scale (do-re-mi...do)?', '8', 200),
('NUMBERS', 'How many lines does a standard sonnet poem have?', '14', 300),
('NUMBERS', 'How many syllables are in a haiku''s first line?', '5', 300),
('NUMBERS', 'How many total syllables are in a traditional haiku?', '17', 300),
('NUMBERS', 'How many millimeters are in a centimeter?', '10', 200),
('NUMBERS', 'How many centimeters are in a meter?', '100', 200),
('NUMBERS', 'How many meters are in a kilometer?', '1000', 200),
('NUMBERS', 'How many grams are in a kilogram?', '1000', 200),
('NUMBERS', 'How many milliliters are in a liter?', '1000', 200),

-- ============================================================================
-- FACTION: WORDS_MEANING -- Greek/Latin roots and vocabulary (up to advanced
-- levels, on purpose, to keep the adults guessing too). Every correct answer
-- is a short meaning or definition, so this pool mixes safely.
-- ============================================================================

('WORDS_MEANING', 'What does the root "bio-" mean?', 'Life', 100),
('WORDS_MEANING', 'What does the root "geo-" mean?', 'Earth', 100),
('WORDS_MEANING', 'What does the root "tele-" mean?', 'Far / distant', 100),
('WORDS_MEANING', 'What does the root "phon-" mean?', 'Sound', 200),
('WORDS_MEANING', 'What does the root "photo-" mean?', 'Light', 200),
('WORDS_MEANING', 'What does the root "graph-" mean?', 'Write / written', 200),
('WORDS_MEANING', 'What does the root "aqua-" mean?', 'Water', 100),
('WORDS_MEANING', 'What does the root "hydro-" mean?', 'Water', 200),
('WORDS_MEANING', 'What does the root "terra-" mean?', 'Earth / land', 200),
('WORDS_MEANING', 'What does the root "astro-" mean?', 'Star', 200),
('WORDS_MEANING', 'What does the root "chrono-" mean?', 'Time', 200),
('WORDS_MEANING', 'What does the root "micro-" mean?', 'Small', 100),
('WORDS_MEANING', 'What does the root "macro-" mean?', 'Large', 200),
('WORDS_MEANING', 'What does the root "poly-" mean?', 'Many', 200),
('WORDS_MEANING', 'What does the root "mono-" mean?', 'One / single', 100),
('WORDS_MEANING', 'What does the root "bi-" mean?', 'Two', 100),
('WORDS_MEANING', 'What does the root "tri-" mean?', 'Three', 100),
('WORDS_MEANING', 'What does the root "therm-" mean?', 'Heat', 200),
('WORDS_MEANING', 'What does the root "path-" mean, as in "sympathy"?', 'Feeling / suffering', 300),
('WORDS_MEANING', 'What does the root "auto-" mean?', 'Self', 100),
('WORDS_MEANING', 'What does the root "anti-" mean?', 'Against', 100),
('WORDS_MEANING', 'What does the root "circum-" mean, as in "circumference"?', 'Around', 200),
('WORDS_MEANING', 'What does the root "trans-" mean, as in "transport"?', 'Across', 200),
('WORDS_MEANING', 'What does the root "port-" mean, as in "transport"?', 'Carry', 200),
('WORDS_MEANING', 'What does the root "dict-" mean, as in "predict"?', 'Speak / say', 200),
('WORDS_MEANING', 'What does the root "scrib-" or "script-" mean, as in "describe"?', 'Write', 200),
('WORDS_MEANING', 'What does the root "spect-" mean, as in "inspect"?', 'Look / see', 200),
('WORDS_MEANING', 'What does the root "aud-" mean, as in "audience"?', 'Hear', 200),
('WORDS_MEANING', 'What does the root "cred-" mean, as in "credible"?', 'Believe', 300),
('WORDS_MEANING', 'What does the root "duc-" or "duct-" mean, as in "conduct"?', 'Lead', 300),
('WORDS_MEANING', 'What does the root "gen-" mean, as in "generate"?', 'Birth / origin', 300),
('WORDS_MEANING', 'What does the root "morph-" mean, as in "metamorphosis"?', 'Shape / form', 300),
('WORDS_MEANING', 'What does the root "phil-" mean, as in "philosophy"?', 'Love', 200),
('WORDS_MEANING', 'What does the suffix "-phobia" mean?', 'Fear', 200),
('WORDS_MEANING', 'What does the root "zo-" mean, as in "zoology"?', 'Animal', 200),
('WORDS_MEANING', 'What does the root "dem-" mean, as in "democracy"?', 'People', 300),
('WORDS_MEANING', 'What does the suffix "-cracy" mean, as in "democracy"?', 'Rule / government', 300),
('WORDS_MEANING', 'What does the root "sol-" mean, as in "solar"?', 'Sun', 200),
('WORDS_MEANING', 'What does the root "luna-" mean, as in "lunar"?', 'Moon', 200),
('WORDS_MEANING', 'What does the root "vor-" mean, as in "carnivore"?', 'Eat / devour', 300),
('WORDS_MEANING', 'What does the root "corp-" mean, as in "corporation"?', 'Body', 300),
('WORDS_MEANING', 'What does the root "man-" mean, as in "manual"?', 'Hand', 200),
('WORDS_MEANING', 'What does the root "ped-" mean, as in "pedestrian"?', 'Foot', 200),
('WORDS_MEANING', 'What does the root "vis-" or "vid-" mean, as in "visible"?', 'See', 200),
('WORDS_MEANING', 'What does the root "flex-" mean, as in "flexible"?', 'Bend', 300),
('WORDS_MEANING', 'What does the root "junct-" mean, as in "conjunction"?', 'Join', 300),
('WORDS_MEANING', 'What does the root "mit-" or "miss-" mean, as in "transmit"?', 'Send', 300),
('WORDS_MEANING', 'What does the root "rupt-" mean, as in "interrupt"?', 'Break', 300),
('WORDS_MEANING', 'What does the root "vert-" mean, as in "convert"?', 'Turn', 300),
('WORDS_MEANING', 'What does the root "ject-" mean, as in "reject"?', 'Throw', 300),

('WORDS_MEANING', 'What does "ubiquitous" mean?', 'Present everywhere', 300),
('WORDS_MEANING', 'What does "ephemeral" mean?', 'Lasting a very short time', 300),
('WORDS_MEANING', 'What does "gregarious" mean?', 'Sociable / outgoing', 300),
('WORDS_MEANING', 'What does "meticulous" mean?', 'Extremely careful and precise', 200),
('WORDS_MEANING', 'What does "candid" mean?', 'Honest and direct', 200),
('WORDS_MEANING', 'What does "benevolent" mean?', 'Kind and generous', 200),
('WORDS_MEANING', 'What does "malevolent" mean?', 'Wishing harm to others', 200),
('WORDS_MEANING', 'What does "resilient" mean?', 'Able to recover quickly', 200),
('WORDS_MEANING', 'What does "ambiguous" mean?', 'Having more than one possible meaning', 200),
('WORDS_MEANING', 'What does "eloquent" mean?', 'Fluent and persuasive in speech', 200),
('WORDS_MEANING', 'What does "frugal" mean?', 'Careful with money', 200),
('WORDS_MEANING', 'What does "tenacious" mean?', 'Persistent / holding firm', 300),
('WORDS_MEANING', 'What does "verbose" mean?', 'Using far more words than needed', 300),
('WORDS_MEANING', 'What does "concise" mean?', 'Brief and clear', 100),
('WORDS_MEANING', 'What does "pragmatic" mean?', 'Practical', 200),
('WORDS_MEANING', 'What does "arbitrary" mean?', 'Based on random choice, not reason', 300),
('WORDS_MEANING', 'What does "clandestine" mean?', 'Secret / hidden', 300),
('WORDS_MEANING', 'What does "audacious" mean?', 'Bold and daring', 200),
('WORDS_MEANING', 'What does "empathy" mean?', 'Understanding another person''s feelings', 100),
('WORDS_MEANING', 'What does "apathy" mean?', 'Lack of interest or concern', 200),
('WORDS_MEANING', 'What does "novice" mean?', 'A beginner', 100),
('WORDS_MEANING', 'What does "obsolete" mean?', 'No longer in use', 100),
('WORDS_MEANING', 'What does "abundant" mean?', 'Existing in large amounts', 100),
('WORDS_MEANING', 'What does "scarce" mean?', 'Not enough / rare', 100),
('WORDS_MEANING', 'What does "diligent" mean?', 'Hardworking and careful', 200),
('WORDS_MEANING', 'What does "reluctant" mean?', 'Unwilling', 100),
('WORDS_MEANING', 'What does "vigilant" mean?', 'Watchful and alert', 200),
('WORDS_MEANING', 'What does "skeptical" mean?', 'Doubtful', 200),
('WORDS_MEANING', 'What does "credible" mean?', 'Believable', 100),
('WORDS_MEANING', 'What does "authentic" mean?', 'Genuine / real', 100),
('WORDS_MEANING', 'What does "unanimous" mean?', 'In complete agreement', 200),
('WORDS_MEANING', 'What does "adversary" mean?', 'An opponent', 200),
('WORDS_MEANING', 'What does "hypothesis" mean?', 'An educated guess', 100),
('WORDS_MEANING', 'What does "inference" mean?', 'A conclusion based on evidence', 200),
('WORDS_MEANING', 'What does "perspective" mean?', 'A point of view', 100),
('WORDS_MEANING', 'What does "colossal" mean?', 'Extremely large', 100),
('WORDS_MEANING', 'What does "tranquil" mean?', 'Calm and peaceful', 100),
('WORDS_MEANING', 'What does "furtive" mean?', 'Secretive / sneaky', 300),
('WORDS_MEANING', 'What does "innovative" mean?', 'Introducing new ideas', 200),
('WORDS_MEANING', 'What does "spontaneous" mean?', 'Happening without planning', 200),
('WORDS_MEANING', 'What does "docile" mean?', 'Easy to manage or teach', 300),
('WORDS_MEANING', 'What does "vivid" mean?', 'Producing powerful, clear images', 200),
('WORDS_MEANING', 'What does "monotonous" mean?', 'Dull and repetitive', 200),
('WORDS_MEANING', 'What does "articulate" mean?', 'Able to express ideas clearly', 200),
('WORDS_MEANING', 'What does "prudent" mean?', 'Wise and careful', 300),
('WORDS_MEANING', 'What does "ominous" mean?', 'Suggesting something bad is coming', 200),
('WORDS_MEANING', 'What does "meager" mean?', 'Small in amount', 200),
('WORDS_MEANING', 'What does "wary" mean?', 'Cautious of danger', 200),
('WORDS_MEANING', 'What does "ambivalent" mean?', 'Having mixed feelings', 300),
('WORDS_MEANING', 'What does "elated" mean?', 'Extremely happy', 100),
('WORDS_MEANING', 'What does "dejected" mean?', 'Sad and discouraged', 100),
('WORDS_MEANING', 'What does "obstinate" mean?', 'Stubbornly refusing to change', 300),
('WORDS_MEANING', 'What does "plausible" mean?', 'Reasonable and believable', 200),
('WORDS_MEANING', 'What does "fortify" mean?', 'To strengthen', 200),
('WORDS_MEANING', 'What does "banish" mean?', 'To send away by force', 100),
('WORDS_MEANING', 'What does "vast" mean?', 'Extremely large in area', 100),
('WORDS_MEANING', 'What does "brittle" mean?', 'Easily broken', 100),
('WORDS_MEANING', 'What does "peculiar" mean?', 'Strange or unusual', 100),
('WORDS_MEANING', 'What does "genuine" mean?', 'Real / authentic', 100),
('WORDS_MEANING', 'What does "commence" mean?', 'To begin', 100),
('WORDS_MEANING', 'What does "conclude" mean?', 'To bring to an end', 100),

-- More roots and advanced vocabulary
('WORDS_MEANING', 'What does the root "omni-" mean, as in "omnivore"?', 'All', 200),
('WORDS_MEANING', 'What does the root "equi-" mean, as in "equilateral"?', 'Equal', 200),
('WORDS_MEANING', 'What does the root "magni-" mean, as in "magnify"?', 'Great / large', 200),
('WORDS_MEANING', 'What does the root "multi-" mean, as in "multiply"?', 'Many', 100),
('WORDS_MEANING', 'What does the root "uni-" mean, as in "unicycle"?', 'One', 100),
('WORDS_MEANING', 'What does the root "quad-" mean, as in "quadrilateral"?', 'Four', 100),
('WORDS_MEANING', 'What does the root "pent-" mean, as in "pentagon"?', 'Five', 100),
('WORDS_MEANING', 'What does the root "oct-" mean, as in "octagon"?', 'Eight', 100),
('WORDS_MEANING', 'What does the root "dec-" mean, as in "decade"?', 'Ten', 100),
('WORDS_MEANING', 'What does the root "cent-" mean, as in "century"?', 'Hundred', 100),
('WORDS_MEANING', 'What does the root "mill-" mean, as in "millennium"?', 'Thousand', 200),
('WORDS_MEANING', 'What does the root "sect-" mean, as in "dissect"?', 'Cut', 300),
('WORDS_MEANING', 'What does the root "form-" mean, as in "transform"?', 'Shape', 200),
('WORDS_MEANING', 'What does the root "sign-" mean, as in "signature"?', 'Mark / sign', 200),
('WORDS_MEANING', 'What does the root "nym-" mean, as in "synonym"?', 'Name / word', 300),
('WORDS_MEANING', 'What does the root "loc-" mean, as in "location"?', 'Place', 200),
('WORDS_MEANING', 'What does the root "temp-" mean, as in "temperature"?', 'Time / heat', 300),
('WORDS_MEANING', 'What does the root "vac-" mean, as in "vacant"?', 'Empty', 300),
('WORDS_MEANING', 'What does the root "clam-" or "claim-" mean, as in "exclaim"?', 'Shout / cry out', 300),
('WORDS_MEANING', 'What does the root "cogn-" mean, as in "recognize"?', 'Know', 300),
('WORDS_MEANING', 'What does "tedious" mean?', 'Long, slow, and boring', 200),
('WORDS_MEANING', 'What does "compassionate" mean?', 'Feeling sympathy for others'' suffering', 100),
('WORDS_MEANING', 'What does "cautious" mean?', 'Careful to avoid danger', 100),
('WORDS_MEANING', 'What does "curious" mean?', 'Eager to learn or know something', 100),
('WORDS_MEANING', 'What does "generous" mean?', 'Willing to give freely', 100),
('WORDS_MEANING', 'What does "humble" mean?', 'Not proud or boastful', 100),
('WORDS_MEANING', 'What does "reluctantly" mean?', 'In an unwilling manner', 200),
('WORDS_MEANING', 'What does "assemble" mean?', 'To gather together', 100),
('WORDS_MEANING', 'What does "dismantle" mean?', 'To take apart', 200),
('WORDS_MEANING', 'What does "fragile" mean?', 'Easily broken or damaged', 100),
('WORDS_MEANING', 'What does "sturdy" mean?', 'Strong and well-built', 100),
('WORDS_MEANING', 'What does "enormous" mean?', 'Extremely large', 100),
('WORDS_MEANING', 'What does "minuscule" mean?', 'Extremely small', 200),
('WORDS_MEANING', 'What does "hesitant" mean?', 'Slow to act because of uncertainty', 200),
('WORDS_MEANING', 'What does "persistent" mean?', 'Continuing firmly despite difficulty', 200),
('WORDS_MEANING', 'What does "cooperate" mean?', 'To work together', 100),
('WORDS_MEANING', 'What does "isolate" mean?', 'To set apart from others', 200),
('WORDS_MEANING', 'What does "adequate" mean?', 'Enough for a purpose', 200),
('WORDS_MEANING', 'What does "excessive" mean?', 'More than what is needed', 200),
('WORDS_MEANING', 'What does "verify" mean?', 'To confirm something is true', 200),
('WORDS_MEANING', 'What does "assume" mean?', 'To believe something without proof', 100),
('WORDS_MEANING', 'What does "predict" mean?', 'To say what will happen before it does', 100),
('WORDS_MEANING', 'What does "analyze" mean?', 'To examine something carefully', 100),
('WORDS_MEANING', 'What does "summarize" mean?', 'To give a brief statement of the main points', 100),
('WORDS_MEANING', 'What does "compare" mean?', 'To look at how things are similar', 100),
('WORDS_MEANING', 'What does "contrast" mean?', 'To look at how things are different', 100),

-- ============================================================================
-- FACTION: WORDS_LABELS -- parts of speech, sentence structure, punctuation,
-- and figurative language. Every correct answer is a grammar or rhetoric
-- category label, so this pool mixes safely too.
-- ============================================================================

('WORDS_LABELS', 'What part of speech names a person, place, thing, or idea?', 'Noun', 100),
('WORDS_LABELS', 'What part of speech describes an action or a state of being?', 'Verb', 100),
('WORDS_LABELS', 'What part of speech describes or modifies a noun?', 'Adjective', 100),
('WORDS_LABELS', 'What part of speech describes or modifies a verb, adjective, or another adverb?', 'Adverb', 200),
('WORDS_LABELS', 'What part of speech takes the place of a noun?', 'Pronoun', 100),
('WORDS_LABELS', 'What part of speech shows a relationship between a noun and other words in a sentence, like "under" or "beside"?', 'Preposition', 200),
('WORDS_LABELS', 'What part of speech joins words, phrases, or clauses together, like "and" or "but"?', 'Conjunction', 200),
('WORDS_LABELS', 'What part of speech expresses strong or sudden emotion, like "Wow!"?', 'Interjection', 200),
('WORDS_LABELS', 'In the sentence "The dog ran quickly," what part of speech is "quickly"?', 'Adverb', 200),
('WORDS_LABELS', 'In the sentence "She is very happy," what part of speech is "happy"?', 'Adjective', 100),
('WORDS_LABELS', 'In the sentence "The cat sat on the mat," what part of speech is "sat"?', 'Verb', 100),
('WORDS_LABELS', 'In the sentence "The cat sat on the mat," what part of speech is "cat"?', 'Noun', 100),
('WORDS_LABELS', 'In the sentence "He ran into the room," what part of speech is "into"?', 'Preposition', 200),
('WORDS_LABELS', 'In the sentence "I like cats and dogs," what part of speech is "and"?', 'Conjunction', 200),
('WORDS_LABELS', 'In the sentence "She gave it to him," what part of speech is "him"?', 'Pronoun', 200),
('WORDS_LABELS', 'In the sentence "The bright red car sped away," what part of speech is "bright"?', 'Adjective', 200),
('WORDS_LABELS', 'What do you call a noun that names a specific person, place, or thing and starts with a capital letter?', 'Proper noun', 200),
('WORDS_LABELS', 'What do you call a general, non-specific noun, like "city" or "dog"?', 'Common noun', 100),
('WORDS_LABELS', 'What do you call a noun that names something you cannot touch, like "happiness"?', 'Abstract noun', 300),
('WORDS_LABELS', 'What do you call a noun that names a group of people or things, like "team" or "flock"?', 'Collective noun', 300),
('WORDS_LABELS', 'What do you call a verb that shows action, like "jump" or "write"?', 'Action verb', 100),
('WORDS_LABELS', 'What do you call a verb that links the subject to more information, like "is" or "seems"?', 'Linking verb', 300),
('WORDS_LABELS', 'What punctuation mark ends a question?', 'Question mark', 100),
('WORDS_LABELS', 'What punctuation mark shows strong emotion or emphasis?', 'Exclamation point', 100),
('WORDS_LABELS', 'What punctuation mark separates items in a list?', 'Comma', 100),
('WORDS_LABELS', 'What punctuation mark shows ownership, like in "Sam''s book"?', 'Apostrophe', 200),
('WORDS_LABELS', 'What punctuation mark introduces a list or an explanation?', 'Colon', 200),
('WORDS_LABELS', 'What punctuation mark joins two related independent clauses?', 'Semicolon', 300),
('WORDS_LABELS', 'What do you call the main word or word group a sentence is about?', 'Subject', 100),
('WORDS_LABELS', 'What do you call the part of a sentence that tells what the subject does or is?', 'Predicate', 200),
('WORDS_LABELS', 'What do you call a sentence that makes a statement and ends with a period?', 'Declarative sentence', 200),
('WORDS_LABELS', 'What do you call a sentence that asks a question?', 'Interrogative sentence', 200),
('WORDS_LABELS', 'What do you call a sentence that gives a command?', 'Imperative sentence', 200),
('WORDS_LABELS', 'What do you call a sentence that shows strong emotion and ends with an exclamation point?', 'Exclamatory sentence', 200),
('WORDS_LABELS', 'What do you call a group of words with a subject and a verb that expresses a complete thought?', 'Independent clause', 300),
('WORDS_LABELS', 'What do you call two or more words that work together as a single adjective, like "well-known"?', 'Compound adjective', 300),
('WORDS_LABELS', 'What do you call the base form of a word before a prefix or suffix is added?', 'Root word', 200),
('WORDS_LABELS', 'What do you call a group of letters added to the beginning of a word to change its meaning?', 'Prefix', 100),
('WORDS_LABELS', 'What do you call a group of letters added to the end of a word to change its meaning?', 'Suffix', 100),
('WORDS_LABELS', 'What do you call two words that sound the same but have different meanings and spellings, like "sea" and "see"?', 'Homophones', 200),
('WORDS_LABELS', 'What do you call words that are spelled the same but have different meanings, like "bat" the animal and "bat" the equipment?', 'Homographs', 300),
('WORDS_LABELS', 'What do you call words that mean nearly the same thing, like "happy" and "glad"?', 'Synonyms', 100),
('WORDS_LABELS', 'What do you call words that mean the opposite of each other, like "hot" and "cold"?', 'Antonyms', 100),

('WORDS_LABELS', '"The wind whispered through the trees" is an example of what figure of speech?', 'Personification', 200),
('WORDS_LABELS', '"Life is a rollercoaster" is an example of what figure of speech?', 'Metaphor', 200),
('WORDS_LABELS', '"Busy as a bee" is an example of what figure of speech?', 'Simile', 100),
('WORDS_LABELS', '"I''ve told you a million times" is an example of what figure of speech?', 'Hyperbole', 200),
('WORDS_LABELS', '"The classroom was so quiet you could hear a pin drop" is an example of what figure of speech?', 'Hyperbole', 200),
('WORDS_LABELS', 'The repeated "s" sound in "she sells seashells" is an example of what device?', 'Alliteration', 200),
('WORDS_LABELS', 'Words that imitate sounds, like "buzz" or "crash," are an example of what device?', 'Onomatopoeia', 200),
('WORDS_LABELS', 'Saying the opposite of what you mean, often for humor, is called what?', 'Irony', 300),
('WORDS_LABELS', 'Giving human qualities to a non-human thing is called what?', 'Personification', 200),
('WORDS_LABELS', 'A comparison using "like" or "as" is called what?', 'Simile', 100),
('WORDS_LABELS', 'A comparison that says one thing IS another, without using "like" or "as," is called what?', 'Metaphor', 200),
('WORDS_LABELS', 'An exaggeration used for effect, not meant to be taken literally, is called what?', 'Hyperbole', 200),
('WORDS_LABELS', 'A phrase whose meaning isn''t obvious from its individual words, like "it''s raining cats and dogs," is called what?', 'Idiom', 200),
('WORDS_LABELS', 'The repetition of vowel sounds within nearby words, like in "hear the mellow wedding bells," is called what?', 'Assonance', 300),
('WORDS_LABELS', 'A short, memorable saying that expresses a common truth, like "the early bird catches the worm," is called what?', 'Proverb', 300),

-- ============================================================================
-- FACTION: SCIENCE_PHYSICAL -- states of matter, simple machines, forces,
-- energy, light, and electricity.
-- ============================================================================

('SCIENCE_PHYSICAL', 'What state of matter has a fixed shape and a fixed volume?', 'Solid', 100),
('SCIENCE_PHYSICAL', 'What state of matter has a fixed volume but takes the shape of its container?', 'Liquid', 100),
('SCIENCE_PHYSICAL', 'What state of matter has no fixed shape and no fixed volume?', 'Gas', 100),
('SCIENCE_PHYSICAL', 'What state of matter is an ionized gas, sometimes called the "fourth state of matter"?', 'Plasma', 300),
('SCIENCE_PHYSICAL', 'What is it called when a solid changes directly into a gas, skipping the liquid stage?', 'Sublimation', 300),
('SCIENCE_PHYSICAL', 'What is it called when a liquid changes into a gas?', 'Evaporation', 200),
('SCIENCE_PHYSICAL', 'What is it called when a gas changes into a liquid?', 'Condensation', 200),
('SCIENCE_PHYSICAL', 'What is it called when a liquid changes into a solid?', 'Freezing', 100),
('SCIENCE_PHYSICAL', 'What is it called when a solid changes into a liquid?', 'Melting', 100),
('SCIENCE_PHYSICAL', 'What simple machine is a stick used to pry or lift something?', 'Lever', 200),
('SCIENCE_PHYSICAL', 'What simple machine is a slanted surface used to raise objects, like a ramp?', 'Inclined plane', 200),
('SCIENCE_PHYSICAL', 'What simple machine is a wheel with a rope or chain wrapped around it, used to lift objects?', 'Pulley', 200),
('SCIENCE_PHYSICAL', 'What simple machine is a rotating shaft attached to a wheel, like a doorknob?', 'Wheel and axle', 300),
('SCIENCE_PHYSICAL', 'What simple machine is a spiral inclined plane, like on a jar lid?', 'Screw', 200),
('SCIENCE_PHYSICAL', 'What simple machine has two sloped sides joined at a point, used for cutting or splitting?', 'Wedge', 200),
('SCIENCE_PHYSICAL', 'What force pulls objects toward the center of the Earth?', 'Gravity', 100),
('SCIENCE_PHYSICAL', 'What force opposes motion between two surfaces touching each other?', 'Friction', 200),
('SCIENCE_PHYSICAL', 'What do we call energy in motion?', 'Kinetic energy', 200),
('SCIENCE_PHYSICAL', 'What do we call stored energy that has the potential to do work?', 'Potential energy', 200),
('SCIENCE_PHYSICAL', 'What do we call the amount of matter in an object?', 'Mass', 200),
('SCIENCE_PHYSICAL', 'What do we call the force that pulls certain metals toward a magnet?', 'Magnetism', 100),
('SCIENCE_PHYSICAL', 'What do we call a push or a pull on an object?', 'Force', 100),
('SCIENCE_PHYSICAL', 'What is the study of matter and energy called?', 'Physics', 200),
('SCIENCE_PHYSICAL', 'What do we call an object''s resistance to a change in its motion?', 'Inertia', 300),
('SCIENCE_PHYSICAL', 'What kind of energy comes directly from the Sun?', 'Solar energy', 100),
('SCIENCE_PHYSICAL', 'What do we call a material that allows electricity to flow through it easily, like copper?', 'Conductor', 200),
('SCIENCE_PHYSICAL', 'What do we call a material that does not allow electricity to flow through it easily, like rubber?', 'Insulator', 200),
('SCIENCE_PHYSICAL', 'What is the bending of light as it passes from one material into another, like into water, called?', 'Refraction', 300),
('SCIENCE_PHYSICAL', 'What is the bouncing of light or sound off a surface called?', 'Reflection', 200),
('SCIENCE_PHYSICAL', 'What do we call a material that lets light pass through it clearly, like glass?', 'Transparent', 100),
('SCIENCE_PHYSICAL', 'What do we call a material that blocks light completely, like wood?', 'Opaque', 200),
('SCIENCE_PHYSICAL', 'What is the chemical symbol for water?', 'H2O', 100),
('SCIENCE_PHYSICAL', 'What is the process by which heat moves through a solid material called?', 'Conduction', 300),

-- ============================================================================
-- FACTION: SCIENCE_LIFE -- body systems, plants, food chains/ecosystems, and
-- animal facts.
-- ============================================================================

('SCIENCE_LIFE', 'What organ pumps blood through the body?', 'Heart', 100),
('SCIENCE_LIFE', 'What organ do humans use to breathe?', 'Lungs', 100),
('SCIENCE_LIFE', 'What organ is the control center of the nervous system?', 'Brain', 100),
('SCIENCE_LIFE', 'What is the largest organ in the human body?', 'Skin', 200),
('SCIENCE_LIFE', 'What organ filters waste out of the blood and produces urine?', 'Kidney', 200),
('SCIENCE_LIFE', 'What organ produces bile to help digest fat?', 'Liver', 300),
('SCIENCE_LIFE', 'What system in the body is made up of bones?', 'Skeletal system', 100),
('SCIENCE_LIFE', 'What system in the body is made up of muscles?', 'Muscular system', 100),
('SCIENCE_LIFE', 'What system carries blood throughout the body?', 'Circulatory system', 200),
('SCIENCE_LIFE', 'What system breaks down food so the body can use it?', 'Digestive system', 100),
('SCIENCE_LIFE', 'What system helps the body breathe?', 'Respiratory system', 200),
('SCIENCE_LIFE', 'What system sends signals between the brain and the rest of the body?', 'Nervous system', 200),
('SCIENCE_LIFE', 'What do we call the smallest unit of life, the building block of all living things?', 'Cell', 100),
('SCIENCE_LIFE', 'What part of a cell contains its genetic material, or DNA?', 'Nucleus', 200),
('SCIENCE_LIFE', 'What process do plants use to make their own food using sunlight?', 'Photosynthesis', 200),
('SCIENCE_LIFE', 'What gas do plants absorb from the air during photosynthesis?', 'Carbon dioxide', 200),
('SCIENCE_LIFE', 'What gas do plants release into the air during photosynthesis?', 'Oxygen', 100),
('SCIENCE_LIFE', 'What part of a plant absorbs water and nutrients from the soil?', 'Roots', 100),
('SCIENCE_LIFE', 'What part of a plant conducts water from the roots up to the leaves?', 'Stem', 100),
('SCIENCE_LIFE', 'What part of a plant makes seeds and often attracts pollinators?', 'Flower', 100),
('SCIENCE_LIFE', 'What green pigment in plants absorbs sunlight for photosynthesis?', 'Chlorophyll', 200),
('SCIENCE_LIFE', 'What do we call a plant''s growth in response to light?', 'Phototropism', 300),
('SCIENCE_LIFE', 'What do we call an organism that makes its own food, like a plant?', 'Producer', 200),
('SCIENCE_LIFE', 'What do we call an organism that eats other organisms for energy?', 'Consumer', 200),
('SCIENCE_LIFE', 'What do we call an animal that only eats plants?', 'Herbivore', 100),
('SCIENCE_LIFE', 'What do we call an animal that only eats meat?', 'Carnivore', 100),
('SCIENCE_LIFE', 'What do we call an animal that eats both plants and meat?', 'Omnivore', 100),
('SCIENCE_LIFE', 'What do we call an organism that breaks down dead plants and animals?', 'Decomposer', 300),
('SCIENCE_LIFE', 'What do we call the natural place where an organism lives?', 'Habitat', 100),
('SCIENCE_LIFE', 'What do we call all the living and non-living things in an area, interacting together?', 'Ecosystem', 200),
('SCIENCE_LIFE', 'What do you call a baby kangaroo?', 'Joey', 100),
('SCIENCE_LIFE', 'What do you call a baby dog?', 'Puppy', 100),
('SCIENCE_LIFE', 'What do you call a baby cat?', 'Kitten', 100),
('SCIENCE_LIFE', 'What do you call a baby cow?', 'Calf', 100),
('SCIENCE_LIFE', 'What do you call a baby horse?', 'Foal', 200),
('SCIENCE_LIFE', 'What do you call a baby frog?', 'Tadpole', 100),
('SCIENCE_LIFE', 'What do you call a baby sheep?', 'Lamb', 100),
('SCIENCE_LIFE', 'What do you call a baby bear?', 'Cub', 100),
('SCIENCE_LIFE', 'What do you call a group of lions?', 'Pride', 200),
('SCIENCE_LIFE', 'What do you call a group of wolves?', 'Pack', 100),
('SCIENCE_LIFE', 'What do you call a group of fish?', 'School', 100),
('SCIENCE_LIFE', 'What do you call a group of crows?', 'Murder', 300),
('SCIENCE_LIFE', 'What do you call a group of geese on the ground?', 'Gaggle', 300),
('SCIENCE_LIFE', 'What is the fastest land animal in the world?', 'Cheetah', 100),
('SCIENCE_LIFE', 'What is the largest animal on Earth?', 'Blue whale', 100),
('SCIENCE_LIFE', 'What is the tallest animal on Earth?', 'Giraffe', 100),
('SCIENCE_LIFE', 'What is the largest land animal on Earth?', 'African elephant', 200),
('SCIENCE_LIFE', 'What do we call an animal that is active mainly at night?', 'Nocturnal', 200),
('SCIENCE_LIFE', 'What do we call the deep winter sleep some animals go through?', 'Hibernation', 100),
('SCIENCE_LIFE', 'What do you call an animal with a backbone?', 'Vertebrate', 200),
('SCIENCE_LIFE', 'What do you call an animal without a backbone?', 'Invertebrate', 200),
('SCIENCE_LIFE', 'What do we call the process of a caterpillar transforming into a butterfly?', 'Metamorphosis', 200),
('SCIENCE_LIFE', 'What do we call an animal, like a frog, that can live both in water and on land?', 'Amphibian', 200),
('SCIENCE_LIFE', 'What do we call a cold-blooded animal with dry, scaly skin, like a snake or lizard?', 'Reptile', 100),
('SCIENCE_LIFE', 'What do we call a warm-blooded animal that has fur or hair and feeds its young milk?', 'Mammal', 100),
('SCIENCE_LIFE', 'What do we call an animal that lays eggs and has feathers?', 'Bird', 100),
('SCIENCE_LIFE', 'What is a young butterfly or moth called before it forms a chrysalis?', 'Caterpillar', 100),

-- ============================================================================
-- FACTION: SCIENCE_EARTH_SPACE -- the solar system, rocks, weather, and the
-- structure of the Earth.
-- ============================================================================

('SCIENCE_EARTH_SPACE', 'What is the closest planet to the Sun?', 'Mercury', 100),
('SCIENCE_EARTH_SPACE', 'What is the largest planet in our solar system?', 'Jupiter', 100),
('SCIENCE_EARTH_SPACE', 'What is the smallest planet in our solar system?', 'Mercury', 200),
('SCIENCE_EARTH_SPACE', 'Which planet is known as the Red Planet?', 'Mars', 100),
('SCIENCE_EARTH_SPACE', 'Which planet is best known for its dramatic ring system?', 'Saturn', 100),
('SCIENCE_EARTH_SPACE', 'What is the closest star to Earth?', 'The Sun', 100),
('SCIENCE_EARTH_SPACE', 'What do we call the path a planet takes around the Sun?', 'Orbit', 100),
('SCIENCE_EARTH_SPACE', 'What is Earth''s only natural satellite called?', 'The Moon', 100),
('SCIENCE_EARTH_SPACE', 'What galaxy is Earth located in?', 'The Milky Way', 200),
('SCIENCE_EARTH_SPACE', 'What do we call a huge ball of hot, glowing gas in space, like our Sun?', 'Star', 100),
('SCIENCE_EARTH_SPACE', 'What do we call a small, rocky object that orbits the Sun but is smaller than a planet?', 'Asteroid', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the streak of light caused by a small piece of rock burning up in Earth''s atmosphere?', 'Meteor', 200),
('SCIENCE_EARTH_SPACE', 'What do we call a large chunk of ice and dust that orbits the Sun and can develop a glowing tail?', 'Comet', 200),
('SCIENCE_EARTH_SPACE', 'What layer of the Earth is the thick layer of hot, dense rock beneath the crust?', 'Mantle', 200),
('SCIENCE_EARTH_SPACE', 'What is the outermost layer of the Earth called, the one we live on?', 'Crust', 100),
('SCIENCE_EARTH_SPACE', 'What is the innermost layer of the Earth called?', 'Core', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the huge, slow-moving pieces of Earth''s crust?', 'Tectonic plates', 300),
('SCIENCE_EARTH_SPACE', 'What do we call a mountain that can erupt, releasing lava?', 'Volcano', 100),
('SCIENCE_EARTH_SPACE', 'What do we call the shaking of the ground caused by shifting tectonic plates?', 'Earthquake', 100),
('SCIENCE_EARTH_SPACE', 'What type of rock forms from cooled lava or magma?', 'Igneous rock', 200),
('SCIENCE_EARTH_SPACE', 'What type of rock forms from layers of sediment pressed together over time?', 'Sedimentary rock', 200),
('SCIENCE_EARTH_SPACE', 'What type of rock forms when heat and pressure change an existing rock?', 'Metamorphic rock', 300),
('SCIENCE_EARTH_SPACE', 'What do we call the layer of gases surrounding the Earth?', 'Atmosphere', 200),
('SCIENCE_EARTH_SPACE', 'What do we call water that falls from clouds, like rain or snow?', 'Precipitation', 200),
('SCIENCE_EARTH_SPACE', 'What instrument measures temperature?', 'Thermometer', 100),
('SCIENCE_EARTH_SPACE', 'What instrument measures wind speed?', 'Anemometer', 300),
('SCIENCE_EARTH_SPACE', 'What do we call a rotating storm with very strong winds that forms over warm ocean water?', 'Hurricane', 100),
('SCIENCE_EARTH_SPACE', 'What do we call a rapidly rotating column of air that touches both a cloud and the ground?', 'Tornado', 100),
('SCIENCE_EARTH_SPACE', 'What phase of the Moon is it when the Moon appears completely lit up?', 'Full moon', 100),
('SCIENCE_EARTH_SPACE', 'What phase of the Moon is it when the Moon isn''t visible at all?', 'New moon', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the water cycle stage where water rises into the air as vapor?', 'Evaporation', 200),
('SCIENCE_EARTH_SPACE', 'What do we call a huge, thick sheet of ice that slowly moves across land?', 'Glacier', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the imaginary line around the middle of the Earth marking 0 degrees latitude?', 'Equator', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the spinning of the Earth on its axis, which causes day and night?', 'Rotation', 200),
('SCIENCE_EARTH_SPACE', 'What do we call the path the Earth takes around the Sun once a year, which causes the seasons?', 'Revolution', 300),

-- ============================================================================
-- FACTION: SCIENCE_GEOGRAPHY_TERMS -- landform and map vocabulary (not real
-- place-name trivia, which lives in Geography/Capitals).
-- ============================================================================

('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a piece of land surrounded by water on three sides?', 'Peninsula', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a narrow strip of land connecting two larger landmasses?', 'Isthmus', 300),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a raised area of mostly flat land, higher than the land around it?', 'Plateau', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the fan-shaped land formed from sediment where a river meets the sea?', 'Delta', 300),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a large area of flat, low-lying land?', 'Plain', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a deep valley with steep sides, often carved out by a river?', 'Canyon', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a piece of land completely surrounded by water?', 'Island', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a curved body of water, part of a larger sea or ocean, partly enclosed by land?', 'Bay', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a narrow area of water connecting two larger bodies of water?', 'Strait', 300),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a large area of sea or ocean that is partly enclosed by land?', 'Gulf', 300),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the point where a river begins?', 'Source', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the point where a river flows into a larger body of water?', 'Mouth', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a large area of trees and plants that gets heavy rainfall all year?', 'Rainforest', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a dry, sandy or rocky area that receives very little rainfall?', 'Desert', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a large, flat area of land covered mainly by grasses, with few or no trees?', 'Grassland', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a wet, low-lying area of land, often covered in shallow water?', 'Wetland', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a huge, thick sheet of ice that covers a large area of land?', 'Glacier', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the imaginary horizontal line marking 0 degrees latitude, circling the middle of the Earth?', 'Equator', 200),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the imaginary vertical line marking 0 degrees longitude, running through Greenwich, England?', 'Prime Meridian', 300),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the very top of a mountain?', 'Summit', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the point exactly opposite the equator at the top of the globe?', 'North Pole', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call the point exactly opposite the equator at the bottom of the globe?', 'South Pole', 100),
('SCIENCE_GEOGRAPHY_TERMS', 'What do we call a small stream that flows into a larger river?', 'Tributary', 300)

) AS v(faction, question_text, correct_answer, points);
