-- profiler_questions_seed.sql
-- Creates the Profiler question table and seeds a starter pool of 65 questions.
--
-- SAFE TO RE-RUN: the table is only created if it doesn't exist yet, and every
-- insert skips a question whose exact text is already in the table. Running it
-- twice adds nothing the second time.
--
-- How Profiler uses this table:
--   * Each round, everyone privately picks one option on their phone.
--   * The TV then shows ONE answer someone gave ("2 of you said: Gentle truth")
--     and everyone guesses who said it.
--   * option_a and option_b are required. option_c through option_g are
--     optional -- leave them NULL for a question with fewer choices (2 to 7).
--   * intensity: 1 = light and silly, 2 = says something about you,
--                3 = deeper (moral / metaphysical). The game mixes them so it
--                never stays heavy for long.
--   * active = false hides a question without deleting it.
--
-- THE CONTENT RULE: every option must be one a person would comfortably own out
-- loud, in front of family, on the TV. No confessions, no "wrong" answers.
-- Off-limits topics: politics, religion as identity, sex/dating, bodies/weight,
-- money amounts, health, family conflict, and questions about people in the room.

CREATE TABLE IF NOT EXISTS profiler_questions (
    id            SERIAL PRIMARY KEY,
    question_text TEXT NOT NULL UNIQUE,
    category      TEXT NOT NULL,          -- HYPOTHETICAL / PERSONALITY / VALUES / LIGHT / BIG_QUESTIONS
    intensity     SMALLINT NOT NULL CHECK (intensity BETWEEN 1 AND 3),
    option_a      TEXT NOT NULL,
    option_b      TEXT NOT NULL,
    option_c      TEXT,
    option_d      TEXT,
    option_e      TEXT,
    option_f      TEXT,
    option_g      TEXT,
    active        BOOLEAN NOT NULL DEFAULT true
);

-- ---------- LIGHT (intensity 1) ----------
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Is a hot dog a sandwich?', 'LIGHT', 1, 'Yes', 'No', 'It''s its own thing', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Toilet paper goes...', 'LIGHT', 1, 'Over', 'Under', 'I''ve never noticed', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Pick a superpower.', 'LIGHT', 1, 'Flying', 'Invisibility', 'Reading minds', 'Time travel', 'Teleporting', 'Super strength', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Cereal: milk first or cereal first?', 'LIGHT', 1, 'Cereal first', 'Milk first', 'Dry, no milk', 'I don''t eat cereal', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Best pizza topping?', 'LIGHT', 1, 'Pepperoni', 'Pineapple', 'Mushrooms', 'Sausage', 'Just cheese', 'Everything', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather fight one horse-sized duck or a hundred duck-sized horses?', 'LIGHT', 1, 'One horse-sized duck', 'A hundred duck-sized horses', 'I''d negotiate', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Your phone battery hits 20%. You feel...', 'LIGHT', 1, 'Totally fine', 'Mild concern', 'Full panic', 'Mine''s always at 20%', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Best season?', 'LIGHT', 1, 'Spring', 'Summer', 'Fall', 'Winter', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Which animal would you be?', 'LIGHT', 1, 'Dog', 'Cat', 'Owl', 'Dolphin', 'Sloth', 'Eagle', 'Otter') ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Sweet or salty snack?', 'LIGHT', 1, 'Sweet', 'Salty', 'Both at once', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Socks in bed?', 'LIGHT', 1, 'Always', 'Never', 'Only when it''s cold', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Your dream vacation is...', 'LIGHT', 1, 'A beach', 'The mountains', 'A big city', 'A theme park', 'A road trip', 'Staying home', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather explore space or the deep ocean?', 'LIGHT', 1, 'Space', 'Deep ocean', 'Neither, thanks', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Movie night: what are you picking?', 'LIGHT', 1, 'Comedy', 'Action', 'Horror', 'Animated', 'Documentary', 'Romance', 'Sci-fi') ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather always be 10 minutes early or 10 minutes late?', 'LIGHT', 1, '10 minutes early', '10 minutes late', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Breakfast for dinner?', 'LIGHT', 1, 'Best idea ever', 'Fine once in a while', 'Dinner should be dinner', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('A zombie apocalypse starts. Your role?', 'LIGHT', 1, 'The leader', 'The medic', 'The builder', 'The scout', 'The comic relief', 'First to go', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather talk to animals or speak every human language?', 'LIGHT', 1, 'Talk to animals', 'Every human language', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Best way to eat a cookie?', 'LIGHT', 1, 'Dunked in milk', 'Warm from the oven', 'Raw dough', 'Straight from the bag', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather live in a treehouse or a houseboat?', 'LIGHT', 1, 'Treehouse', 'Houseboat', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;

-- ---------- PERSONALITY (intensity 2) ----------
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('At a party, you''re usually...', 'PERSONALITY', 2, 'In the kitchen', 'In the center of the room', 'With the pets', 'Planning my exit', 'Running the music', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Packing for a trip happens...', 'PERSONALITY', 2, 'A week before', 'The night before', 'An hour before', 'In the car', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('You''re lost. You...', 'PERSONALITY', 2, 'Ask someone', 'Check my phone', 'Keep going, it''ll work out', 'Hand the problem to someone else', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('How do you recharge after a long week?', 'PERSONALITY', 2, 'Alone time', 'Out with friends', 'Outdoors', 'A big project', 'Sleep. Lots of sleep.', 'Screens', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Your desk or workspace is...', 'PERSONALITY', 2, 'Spotless', 'Organized chaos', 'Pure chaos', 'What desk?', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Morning person or night owl?', 'PERSONALITY', 2, 'Morning person', 'Night owl', 'Neither, I''m always tired', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('When you play a game, you mostly want to...', 'PERSONALITY', 2, 'Win', 'Have fun', 'Make people laugh', 'Learn the rules perfectly', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('New gadget arrives. You...', 'PERSONALITY', 2, 'Read the manual first', 'Figure it out as I go', 'Watch a video', 'Hand it to someone else', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('You get unexpected free time. You...', 'PERSONALITY', 2, 'Nap', 'Clean something', 'Call someone', 'Start a hobby project', 'Go outside', 'Scroll', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be the smartest, funniest, kindest, or bravest person in the room?', 'PERSONALITY', 2, 'Smartest', 'Funniest', 'Kindest', 'Bravest', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Group project: what''s your role?', 'PERSONALITY', 2, 'The planner', 'The doer', 'The idea person', 'The cheerleader', 'The one who finishes it at 2 a.m.', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('How do you handle a surprise party thrown for you?', 'PERSONALITY', 2, 'Love it', 'Grateful but overwhelmed', 'I''d rather know ahead', 'I''d figure it out early', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Which compliment means the most to you?', 'PERSONALITY', 2, 'You''re so smart', 'You''re so funny', 'You''re so kind', 'You''re so creative', 'You''re so dependable', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('In an argument, you usually...', 'PERSONALITY', 2, 'Stand my ground', 'Look for middle ground', 'Go quiet and think', 'Make a joke', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather plan every detail of a trip or wing it?', 'PERSONALITY', 2, 'Plan every detail', 'Plan a little', 'Wing it completely', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Which would you rather master?', 'PERSONALITY', 2, 'An instrument', 'A language', 'Cooking', 'A sport', 'Drawing', 'Coding', NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Your ideal Saturday starts with...', 'PERSONALITY', 2, 'Sleeping in', 'An early workout', 'A big breakfast', 'Chores out of the way', 'No plans at all', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('How many browser tabs do you have open right now?', 'PERSONALITY', 2, 'One or two', 'Under ten', 'Dozens', 'I''m afraid to look', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;

-- ---------- VALUES (intensity 2) ----------
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('A friend''s new haircut is bad, and they ask what you think.', 'VALUES', 2, 'Kind fib', 'Gentle truth', 'Change the subject', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('What matters most in a job?', 'VALUES', 2, 'The pay', 'The meaning', 'The people', 'The free time', 'Learning new things', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be respected, liked, or left alone?', 'VALUES', 2, 'Respected', 'Liked', 'Left alone', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather have more time or more energy?', 'VALUES', 2, 'More time', 'More energy', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be famous or anonymous?', 'VALUES', 2, 'Famous', 'Anonymous', 'Famous, but only locally', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Which would you rather leave behind?', 'VALUES', 2, 'A great invention', 'A great book', 'A beautiful building', 'A big family', 'A kinder town', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be a big fish in a small pond or a small fish in a big pond?', 'VALUES', 2, 'Big fish, small pond', 'Small fish, big pond', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be really good at one thing or pretty good at everything?', 'VALUES', 2, 'Really good at one thing', 'Pretty good at everything', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('A stranger''s dog gets loose on a busy street. You...', 'VALUES', 2, 'Chase it down', 'Call out to the owner', 'Stop traffic', 'Grab a snack to lure it', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather have a quiet life you love or an exciting life that''s exhausting?', 'VALUES', 2, 'Quiet life I love', 'Exciting and exhausting', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;

-- ---------- HYPOTHETICAL / BIG QUESTIONS (intensity 3) ----------
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you want to know the date you''ll die?', 'BIG_QUESTIONS', 3, 'Yes', 'No', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('A teleporter destroys you and rebuilds you perfectly at your destination. Would you use it?', 'BIG_QUESTIONS', 3, 'Every day', 'Only in an emergency', 'Never', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('You can live forever -- but only you. Do you take it?', 'BIG_QUESTIONS', 3, 'Yes', 'No', 'Only if I could quit later', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Does everything happen for a reason?', 'BIG_QUESTIONS', 3, 'Yes', 'Some things do', 'No, it''s mostly chance', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('You can relive one year of your life, knowing what you know now. Which?', 'HYPOTHETICAL', 3, 'Childhood', 'Teens', 'Twenties', 'A recent year', 'No thanks', NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Do you believe in ghosts?', 'BIG_QUESTIONS', 3, 'Yes', 'No', 'I want to', 'I''m not ruling it out', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Is there intelligent life somewhere else in the universe?', 'BIG_QUESTIONS', 3, 'Definitely', 'Probably', 'Probably not', 'We''re it', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather see 100 years into the future or 100 years into the past?', 'HYPOTHETICAL', 3, 'The future', 'The past', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you want to know what other people really think of you?', 'BIG_QUESTIONS', 3, 'Yes, all of it', 'Only the good stuff', 'No, never', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('If you could erase one memory, would you?', 'BIG_QUESTIONS', 3, 'Yes', 'No -- even the bad ones made me', 'I''d have to think about it', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('A one-way ticket to start the first colony on Mars. Do you go?', 'HYPOTHETICAL', 3, 'Yes, immediately', 'Only with my family', 'No way', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather be able to change the past or see the future?', 'HYPOTHETICAL', 3, 'Change the past', 'See the future', 'Neither', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Is it better to be lucky or good?', 'BIG_QUESTIONS', 3, 'Lucky', 'Good', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you take a pill that meant you never needed to sleep again?', 'HYPOTHETICAL', 3, 'Yes', 'No, I love sleep', 'Only for a week to test it', NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Are people mostly good?', 'BIG_QUESTIONS', 3, 'Yes', 'Mostly, with exceptions', 'It depends on the day', 'No', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('You can meet one version of yourself. Which?', 'HYPOTHETICAL', 3, 'Me at 8', 'Me at 18', 'Me at 80', 'Me from another life path', NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
INSERT INTO profiler_questions (question_text, category, intensity, option_a, option_b, option_c, option_d, option_e, option_f, option_g) VALUES ('Would you rather know every answer or always ask the right question?', 'BIG_QUESTIONS', 3, 'Know every answer', 'Ask the right question', NULL, NULL, NULL, NULL, NULL) ON CONFLICT (question_text) DO NOTHING;
