-- Trivi-Yeah II prototype content: 5 general-knowledge categories, 20
-- questions each (4 point tiers x 5 questions), every row carrying its own
-- curated 6-answer wrong_answers pool (same mechanism as the WWII_HISTORY
-- rewrite). Namespaced under its own game_mode ('TRIVI_YEAH_II') rather than
-- the classic Trivi-Yeah's 'TRIVIA' pool, so this content is invisible to
-- the live classic mode until the new grid engine is actually built to
-- query it -- seeding content now, ahead of that build, so gameplay can be
-- tried out as soon as it exists.

DELETE FROM questions WHERE game_mode = 'TRIVI_YEAH_II';

INSERT INTO questions (question_number, game_mode, category, subcategory, faction, question_text, visual_asset, correct_answer, wrong_answers, points)
VALUES
-- SCIENCE_NATURE
(2001, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What planet is known as the Red Planet?', NULL, 'Mars', ARRAY['Venus','Jupiter','Mercury','Saturn','Neptune','Pluto'], 100),
(2002, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What gas do plants absorb from the air to make food?', NULL, 'Carbon dioxide', ARRAY['Oxygen','Nitrogen','Hydrogen','Helium','Methane','Argon'], 100),
(2003, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'How many legs does a spider have?', NULL, 'Eight', ARRAY['Six','Ten','Four','Twelve','Two','Five'], 100),
(2004, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the largest organ in the human body?', NULL, 'Skin', ARRAY['Liver','Heart','Brain','Lungs','Kidney','Stomach'], 100),
(2005, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What force pulls objects toward the Earth?', NULL, 'Gravity', ARRAY['Magnetism','Friction','Inertia','Velocity','Momentum','Pressure'], 100),
(2006, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the chemical symbol for gold?', NULL, 'Au', ARRAY['Ag','Gd','Go','Gl','Fe','Pb'], 200),
(2007, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What part of a plant primarily conducts photosynthesis?', NULL, 'Leaves', ARRAY['Roots','Stem','Flower','Seeds','Bark','Thorns'], 200),
(2008, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the hardest natural substance on Earth?', NULL, 'Diamond', ARRAY['Quartz','Granite','Steel','Obsidian','Titanium','Emerald'], 200),
(2009, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the closest star to Earth, other than the Sun?', NULL, 'Proxima Centauri', ARRAY['Alpha Centauri','Sirius','Betelgeuse','Polaris','Vega','Rigel'], 200),
(2010, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What type of animal is a Komodo dragon?', NULL, 'A lizard', ARRAY['A snake','A crocodile','A dinosaur','A turtle','An iguana','A salamander'], 200),
(2011, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is commonly called the "powerhouse of the cell"?', NULL, 'Mitochondria', ARRAY['Nucleus','Ribosome','Golgi apparatus','Chloroplast','Cytoplasm','Vacuole'], 300),
(2012, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'Approximately how fast does light travel in a vacuum?', NULL, '300,000 km per second', ARRAY['150,000 km per second','3,000 km per second','1,000,000 km per second','500,000 km per second','30,000 km per second','100,000 km per second'], 300),
(2013, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'Which blood type is known as the universal donor?', NULL, 'O negative', ARRAY['AB positive','A positive','B negative','O positive','AB negative','A negative'], 300),
(2014, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the scientific study of fungi called?', NULL, 'Mycology', ARRAY['Botany','Zoology','Entomology','Virology','Ecology','Geology'], 300),
(2015, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'Which element has the atomic number 1?', NULL, 'Hydrogen', ARRAY['Helium','Oxygen','Carbon','Nitrogen','Lithium','Boron'], 300),
(2016, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the only metal that is liquid at standard room temperature?', NULL, 'Mercury', ARRAY['Lead','Tin','Gallium','Bismuth','Zinc','Sodium'], 400),
(2017, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What is the term for an animal that is active mainly at night?', NULL, 'Nocturnal', ARRAY['Diurnal','Crepuscular','Hibernal','Migratory','Dormant','Arboreal'], 400),
(2018, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'Which gas makes up about 78% of Earth''s atmosphere?', NULL, 'Nitrogen', ARRAY['Oxygen','Carbon dioxide','Argon','Hydrogen','Helium','Methane'], 400),
(2019, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'What pH value represents a perfectly neutral substance?', NULL, '7', ARRAY['0','14','1','10','5','12'], 400),
(2020, 'TRIVI_YEAH_II', 'SCIENCE_NATURE', NULL, NULL, 'Which organ produces insulin in the human body?', NULL, 'Pancreas', ARRAY['Liver','Kidney','Spleen','Gallbladder','Thyroid','Adrenal gland'], 400),
-- MOVIES_TV
(2021, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'In "The Wizard of Oz," what color are the shoes Dorothy wears?', NULL, 'Ruby red', ARRAY['Emerald green','Golden yellow','Silver','Sapphire blue','Bronze','Pearl white'], 100),
(2022, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What is the name of the clownfish in "Finding Nemo"?', NULL, 'Nemo', ARRAY['Marlin','Dory','Bruce','Gill','Squirt','Crush'], 100),
(2023, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which superhero is also known as the "Man of Steel"?', NULL, 'Superman', ARRAY['Batman','Thor','Iron Man','The Flash','Green Lantern','Aquaman'], 100),
(2024, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What is the name of the coffee shop the friends hang out at in "Friends"?', NULL, 'Central Perk', ARRAY['The Grind','Common Grounds','Java Joe''s','The Daily Grind','Perk Place','Bean There'], 100),
(2025, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'In "Star Wars," what is the name of Luke Skywalker''s home planet?', NULL, 'Tatooine', ARRAY['Naboo','Alderaan','Hoth','Coruscant','Endor','Dagobah'], 100),
(2026, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Who directed the movie "Jaws"?', NULL, 'Steven Spielberg', ARRAY['George Lucas','Martin Scorsese','James Cameron','Ridley Scott','Francis Ford Coppola','Tim Burton'], 200),
(2027, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What is the name of the fictional African nation in "Black Panther"?', NULL, 'Wakanda', ARRAY['Zamunda','Genosha','Latveria','Sokovia','Madripoor','Attilan'], 200),
(2028, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'In "Breaking Bad," what is Walter White''s criminal alias?', NULL, 'Heisenberg', ARRAY['Saul','Jesse','Gus','Hank','Skyler','Mike'], 200),
(2029, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which actor played Jack Dawson in "Titanic"?', NULL, 'Leonardo DiCaprio', ARRAY['Brad Pitt','Matt Damon','Tom Cruise','Johnny Depp','Matthew McConaughey','Ben Affleck'], 200),
(2030, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What is the name of the wizarding school in the Harry Potter series?', NULL, 'Hogwarts', ARRAY['Durmstrang','Beauxbatons','Ilvermorny','Hogsmeade','Azkaban','Diagon'], 200),
(2031, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which movie won the Academy Award for Best Picture for 1994?', NULL, 'Forrest Gump', ARRAY['Pulp Fiction','The Shawshank Redemption','Speed','The Lion King','Dumb and Dumber','True Lies'], 300),
(2032, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Who composed the musical score for the original "Star Wars" trilogy?', NULL, 'John Williams', ARRAY['Hans Zimmer','John Barry','Alan Silvestri','Danny Elfman','Howard Shore','James Horner'], 300),
(2033, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What is the name of the AI antagonist in "2001: A Space Odyssey"?', NULL, 'HAL 9000', ARRAY['Skynet','GLaDOS','Ultron','VIKI','Ava','Samantha'], 300),
(2034, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which TV series is set in the fictional town of Hawkins, Indiana?', NULL, 'Stranger Things', ARRAY['Twin Peaks','Riverdale','Gilmore Girls','Supernatural','The X-Files','Fargo'], 300),
(2035, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Who played the Joker in "The Dark Knight" (2008)?', NULL, 'Heath Ledger', ARRAY['Jack Nicholson','Joaquin Phoenix','Jared Leto','Cesar Romero','Mark Hamill','Barry Keoghan'], 300),
(2036, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What was the first full-length cel-animated feature film ever released?', NULL, 'Snow White and the Seven Dwarfs', ARRAY['Pinocchio','Fantasia','Bambi','Cinderella','Dumbo','Steamboat Willie'], 400),
(2037, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which film is considered the first "talkie" to bring sound to Hollywood?', NULL, 'The Jazz Singer', ARRAY['Metropolis','The Birth of a Nation','Sunrise','Wings','City Lights','Nosferatu'], 400),
(2038, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Who directed "Citizen Kane"?', NULL, 'Orson Welles', ARRAY['Alfred Hitchcock','Billy Wilder','John Ford','Frank Capra','Howard Hawks','William Wyler'], 400),
(2039, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'What 1988 film extensively blended live action with animated characters, including Roger Rabbit?', NULL, 'Who Framed Roger Rabbit', ARRAY['Mary Poppins','Space Jam','Cool World','Pete''s Dragon','Bedknobs and Broomsticks','Enchanted'], 400),
(2040, 'TRIVI_YEAH_II', 'MOVIES_TV', NULL, NULL, 'Which actress holds the record for the most competitive (non-honorary) acting Academy Awards?', NULL, 'Katharine Hepburn', ARRAY['Meryl Streep','Bette Davis','Ingrid Bergman','Frances McDormand','Jane Fonda','Elizabeth Taylor'], 400),
-- MUSIC
(2041, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'How many strings does a standard guitar have?', NULL, 'Six', ARRAY['Four','Five','Seven','Eight','Twelve','Three'], 100),
(2042, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which instrument has black and white keys?', NULL, 'Piano', ARRAY['Violin','Trumpet','Drums','Flute','Guitar','Saxophone'], 100),
(2043, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Who is known as the "King of Pop"?', NULL, 'Michael Jackson', ARRAY['Elvis Presley','Prince','Justin Timberlake','James Brown','Usher','Bruno Mars'], 100),
(2044, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'What term describes a group of musicians who perform together?', NULL, 'A band', ARRAY['A soloist','An orchestra pit','A chorus line','A label','A chart','A session'], 100),
(2045, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which pop star released the album "1989"?', NULL, 'Taylor Swift', ARRAY['Katy Perry','Ariana Grande','Beyoncé','Adele','Rihanna','Lady Gaga'], 100),
(2046, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which British band sang "Hey Jude"?', NULL, 'The Beatles', ARRAY['The Rolling Stones','Pink Floyd','Queen','The Who','Led Zeppelin','The Kinks'], 200),
(2047, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'What is the term for singing without any instrumental accompaniment?', NULL, 'A cappella', ARRAY['Acoustic','Karaoke','Falsetto','Harmony','Staccato','Vibrato'], 200),
(2048, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which artist released the album and song "Thriller"?', NULL, 'Michael Jackson', ARRAY['Prince','Stevie Wonder','Lionel Richie','Smokey Robinson','Marvin Gaye','Diana Ross'], 200),
(2049, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which genre of music originated in Jamaica?', NULL, 'Reggae', ARRAY['Salsa','Samba','Calypso','Ska','Merengue','Bachata'], 200),
(2050, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which composer continued writing music after going almost completely deaf?', NULL, 'Ludwig van Beethoven', ARRAY['Wolfgang Amadeus Mozart','Johann Sebastian Bach','Franz Schubert','Johannes Brahms','Frederic Chopin','Joseph Haydn'], 200),
(2051, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Mick Jagger and Keith Richards are members of which rock band?', NULL, 'The Rolling Stones', ARRAY['The Beatles','The Who','Led Zeppelin','Aerosmith','The Eagles','Fleetwood Mac'], 300),
(2052, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'What is the highest female singing voice classification?', NULL, 'Soprano', ARRAY['Alto','Mezzo-soprano','Contralto','Tenor','Baritone','Bass'], 300),
(2053, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which American singer is known as "The Queen of Soul"?', NULL, 'Aretha Franklin', ARRAY['Whitney Houston','Diana Ross','Tina Turner','Etta James','Gladys Knight','Patti LaBelle'], 300),
(2054, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which Detroit record label did Berry Gordy found?', NULL, 'Motown', ARRAY['Atlantic Records','Capitol Records','Columbia Records','RCA','Stax Records','Def Jam'], 300),
(2055, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which classical composer wrote "The Four Seasons"?', NULL, 'Antonio Vivaldi', ARRAY['Johann Sebastian Bach','George Frideric Handel','Franz Joseph Haydn','Wolfgang Amadeus Mozart','Claudio Monteverdi','Arcangelo Corelli'], 300),
(2056, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which 1969 music festival took place on a dairy farm in Bethel, New York?', NULL, 'Woodstock', ARRAY['Monterey Pop Festival','Altamont','Isle of Wight Festival','Live Aid','Lollapalooza','Coachella'], 400),
(2057, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Who composed the opera "The Magic Flute"?', NULL, 'Wolfgang Amadeus Mozart', ARRAY['Ludwig van Beethoven','Giuseppe Verdi','Richard Wagner','Giacomo Puccini','Franz Schubert','Johann Strauss II'], 400),
(2058, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which instrument is Yo-Yo Ma famous for playing?', NULL, 'Cello', ARRAY['Violin','Viola','Double bass','Piano','Harp','Clarinet'], 400),
(2059, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'What was the best-selling album of the 1980s worldwide?', NULL, 'Thriller', ARRAY['Back in Black','The Dark Side of the Moon','Born in the U.S.A.','Appetite for Destruction','Purple Rain','Bad'], 400),
(2060, 'TRIVI_YEAH_II', 'MUSIC', NULL, NULL, 'Which jazz trumpeter and singer was nicknamed "Satchmo"?', NULL, 'Louis Armstrong', ARRAY['Miles Davis','Dizzy Gillespie','Duke Ellington','Chet Baker','Nat King Cole','Charlie Parker'], 400),
-- SPORTS
(2061, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'How many players are on a standard soccer team on the field at once?', NULL, 'Eleven', ARRAY['Ten','Twelve','Nine','Thirteen','Eight','Seven'], 100),
(2062, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'In basketball, how many points is a standard field goal worth?', NULL, 'Two', ARRAY['One','Three','Four','Five','Six','Ten'], 100),
(2063, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'What sport is played at the Wimbledon championships?', NULL, 'Tennis', ARRAY['Golf','Cricket','Rugby','Badminton','Squash','Table tennis'], 100),
(2064, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'How many holes are played in a standard round of golf?', NULL, 'Eighteen', ARRAY['Nine','Twelve','Twenty','Sixteen','Twenty-four','Fifteen'], 100),
(2065, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'What shape is the infield of a baseball field?', NULL, 'A diamond', ARRAY['A square','A circle','A triangle','A rectangle','A pentagon','An oval'], 100),
(2066, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which country has won the most FIFA World Cups?', NULL, 'Brazil', ARRAY['Germany','Italy','Argentina','France','Spain','Uruguay'], 200),
(2067, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'In which sport would a player perform a "slam dunk"?', NULL, 'Basketball', ARRAY['Volleyball','Tennis','Football','Baseball','Hockey','Rugby'], 200),
(2068, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'How many interlocking rings are on the Olympic flag?', NULL, 'Five', ARRAY['Four','Six','Seven','Three','Eight','Nine'], 200),
(2069, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'What is widely considered the national sport of Japan?', NULL, 'Sumo wrestling', ARRAY['Judo','Karate','Baseball','Kendo','Table tennis','Volleyball'], 200),
(2070, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'In American football, how many points is a touchdown worth?', NULL, 'Six', ARRAY['Three','Seven','Two','Five','Eight','Ten'], 200),
(2071, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which men''s tennis player holds the record for the most Grand Slam singles titles?', NULL, 'Novak Djokovic', ARRAY['Roger Federer','Rafael Nadal','Pete Sampras','Andre Agassi','Bjorn Borg','Rod Laver'], 300),
(2072, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which country hosted the first modern Olympic Games in 1896?', NULL, 'Greece', ARRAY['France','United States','England','Italy','Germany','Switzerland'], 300),
(2073, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which boxer, born Cassius Clay, was known as "The Greatest"?', NULL, 'Muhammad Ali', ARRAY['Mike Tyson','Joe Frazier','George Foreman','Sugar Ray Robinson','Floyd Mayweather','Evander Holyfield'], 300),
(2074, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'In cricket, how many players are on each team?', NULL, 'Eleven', ARRAY['Ten','Twelve','Nine','Thirteen','Eight','Fifteen'], 300),
(2075, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which country is credited with inventing the sport of golf?', NULL, 'Scotland', ARRAY['England','Ireland','Wales','Netherlands','United States','France'], 300),
(2076, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Who holds MLB''s officially recognized single-season home run record, with 73 in 2001?', NULL, 'Barry Bonds', ARRAY['Babe Ruth','Mark McGwire','Sammy Sosa','Roger Maris','Hank Aaron','Aaron Judge'], 400),
(2077, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which country won the first-ever FIFA World Cup in 1930?', NULL, 'Uruguay', ARRAY['Brazil','Argentina','Italy','France','England','Germany'], 400),
(2078, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'What is the maximum possible break in a single visit in snooker?', NULL, '147', ARRAY['155','100','180','200','50','120'], 400),
(2079, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'Which racehorse won the US Triple Crown in 1973 by a record margin?', NULL, 'Secretariat', ARRAY['Seabiscuit','Man o'' War','American Pharoah','Citation','War Admiral','Affirmed'], 400),
(2080, 'TRIVI_YEAH_II', 'SPORTS', NULL, NULL, 'In what year were the first Winter Olympic Games held?', NULL, '1924', ARRAY['1920','1928','1900','1932','1912','1936'], 400),
-- WORLD_HISTORY
(2081, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Who was the first President of the United States?', NULL, 'George Washington', ARRAY['Thomas Jefferson','John Adams','Abraham Lincoln','Benjamin Franklin','James Madison','Alexander Hamilton'], 100),
(2082, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'In what year did World War I begin?', NULL, '1914', ARRAY['1912','1916','1918','1920','1910','1939'], 100),
(2083, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which ancient civilization built the pyramids at Giza?', NULL, 'The Egyptians', ARRAY['The Romans','The Greeks','The Mayans','The Aztecs','The Babylonians','The Persians'], 100),
(2084, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which explorer sailed to the Americas in 1492?', NULL, 'Christopher Columbus', ARRAY['Vasco da Gama','Ferdinand Magellan','Marco Polo','Amerigo Vespucci','Henry Hudson','John Cabot'], 100),
(2085, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which wall divided a European city from 1961 to 1989?', NULL, 'The Berlin Wall', ARRAY['The Great Wall','Hadrian''s Wall','The Iron Curtain','The Maginot Line','The Atlantic Wall','The Siegfried Line'], 100),
(2086, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which Queen reigned over England for over 60 years during the Victorian era?', NULL, 'Queen Victoria', ARRAY['Queen Elizabeth I','Queen Elizabeth II','Queen Anne','Queen Mary I','Queen Charlotte','Queen Caroline'], 200),
(2087, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which empire was ruled by Julius Caesar?', NULL, 'The Roman Empire', ARRAY['The Greek Empire','The Persian Empire','The Egyptian Empire','The Byzantine Empire','The Ottoman Empire','The Macedonian Empire'], 200),
(2088, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'What document did the American colonies sign in 1776 to declare independence?', NULL, 'The Declaration of Independence', ARRAY['The Constitution','The Bill of Rights','The Magna Carta','The Articles of Confederation','The Emancipation Proclamation','The Mayflower Compact'], 200),
(2089, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which country was first to send a human into space?', NULL, 'The Soviet Union', ARRAY['The United States','Germany','China','France','United Kingdom','Japan'], 200),
(2090, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Who was the leader of Nazi Germany during World War II?', NULL, 'Adolf Hitler', ARRAY['Benito Mussolini','Joseph Stalin','Hermann Göring','Heinrich Himmler','Joseph Goebbels','Erwin Rommel'], 200),
(2091, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'The Magna Carta was signed in which country in 1215?', NULL, 'England', ARRAY['France','Scotland','Spain','Ireland','Germany','Italy'], 300),
(2092, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which empire was ruled by Genghis Khan?', NULL, 'The Mongol Empire', ARRAY['The Ottoman Empire','The Persian Empire','The Chinese Empire','The Russian Empire','The Tang Dynasty','The Byzantine Empire'], 300),
(2093, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'What was the name of the ship that carried the Pilgrims to America in 1620?', NULL, 'The Mayflower', ARRAY['The Santa Maria','The Nina','The Pinta','The Endeavour','The Beagle','The Speedwell'], 300),
(2094, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which revolution began in France in 1789?', NULL, 'The French Revolution', ARRAY['The Industrial Revolution','The Glorious Revolution','The Russian Revolution','The American Revolution','The Bolshevik Revolution','The Haitian Revolution'], 300),
(2095, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Whose assassination in Sarajevo in 1914 triggered the start of World War I?', NULL, 'Archduke Franz Ferdinand', ARRAY['Kaiser Wilhelm II','Tsar Nicholas II','King George V','Otto von Bismarck','Emperor Franz Joseph','Woodrow Wilson'], 300),
(2096, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which ancient wonder of the world stood in the harbor of Alexandria, Egypt?', NULL, 'The Lighthouse of Alexandria', ARRAY['The Hanging Gardens','The Colossus of Rhodes','The Great Pyramid','The Temple of Artemis','The Statue of Zeus','The Mausoleum at Halicarnassus'], 400),
(2097, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'The Treaty of Versailles officially ended which war?', NULL, 'World War I', ARRAY['World War II','The Franco-Prussian War','The Napoleonic Wars','The Crimean War','The Seven Years'' War','The Spanish-American War'], 400),
(2098, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which dynasty was the last imperial dynasty of China?', NULL, 'The Qing Dynasty', ARRAY['The Ming Dynasty','The Tang Dynasty','The Han Dynasty','The Song Dynasty','The Yuan Dynasty','The Zhou Dynasty'], 400),
(2099, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'Which Byzantine Emperor is famous for codifying Roman law in the 6th century?', NULL, 'Justinian I', ARRAY['Constantine the Great','Theodosius I','Basil II','Heraclius','Diocletian','Augustus'], 400),
(2100, 'TRIVI_YEAH_II', 'WORLD_HISTORY', NULL, NULL, 'The Rosetta Stone, key to deciphering Egyptian hieroglyphs, is inscribed in how many different scripts?', NULL, 'Three', ARRAY['Two','Four','Five','One','Six','Seven'], 400);
