-- WWII_HISTORY rewrite: retires the old PERSON/PLACE/THING/EVENT/DATE x
-- ALLIED/AXIS structure (peer-pulled distractors) in favor of general-
-- knowledge questions, each carrying its own curated 6-answer wrong_answers
-- pool. 3 of the 6 are drawn at random each time the question is served, so
-- the same question can show a different (and sometimes tougher) trio of
-- foils on a replay. subcategory/faction are left NULL -- this mechanism
-- doesn't need peer grouping at all.
--
-- Requires the wrong_answers column (see the ALTER TABLE below, safe to
-- run even if it already exists).

ALTER TABLE questions ADD COLUMN IF NOT EXISTS wrong_answers TEXT[];

DELETE FROM questions WHERE category = 'WWII_HISTORY';

INSERT INTO questions (question_number, game_mode, category, subcategory, faction, question_text, visual_asset, correct_answer, wrong_answers, points)
VALUES
(1465, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'On what date did Germany invade Poland, starting World War II in Europe?', NULL, 'September 1, 1939', ARRAY['August 23, 1939','September 3, 1939','June 22, 1941','November 11, 1938','March 12, 1938','May 10, 1940'], 100),
(1466, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the code name for the Allied invasion of Normandy in June 1944?', NULL, 'Operation Overlord', ARRAY['Operation Torch','Operation Market Garden','Operation Husky','Operation Barbarossa','Operation Dynamo','Operation Cobra'], 100),
(1467, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which two Japanese cities were struck by atomic bombs in August 1945?', NULL, 'Hiroshima and Nagasaki', ARRAY['Tokyo and Osaka','Kyoto and Yokohama','Hiroshima and Kyoto','Nagasaki and Tokyo','Osaka and Nagasaki','Yokohama and Hiroshima'], 100),
(1468, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the name of the German battleship sunk by the Royal Navy in May 1941?', NULL, 'Bismarck', ARRAY['Tirpitz','Graf Spee','Scharnhorst','Gneisenau','Prinz Eugen','Admiral Hipper'], 200),
(1469, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which battle is widely considered the turning point of the war on the Eastern Front?', NULL, 'Battle of Stalingrad', ARRAY['Battle of Kursk','Battle of Moscow','Siege of Leningrad','Battle of Kiev','Battle of Berlin','Battle of Smolensk'], 200),
(1470, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'On what date did Japan attack Pearl Harbor?', NULL, 'December 7, 1941', ARRAY['December 8, 1941','November 7, 1941','January 7, 1942','December 25, 1941','October 7, 1941','December 1, 1941'], 100),
(1471, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which three countries formed the core of the Axis powers?', NULL, 'Germany, Italy, and Japan', ARRAY['Germany, Austria, and Italy','Germany, Japan, and Spain','Italy, Japan, and Romania','Germany, Hungary, and Japan','Japan, Italy, and Finland','Germany, Bulgaria, and Japan'], 100),
(1472, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Who served as British Prime Minister for most of World War II?', NULL, 'Winston Churchill', ARRAY['Neville Chamberlain','Clement Attlee','Anthony Eden','Stanley Baldwin','Lord Halifax','Harold Macmillan'], 100),
(1473, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which U.S. President led the country for most of World War II?', NULL, 'Franklin D. Roosevelt', ARRAY['Harry Truman','Herbert Hoover','Woodrow Wilson','Dwight D. Eisenhower','Calvin Coolidge','Warren Harding'], 100),
(1474, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Who was the leader of Nazi Germany during World War II?', NULL, 'Adolf Hitler', ARRAY['Heinrich Himmler','Hermann Göring','Joseph Goebbels','Rudolf Hess','Albert Speer','Erwin Rommel'], 100),
(1475, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Who served as Supreme Allied Commander in Europe during World War II?', NULL, 'Dwight D. Eisenhower', ARRAY['George Patton','Omar Bradley','Bernard Montgomery','Douglas MacArthur','George Marshall','Mark Clark'], 200),
(1476, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which German general was nicknamed the "Desert Fox" for his campaigns in North Africa?', NULL, 'Erwin Rommel', ARRAY['Heinz Guderian','Gerd von Rundstedt','Albert Kesselring','Walther Model','Fedor von Bock','Wilhelm Keitel'], 200),
(1477, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the codename for the top-secret U.S. program that developed the atomic bomb?', NULL, 'The Manhattan Project', ARRAY['Operation Trinity','Project Alberta','Operation Crossroads','Operation Paperclip','Operation Silverplate','The Alsos Mission'], 200),
(1478, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What date is celebrated as V-E Day (Victory in Europe)?', NULL, 'May 8, 1945', ARRAY['May 7, 1945','April 30, 1945','September 2, 1945','June 6, 1944','May 1, 1945','April 25, 1945'], 200),
(1479, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What date marks V-J Day, the formal Japanese surrender aboard the USS Missouri?', NULL, 'September 2, 1945', ARRAY['August 15, 1945','August 6, 1945','August 9, 1945','May 8, 1945','September 1, 1945','August 14, 1945'], 200),
(1480, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What German term, meaning "lightning war," describes the fast, coordinated tank-and-air offensive tactic used early in the war?', NULL, 'Blitzkrieg', ARRAY['Schwerpunkt','Wehrmacht','Panzerkrieg','Sitzkrieg','Kesselschlacht','Anschluss'], 200),
(1481, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'The systematic genocide of six million Jews by Nazi Germany during World War II is known as what?', NULL, 'The Holocaust', ARRAY['The Inquisition','The Reign of Terror','The Great Purge','Kristallnacht','The Nuremberg Laws','The Warsaw Ghetto Uprising'], 100),
(1482, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which young diarist hid with her family in an Amsterdam attic during the Nazi occupation of the Netherlands?', NULL, 'Anne Frank', ARRAY['Irena Sendler','Corrie ten Boom','Sophie Scholl','Hannah Senesh','Miep Gies','Edith Frank'], 100),
(1483, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the name of the German cipher machine used to encrypt military communications?', NULL, 'Enigma', ARRAY['Lorenz','Colossus','Purple','Fialka','Typex','SIGABA'], 200),
(1484, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which British mathematician led the team that broke the German Enigma code at Bletchley Park?', NULL, 'Alan Turing', ARRAY['Gordon Welchman','Dilly Knox','Bill Tutte','Max Newman','Stewart Menzies','Winston Churchill'], 300),
(1485, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'The 1940 air campaign in which the RAF defended the United Kingdom against the German Luftwaffe is known as what?', NULL, 'The Battle of Britain', ARRAY['The Blitz','The Battle of the Atlantic','Operation Sea Lion','The Phoney War','The Battle of France','The Dunkirk Evacuation'], 200),
(1486, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the codename for the 1940 evacuation of Allied troops from the beaches of Dunkirk, France?', NULL, 'Operation Dynamo', ARRAY['Operation Overlord','Operation Sea Lion','Operation Torch','Operation Market Garden','Operation Cobra','Operation Husky'], 300),
(1487, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the nickname of the atomic bomb dropped on Nagasaki?', NULL, 'Fat Man', ARRAY['Little Boy','Trinity','Thin Man','Gadget','Ivy Mike','Tallboy'], 300),
(1488, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which physicist directed the Manhattan Project''s Los Alamos Laboratory and is often called the "father of the atomic bomb"?', NULL, 'J. Robert Oppenheimer', ARRAY['Enrico Fermi','Albert Einstein','Niels Bohr','Edward Teller','Leslie Groves','Werner Heisenberg'], 300),
(1489, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What were the post-war tribunals that prosecuted senior Nazi officials for war crimes called?', NULL, 'The Nuremberg Trials', ARRAY['The Tokyo Trials','The Yalta Conference','The Potsdam Conference','The Geneva Convention','The Wannsee Conference','The Munich Agreement'], 200),
(1490, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'The iconic photograph of six U.S. Marines raising a flag was taken atop which mountain during the Battle of Iwo Jima?', NULL, 'Mount Suribachi', ARRAY['Mount Fuji','Hacksaw Ridge','Bunker Hill','Mount Tapotchau','Peleliu','Chichijima'], 300),
(1491, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which June 1942 naval battle is considered the turning point of the war in the Pacific?', NULL, 'The Battle of Midway', ARRAY['The Battle of the Coral Sea','The Battle of Leyte Gulf','The Battle of Guadalcanal','The Battle of the Philippine Sea','The Battle of Okinawa','The Battle of Iwo Jima'], 200),
(1492, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which of the five D-Day landing beaches was assigned to American forces and suffered the heaviest casualties?', NULL, 'Omaha Beach', ARRAY['Utah Beach','Gold Beach','Juno Beach','Sword Beach','Pointe du Hoc','Cherbourg'], 200),
(1493, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'At which 1945 conference did Roosevelt, Churchill, and Stalin plan the postwar reorganization of Europe?', NULL, 'The Yalta Conference', ARRAY['The Potsdam Conference','The Tehran Conference','The Casablanca Conference','The Munich Conference','The Atlantic Charter','The Cairo Conference'], 300),
(1494, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which 1945 conference, held after Germany''s surrender, decided how to administer occupied Germany?', NULL, 'The Potsdam Conference', ARRAY['The Yalta Conference','The Tehran Conference','The Casablanca Conference','The San Francisco Conference','The Dumbarton Oaks Conference','The Bretton Woods Conference'], 300),
(1495, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What term describes Japanese pilots who carried out deliberate suicide attacks by crashing their aircraft into Allied ships?', NULL, 'Kamikaze', ARRAY['Banzai','Bushido','Shinto','Zaibatsu','Ronin','Sensei'], 100),
(1496, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What was the name of the U.S. program that supplied Britain, the Soviet Union, and other Allies with war materials before America formally entered the war?', NULL, 'The Lend-Lease Act', ARRAY['The Marshall Plan','The Neutrality Acts','The Atlantic Charter','The Selective Service Act','The War Powers Act','The Cash and Carry policy'], 300),
(1497, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What name was given to the collaborationist French government that governed unoccupied southern France after 1940?', NULL, 'Vichy France', ARRAY['Free France','The Third Republic','The Fourth Republic','Occupied France','The Maquis','The Paris Commune'], 300),
(1498, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which French general led the Free French Forces in exile and later became President of France?', NULL, 'Charles de Gaulle', ARRAY['Philippe Pétain','Jean Moulin','Maxime Weygand','Georges Mandel','Pierre Laval','Henri Giraud'], 200),
(1499, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Who was the fascist dictator of Italy during World War II?', NULL, 'Benito Mussolini', ARRAY['Victor Emmanuel III','Pietro Badoglio','Galeazzo Ciano','Rodolfo Graziani','Italo Balbo','Achille Starace'], 100),
(1500, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What name is given to the first Black American military aviators, who flew combat missions escorting bombers in World War II?', NULL, 'The Tuskegee Airmen', ARRAY['The Flying Tigers','The Doolittle Raiders','The Devil''s Brigade','The Band of Brothers','The Screaming Eagles','The Dambusters'], 200),
(1501, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What cultural icon represented American women who took factory jobs producing war materials while men served overseas?', NULL, 'Rosie the Riveter', ARRAY['Lady Liberty','Betty Grable','Uncle Sam','Wendy the Welder','Molly Pitcher','Lois Lane'], 100),
(1502, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'What name is given to the major German offensive launched through the Ardennes forest in December 1944?', NULL, 'The Battle of the Bulge', ARRAY['Operation Market Garden','The Battle of Aachen','The Battle of Remagen','The Battle of Hürtgen Forest','The Falaise Pocket','The Siege of Bastogne'], 200),
(1503, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'In what year was the United Nations founded, in the aftermath of World War II?', NULL, '1945', ARRAY['1944','1946','1919','1939','1948','1950'], 100),
(1504, 'TRIVIA', 'WWII_HISTORY', NULL, NULL, 'Which country suffered the highest number of military and civilian deaths in World War II?', NULL, 'The Soviet Union', ARRAY['Germany','China','Poland','Japan','The United States','The United Kingdom'], 300);
